In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("C:/Users/USER/WEEK04_01_데이터분석중급Q/data_titanic/train.csv", index_col="PassengerId")

In [3]:
train.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
#1 번 문제 풀이

In [5]:
#우선 결측이 있나 없나 확인 해보기
train.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [6]:
train['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [7]:
# Survived 에 결측이 없는 것을 확인
# 1번이 생존 0이 사망이므로 생존자 총 인원수는 342, 사망자 총 인원수는 549이다

In [8]:
# 생존률은 생존자를 전체 인원으로 나누면 끝

In [9]:
a = len(train.loc[train['Survived'] == 1]) / len(train['Survived'])

In [10]:
# 결과를 출력한다
print(a)

0.3838383838383838

In [11]:
train['Survived'].value_counts() / len(train['Survived'])

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [12]:
# 2번문제 풀기

In [13]:
train['Survived(Status)'] = train['Survived'].replace({0 : 'Perish', 1 : 'Survived'})

In [14]:
train[['Survived', 'Survived(Status)']]

             Survived Survived(Status)
PassengerId
1                   0           Perish
2                   1         Survived
3                   1         Survived
4                   1         Survived
5                   0           Perish
...               ...              ...
887                 0           Perish
888                 1         Survived
889                 0           Perish
890                 1         Survived
891                 0           Perish

[891 rows x 2 columns]

In [15]:
train['Survived(Status)'].value_counts()

Perish      549
Survived    342
Name: Survived(Status), dtype: int64

In [16]:
# Pclass 값도 마찬가지로 변경하기

In [17]:
train['Pclass(Status)'] = train['Pclass'].replace({1 : 'First Class',
                                                   2 : 'Business',
                                                   3 : 'Economy'})

In [18]:
print(train[['Pclass', 'Pclass(Status)']])

             Pclass Pclass(Status)
PassengerId
1                 3        Economy
2                 1    First Class
3                 3        Economy
4                 1    First Class
5                 3        Economy
...             ...            ...
887               2       Business
888               1    First Class
889               3        Economy
890               1    First Class
891               3        Economy

[891 rows x 2 columns]

In [19]:
# 4번

In [20]:
train['Embarked(Status)'] = train['Embarked'].replace({'C' : 'Cherbourg',
                                                       'S' : 'Southampton',
                                                       'Q' : 'Queenstown'})

In [21]:
print(train[['Embarked', 'Embarked(Status)']])

            Embarked Embarked(Status)
PassengerId
1                  S      Southampton
2                  C        Cherbourg
3                  S      Southampton
4                  S      Southampton
5                  S      Southampton
...              ...              ...
887                S      Southampton
888                S      Southampton
889                S      Southampton
890                C        Cherbourg
891                Q       Queenstown

[891 rows x 2 columns]

In [22]:
# Embarked(Status)별 생존자 구하기
pd.pivot_table(data = train, index = 'Embarked(Status)', values = 'Survived')

                  Survived
Embarked(Status)
Cherbourg         0.553571
Queenstown        0.389610
Southampton       0.336957

In [23]:
# 5번 one-hot encoding 하기

In [24]:
train['Embarked(C)'] = [1 if x == 'C' else 0 for x in train['Embarked']]
train['Embarked(S)'] = [1 if x == 'S' else 0 for x in train['Embarked']]
train['Embarked(Q)'] = [1 if x == 'Q' else 0 for x in train['Embarked']]

In [25]:
train[['Embarked', 'Embarked(Status)', 'Embarked(C)', 'Embarked(S)', 'Embarked(Q)']]

            Embarked Embarked(Status)  Embarked(C)  Embarked(S)  Embarked(Q)
PassengerId
1                  S      Southampton            0            1            0
2                  C        Cherbourg            1            0            0
3                  S      Southampton            0            1            0
4                  S      Southampton            0            1            0
5                  S      Southampton            0            1            0
...              ...              ...          ...          ...          ...
887                S      Southampton            0            1            0
888                S      Southampton            0            1            0
889                S      Southampton            0            1            0
890                C        Cherbourg            1            0            0
891                Q       Queenstown            0            0            1

[891 rows x 5 columns]

In [26]:
# OR pd.get_dummies로 해도 됨

In [27]:
train['Age'].min()

0.42

In [28]:
# 6번 문제 
train['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [29]:
# 평균 약 27세
# 표준편차 약 14.5
# max age = 80
# min age = 0.42??? 생후 3~4개월 아이로 추측

In [30]:
# 7 번객실 등급별 나이 컬럼 구하기
pd.pivot_table(data=train, index='Pclass', values = 'Age')

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

In [31]:
# 8번 나이를 범위로 나눠서 생존률 구해보기
re = []
for i in train['Age']:
    if pd.isna(i):
        re.append(np.nan)
    elif i < 15:
        re.append('Young')
    elif i < 30:
        re.append('Medium')
    else:
        re.append('Old')

In [32]:
train['agetype'] = re

In [33]:
train[['Age', 'agetype']]

              Age agetype
PassengerId
1            22.0  Medium
2            38.0     Old
3            26.0  Medium
4            35.0     Old
5            35.0     Old
...           ...     ...
887          27.0  Medium
888          19.0  Medium
889           NaN     NaN
890          26.0  Medium
891          32.0     Old

[891 rows x 2 columns]

In [34]:
print(train[['Age', 'agetype']])

              Age agetype
PassengerId
1            22.0  Medium
2            38.0     Old
3            26.0  Medium
4            35.0     Old
5            35.0     Old
...           ...     ...
887          27.0  Medium
888          19.0  Medium
889           NaN     NaN
890          26.0  Medium
891          32.0     Old

[891 rows x 2 columns]

In [35]:
# agetype 별 승객 생존률
pd.pivot_table(data=train, index='agetype', values='Survived')

         Survived
agetype
Medium   0.362745
Old      0.406061
Young    0.576923

In [36]:
# 9번 나이가 비어있는 승객과 비지 않은 승객의 생존률 차이 구하기
train.loc[train['agetype'].isnull(), 'ageblank'] = 'blank'
train.loc[train['agetype'].notnull(), 'ageblank'] = 'not blank'

In [37]:
train[['Age','ageblank']]

              Age   ageblank
PassengerId
1            22.0  not blank
2            38.0  not blank
3            26.0  not blank
4            35.0  not blank
5            35.0  not blank
...           ...        ...
887          27.0  not blank
888          19.0  not blank
889           NaN      blank
890          26.0  not blank
891          32.0  not blank

[891 rows x 2 columns]

In [38]:
train.groupby('ageblank')['Survived'].mean()

ageblank
blank        0.293785
not blank    0.406162
Name: Survived, dtype: float64

In [39]:
pd.pivot_table(data=train, index='ageblank', values='Survived')

           Survived
ageblank
blank      0.293785
not blank  0.406162

In [40]:
# 10번 Pclass별 age나이 평균 구하기 
train.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [41]:
train['age(fill)'] = train['Age']

In [42]:
train.loc[(train['Age'].isnull()) & (train["Pclass"]==1),
          'age(fill)'] = train[train["Pclass"]==1]["Age"].mean()

train.loc[(train['Age'].isnull()) & (train["Pclass"]==2),
          'age(fill)'] = train[train["Pclass"]==2]["Age"].mean()

train.loc[(train['Age'].isnull()) & (train["Pclass"]==3),
          'age(fill)'] = train[train["Pclass"]==3]["Age"].mean()

In [43]:
train.loc[train['age(fill)'].isna()]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, Survived(Status), Pclass(Status), Embarked(Status), Embarked(C), Embarked(S), Embarked(Q), agetype, ageblank, age(fill)]
Index: []

In [44]:
train[['Pclass', 'Age', 'age(fill)']]

             Pclass   Age  age(fill)
PassengerId
1                 3  22.0   22.00000
2                 1  38.0   38.00000
3                 3  26.0   26.00000
4                 1  35.0   35.00000
5                 3  35.0   35.00000
...             ...   ...        ...
887               2  27.0   27.00000
888               1  19.0   19.00000
889               3   NaN   25.14062
890               1  26.0   26.00000
891               3  32.0   32.00000

[891 rows x 3 columns]

In [45]:
# 11번 sibsp, parch 분석

train['single'] = (train['SibSp'] == 0) & (train['Parch'] == 0)

In [46]:
train[['SibSp', 'Parch', 'single']]

             SibSp  Parch  single
PassengerId
1                1      0   False
2                1      0   False
3                0      0    True
4                1      0   False
5                0      0    True
...            ...    ...     ...
887              0      0    True
888              0      0    True
889              1      2   False
890              0      0    True
891              0      0    True

[891 rows x 3 columns]

In [47]:
# 12번 가족 수 구하기 
train['family_size'] = train['SibSp'] + train['Parch'] + 1
train['family_size']

PassengerId
1      2
2      2
3      1
4      2
5      1
      ..
887    1
888    1
889    4
890    1
891    1
Name: family_size, Length: 891, dtype: int64

In [48]:
#가족 수 별 생존률
train.groupby('family_size')['Survived'].mean()

family_size
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

In [49]:
pd.pivot_table(data=train, index="family_size", values="Survived")

             Survived
family_size
1            0.303538
2            0.552795
3            0.578431
4            0.724138
5            0.200000
6            0.136364
7            0.333333
8            0.000000
11           0.000000

In [50]:
# 13번 가족수 범위 구하기

In [51]:
result = []
for i in train['family_size']:
    if pd.isna(i):
        result.append(np.nan)
    elif i == 1:
        result.append('Single')
    elif i < 5:
        result.append('Nuclear')
    else:
        result.append('Big')

In [52]:
train['family_type'] = result

In [53]:
train[['family_size', 'family_type']]

             family_size family_type
PassengerId
1                      2     Nuclear
2                      2     Nuclear
3                      1      Single
4                      2     Nuclear
5                      1      Single
...                  ...         ...
887                    1      Single
888                    1      Single
889                    4     Nuclear
890                    1      Single
891                    1      Single

[891 rows x 2 columns]

In [54]:
# family_type 별 생존률 구하기
pd.pivot_table(data=train, index='family_type', values='Survived')

             Survived
family_type
Big          0.161290
Nuclear      0.578767
Single       0.303538

In [55]:
# 14 sigel nuclear big을 ont hot 인코딩 하기

In [56]:
train['family_type(Single)'] = [1 if x == 'Single' else 0 for x in train['family_type']]
train['family_type(Nuclear)'] = [1 if x == 'Nuclear' else 0 for x in train['family_type']]
train['family_type(Big)'] = [1 if x == 'Big' else 0 for x in train['family_type']]

In [57]:
train[['family_type', 'family_type(Single)',
       'family_type(Nuclear)', 'family_type(Big)']]

,family_type,family_type(Single),family_type(Nuclear),family_type(Big)
PassengerId,,,,
1,Nuclear,0,1,0
2,Nuclear,0,1,0
3,Single,1,0,0
4,Nuclear,0,1,0
5,Single,1,0,0
...,...,...,...,...
887,Single,1,0,0
888,Single,1,0,0
889,Nuclear,0,1,0
890,Single,1,0,0
891,Single,1,0,0

In [58]:
# 15 이름 분석 titel 추출

In [59]:
train['Title'] = train['Name'].str.extract(r',\s*([^.]*)\.')

In [60]:
train[['Name', 'Title']]

                                                          Name Title
PassengerId
1                                      Braund, Mr. Owen Harris    Mr
2            Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs
3                                       Heikkinen, Miss. Laina  Miss
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs
5                                     Allen, Mr. William Henry    Mr
...                                                        ...   ...
887                                      Montvila, Rev. Juozas   Rev
888                               Graham, Miss. Margaret Edith  Miss
889                   Johnston, Miss. Catherine Helen "Carrie"  Miss
890                                      Behr, Mr. Karl Howell    Mr
891                                        Dooley, Mr. Patrick    Mr

[891 rows x 2 columns]

In [61]:
# 16 이름 반복 패턴 정리

In [62]:
pd.crosstab(train["Title"], train["Survived"], margins=True)

Survived        0    1  All
Title
Capt            1    0    1
Col             1    1    2
Don             1    0    1
Dr              4    3    7
Jonkheer        1    0    1
Lady            0    1    1
Major           1    1    2
Master         17   23   40
Miss           55  127  182
Mlle            0    2    2
Mme             0    1    1
Mr            436   81  517
Mrs            26   99  125
Ms              0    1    1
Rev             6    0    6
Sir             0    1    1
the Countess    0    1    1
All           549  342  891

In [63]:
def get_cleaned_title(title):
    title = title.strip()
    if title == 'Mr' or title == 'Miss' or title == 'Mrs' or title == 'Master':
        return title
    else:
        return 'Others'

In [64]:
train['Title(Status)'] = train['Title'].apply(get_cleaned_title)

In [65]:
train[['Name', 'Title', 'Title(Status)']]

,Name,Title,Title(Status)
PassengerId,,,
1,"Braund, Mr. Owen Harris",Mr,Mr
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Mrs,Mrs
3,"Heikkinen, Miss. Laina",Miss,Miss
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Mrs,Mrs
5,"Allen, Mr. William Henry",Mr,Mr
...,...,...,...
887,"Montvila, Rev. Juozas",Rev,Others
888,"Graham, Miss. Margaret Edith",Miss,Miss
889,"Johnston, Miss. Catherine Helen ""Carrie""",Miss,Miss
890,"Behr, Mr. Karl Howell",Mr,Mr
891,"Dooley, Mr. Patrick",Mr,Mr

In [66]:
train['Title'] = train['Title'].str.strip()

In [67]:
train.loc[train['Title'] == 'Mr', 'Married'] = True

train.loc[train['Title'] == 'Master', 'Married'] = False

train.loc[train['Title'] == 'Mrs', 'Married'] = True

train.loc[train['Title'] == 'Miss', 'Married'] = False

In [68]:
print(train['Married'])

PassengerId
1       True
2       True
3      False
4       True
5       True
       ...
887      NaN
888    False
889    False
890     True
891     True
Name: Married, Length: 891, dtype: object

In [69]:
train[['Name', 'Title', 'Married']]

                                                          Name Title Married
PassengerId
1                                      Braund, Mr. Owen Harris    Mr    True
2            Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs    True
3                                       Heikkinen, Miss. Laina  Miss   False
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs    True
5                                     Allen, Mr. William Henry    Mr    True
...                                                        ...   ...     ...
887                                      Montvila, Rev. Juozas   Rev     NaN
888                               Graham, Miss. Margaret Edith  Miss   False
889                   Johnston, Miss. Catherine Helen "Carrie"  Miss   False
890                                      Behr, Mr. Karl Howell    Mr    True
891                                        Dooley, Mr. Patrick    Mr    True

[891 rows x 3 columns]

In [70]:
pd.pivot_table(data=train, index='Married', values='Survived')

         Survived
Married
False    0.675676
True     0.280374

In [71]:
train.to_csv('C:/Users/USER/WEEK04_01_데이터분석중급Q/data_titanic/train_one_hot.csv')

## 테스트 데이터 전처리

In [72]:
test = pd.read_csv("C:/Users/USER/WEEK04_01_데이터분석중급Q/data_titanic/test.csv",
                    index_col="PassengerId")

In [73]:
test

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [74]:
test['Pclass(Status)'] = test['Pclass'].replace({1 : 'First Class',
                                                   2 : 'Business',
                                                   3 : 'Economy'})

In [75]:
test['Embarked(Status)'] = test['Embarked'].replace({'C' : 'Cherbourg',
                                                     'S' : 'Southampton',
                                                     'Q' : 'Queenstown'})

In [76]:
test['Embarked(C)'] = [1 if x == 'C' else 0 for x in test['Embarked']]
test['Embarked(S)'] = [1 if x == 'S' else 0 for x in test['Embarked']]
test['Embarked(Q)'] = [1 if x == 'Q' else 0 for x in test['Embarked']]

In [77]:
re = []
for i in test['Age']:
    if pd.isna(i):
        re.append(np.nan)
    elif i < 15:
        re.append('Young')
    elif i < 30:
        re.append('Medium')
    else:
        re.append('Old')

In [78]:
test['agetype'] = re

In [79]:
test.loc[test['agetype'].isnull(), 'ageblank'] = 'blank'
test.loc[test['agetype'].notnull(), 'ageblank'] = 'not blank'

In [80]:
test['age(fill)'] = train['Age']

In [81]:
test.groupby('Pclass')['Age'].mean()

Pclass
1    40.918367
2    28.777500
3    24.027945
Name: Age, dtype: float64

In [82]:
test.loc[(test['Age'].isnull()) & (test['Pclass']) == 1, 'age(fill)'] = 40.918367
test.loc[(test['Age'].isnull()) & (test['Pclass']) == 2, 'age(fill)'] = 28.777500
test.loc[(test['Age'].isnull()) & (test['Pclass']) == 3, 'age(fill)'] = 24.027945

In [83]:
test['single'] = (test['SibSp'] == 0) & (test['Parch'] == 0)

In [84]:
test['family_size'] = test['SibSp'] + test['Parch'] + 1
test['family_size']

PassengerId
892     1
893     2
894     1
895     1
896     3
       ..
1305    1
1306    1
1307    1
1308    1
1309    3
Name: family_size, Length: 418, dtype: int64

In [85]:
result = []
for i in test['family_size']:
    if pd.isna(i):
        result.append(np.nan)
    elif i == 1:
        result.append('Single')
    elif i < 5:
        result.append('Nuclear')
    else:
        result.append('Big')

In [86]:
test['family_type'] = result

In [87]:
test['family_type(Single)'] = [1 if x == 'Single' else 0 for x in test['family_type']]
test['family_type(Nuclear)'] = [1 if x == 'Nuclear' else 0 for x in test['family_type']]
test['family_type(Big)'] = [1 if x == 'Big' else 0 for x in test['family_type']]

In [88]:
test['Title'] = test['Name'].str.extract(r',\s*([^.]*)\.')

In [89]:
test[['Name', 'Title']]

                                                     Name   Title
PassengerId
892                                      Kelly, Mr. James      Mr
893                      Wilkes, Mrs. James (Ellen Needs)     Mrs
894                             Myles, Mr. Thomas Francis      Mr
895                                      Wirz, Mr. Albert      Mr
896          Hirvonen, Mrs. Alexander (Helga E Lindqvist)     Mrs
...                                                   ...     ...
1305                                   Spector, Mr. Woolf      Mr
1306                         Oliva y Ocana, Dona. Fermina    Dona
1307                         Saether, Mr. Simon Sivertsen      Mr
1308                                  Ware, Mr. Frederick      Mr
1309                             Peter, Master. Michael J  Master

[418 rows x 2 columns]

In [90]:
def get_cleaned_title_test(title):
    title = title.strip()
    if title == 'Mr' or title == 'Miss' or title == 'Mrs' or title == 'Master':
        return title
    else:
        return 'Others'

In [91]:
test['Title(Status)'] = test['Title'].apply(get_cleaned_title_test)

In [92]:
test[['Name', 'Title', 'Title(Status)']]

,Name,Title,Title(Status)
PassengerId,,,
892,"Kelly, Mr. James",Mr,Mr
893,"Wilkes, Mrs. James (Ellen Needs)",Mrs,Mrs
894,"Myles, Mr. Thomas Francis",Mr,Mr
895,"Wirz, Mr. Albert",Mr,Mr
896,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",Mrs,Mrs
...,...,...,...
1305,"Spector, Mr. Woolf",Mr,Mr
1306,"Oliva y Ocana, Dona. Fermina",Dona,Others
1307,"Saether, Mr. Simon Sivertsen",Mr,Mr
1308,"Ware, Mr. Frederick",Mr,Mr
1309,"Peter, Master. Michael J",Master,Master

In [93]:
test['Title'] = test['Title'].str.strip()

In [94]:
test.loc[test['Title'] == 'Mr', 'Married'] = True

test.loc[test['Title'] == 'Master', 'Married'] = False

test.loc[test['Title'] == 'Mrs', 'Married'] = True

test.loc[test['Title'] == 'Miss', 'Married'] = False

In [95]:
print(train['Married'])

PassengerId
1       True
2       True
3      False
4       True
5       True
       ...
887      NaN
888    False
889    False
890     True
891     True
Name: Married, Length: 891, dtype: object

In [96]:
test[['Name', 'Title', 'Married']]

                                                     Name   Title Married
PassengerId
892                                      Kelly, Mr. James      Mr    True
893                      Wilkes, Mrs. James (Ellen Needs)     Mrs    True
894                             Myles, Mr. Thomas Francis      Mr    True
895                                      Wirz, Mr. Albert      Mr    True
896          Hirvonen, Mrs. Alexander (Helga E Lindqvist)     Mrs    True
...                                                   ...     ...     ...
1305                                   Spector, Mr. Woolf      Mr    True
1306                         Oliva y Ocana, Dona. Fermina    Dona     NaN
1307                         Saether, Mr. Simon Sivertsen      Mr    True
1308                                  Ware, Mr. Frederick      Mr    True
1309                             Peter, Master. Michael J  Master   False

[418 rows x 3 columns]

## 분석 시작

In [97]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [98]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Survived              891 non-null    int64
 1   Pclass                891 non-null    int64
 2   Name                  891 non-null    object
 3   Sex                   891 non-null    object
 4   Age                   714 non-null    float64
 5   SibSp                 891 non-null    int64
 6   Parch                 891 non-null    int64
 7   Ticket                891 non-null    object
 8   Fare                  891 non-null    float64
 9   Cabin                 204 non-null    object
 10  Embarked              889 non-null    object
 11  Survived(Status)      891 non-null    object
 12  Pclass(Status)        891 non-null    object
 13  Embarked(Status)      889 non-null    object
 14  Embarked(C)           891 non-null    int64
 15  Embarked(S)           891 non-null    int64
 16  Embarked(Q)           891 non-null    int64
 17  agetype               714 non-null    object
 18  ageblank              891 non-null    object
 19  age(fill)             891 non-null    float64
 20  single                891 non-null    bool
 21  family_size           891 non-null    int64
 22  family_type           891 non-null    object
 23  family_type(Single)   891 non-null    int64
 24  family_type(Nuclear)  891 non-null    int64
 25  family_type(Big)      891 non-null    int64
 26  Title                 891 non-null    object
 27  Title(Status)         891 non-null    object
 28  Married               864 non-null    object
dtypes: bool(1), float64(3), int64(11), object(14)
memory usage: 235.0+ KB

In [99]:
train['age(fill)'].isnull().sum()

0

In [100]:
x_train = train[['Pclass', 'SibSp', 'Parch',
                 'Fare', 'Embarked(C)', 'Embarked(S)',
                 'Embarked(Q)', 'age(fill)', 'family_size',
                 'family_type(Single)', 'family_type(Nuclear)',
                 'family_type(Big)']]

y_train = train['Survived']

x_test = test[['Pclass', 'SibSp', 'Parch',
               'Fare', 'Embarked(C)', 'Embarked(S)',
               'Embarked(Q)', 'age(fill)', 'family_size',
               'family_type(Single)', 'family_type(Nuclear)',
               'family_type(Big)']]

In [101]:
logist_reg = LogisticRegression(max_iter=5000)

logist_reg.fit(x_train, y_train)

LogisticRegression(max_iter=5000)

In [102]:
y_train_pred = logist_reg.predict(x_train)
print("Train Accuracy:", accuracy_score(y_train, y_train_pred))

Train Accuracy: 0.734006734006734

In [103]:
print(confusion_matrix(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))

[[471  78]
 [159 183]]
              precision    recall  f1-score   support

           0       0.75      0.86      0.80       549
           1       0.70      0.54      0.61       342

    accuracy                           0.73       891
   macro avg       0.72      0.70      0.70       891
weighted avg       0.73      0.73      0.73       891