In [179]:
import pandas as pd
import numpy as np

In [180]:
data = {
 'Name': ['Minsoo', 'Jihyun', 'Woohyun', 'Daeun'],
 'Korean': [88, 92, 85, 90],
 'English': [76, 95, 89, 85],
 'Math': [90, 88, 93, 99]
 }

In [181]:
# 1. 다음 데이터를 이용해DataFrame을 만드세요
df = pd.DataFrame(data)

In [182]:
df

      Name  Korean  English  Math
0   Minsoo      88       76    90
1   Jihyun      92       95    88
2  Woohyun      85       89    93
3    Daeun      90       85    99

In [183]:
# 2. 인덱스를 ['1번', '2번', '3번', '4번'] 으로 설정하세요.
df.rename(index={0 : '1번', 1 : '2번', 2 : '3번', 3 : '4번'}, inplace=True)

In [184]:
df

       Name  Korean  English  Math
1번   Minsoo      88       76    90
2번   Jihyun      92       95    88
3번  Woohyun      85       89    93
4번    Daeun      90       85    99

In [185]:
# 3. English 열만 출력하시오
df.iloc[:, [2]]

    English
1번       76
2번       95
3번       89
4번       85

In [186]:
df.loc[:, ['English']]

    English
1번       76
2번       95
3번       89
4번       85

In [187]:
# 4. 2번 학생의 모든 점수를 행 기준으로 출력하기
df.iloc[1]

Name       Jihyun
Korean         92
English        95
Math           88
Name: 2번, dtype: object

In [188]:
# 5. korea & math 열만 선택해서 출력하기

df[['Korean', 'Math']]

    Korean  Math
1번      88    90
2번      92    88
3번      85    93
4번      90    99

In [189]:
df.loc[:, ['Korean', 'Math']]

    Korean  Math
1번      88    90
2번      92    88
3번      85    93
4번      90    99

In [190]:
# 6. 인덱스를 0,1,2,3 숫자로 다시 초기화

df.reset_index(inplace=True)

In [191]:
df

  index     Name  Korean  English  Math
0    1번   Minsoo      88       76    90
1    2번   Jihyun      92       95    88
2    3번  Woohyun      85       89    93
3    4번    Daeun      90       85    99

In [201]:
#7. Name 열을 새 인덱스로 지정 
df.set_index(['Name'], inplace=True)

In [193]:
# 8. Woohyun의 점수를 조회하시오

In [204]:
df.loc['Woohyun']

index      3번
Korean     85
English    89
Math       93
Name: Woohyun, dtype: object

In [205]:
df.iloc[2:3]

        index  Korean  English  Math
Name
Woohyun    3번      85       89    93