In [8]:
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import rc

import numpy as np
import pandas as pd

import time
from selenium import webdriver
import requests

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

plt.rcParams["axes.unicode_minus"]=False
rc("font",family = "Malgun Gothic")
%matplotlib inline

import re
from bs4 import BeautifulSoup
from urllib.request import urlopen
from bs4 import BeautifulSoup
from tqdm import tqdm_notebook

import folium

In [15]:
url ="https://www.starbucks.co.kr/store/store_map.do"
driver = webdriver.Chrome()

In [16]:
driver.implicitly_wait(5)
driver.get(url)
time.sleep(5)

In [17]:
driver.find_element(By.CSS_SELECTOR, "#container > div > form > fieldset > div > section > article.find_store_cont > article > header.loca_search").click()
time.sleep(5)

In [18]:
driver.find_element(By.CSS_SELECTOR,"#container > div > form > fieldset > div > section > article.find_store_cont > article > article:nth-child(4) > div.loca_step1 > div.loca_step1_cont > ul > li:nth-child(10) > a").click()
time.sleep(5)
driver.find_element(By.CSS_SELECTOR,"#mCSB_2_container > ul > li:nth-child(1) > a").click()
time.sleep(5)

In [19]:
req = driver.page_source
soup = BeautifulSoup(req, 'html.parser')
time.sleep(5)

In [20]:
content = soup.find("div", id = "mCSB_3_container")
time.sleep(5)
contents = content.find_all("li")
time.sleep(5)

In [21]:
for element in contents:
    print(element.text.strip())

김해구산DT   경상남도 김해시 김해대로 1918 (구산동)1522-3232 리저브 매장 2번
김해진영DT   경상남도 김해시 진영읍 여래로20번길 34-26 1522-3232 리저브 매장 2번
신세계김해   경상남도 김해시 김해대로 2232 신세계백화점 1층1522-3232 리저브 매장 2번
김해이마트   경상남도 김해시 김해대로 2232 김해이마트 1층1522-3232 리저브 매장 2번
김해대로DT   경상남도 김해시 김해대로 2465 1522-3232 리저브 매장 2번
김해외동DT   경상남도 김해시 분성로 146 (외동)1522-3232 리저브 매장 2번
김해율하   경상남도 김해시 율하카페길 77 (관동동) 1층1522-3232 리저브 매장 2번
김해삼계   경상남도 김해시 가야로 182 (삼계동)1522-3232 리저브 매장 2번
김해내동   경상남도 김해시 경원로 67 (내동)1522-3232 리저브 매장 2번
서김해IC DT   경상남도 김해시 금관대로 820-22 (명법동)1522-3232 리저브 매장 2번
김해주촌DT   경상남도 김해시 주촌면 선천로 99 1522-3232 리저브 매장 2번
김해가야로DT   경상남도 김해시 가야로 450 (동상동)1522-3232 리저브 매장 2번
장유대청   경상남도 김해시 계동로 213 (대청동)1522-3232 리저브 매장 2번
장유율하   경상남도 김해시 율하6로 67 1층 105호 (장유동)1522-3232 리저브 매장 2번
진영신도시   경상남도 김해시 진영읍 장등로10번길 1 1522-3232 리저브 매장 2번
김해율하신도시   경상남도 김해시 율하3로 32 (율하동)1522-3232 리저브 매장 2번
김해금관대로DT   경상남도 김해시 금관대로 1293 (내동)1522-3232 리저브 매장 2번
밀양DT   경상남도 밀양시 밀양대로 1792 (삼문동)1522-3232 리저브 매장 2번
경남사천DT   경상남도 사천시 사천읍 사천대로 1844 1522-3232 리저브 매장 2번
사천벌리   경상남도 사천시 주공로 31 (벌리동)1522-3232 리저브 매장 2번
진주평거   경상남도 진주시 진양호로 206 BYC빌딩1층1522-3232 리저브 매장 2번
진주칠암DT   경상남도 진주시 진주대로829번길 2 (주약동)1522-3232 리저브 매장 2번
진주중안   경상남도 진주시 진양호로527번길 3 (중안동)1522-3232 리저브 매장 2번
진주신안   경상남도 진주시 진양호로 353 (신안동)1522-3232 리저브 매장 2번
진주경상대   경상남도 진주시 진주대로 510 (가좌동)1522-3232 리저브 매장 2번
진주초전DT   경상남도 진주시 대신로 411 (초전동)1522-3232 리저브 매장 2번
진주혁신도시   경상남도 진주시 에나로127번길 30 (충무공동)1522-3232 리저브 매장 2번
경상대칠암캠퍼스   경상남도 진주시 동진로 22 (칠암동)1522-3232 리저브 매장 2번
마산회원DT   경상남도 창원시 마산회원구 3·15대로 518 (회원동)1522-3232 리저브 매장 2번
창원상남로   경상남도 창원시 성산구 상남로 88 (상남동)1522-3232 리저브 매장 2번
마산역DT   경상남도 창원시 마산회원구 3·15대로 715 (석전동)1522-3232 리저브 매장 2번
마산해안대로DT   경상남도 창원시 마산합포구 해안대로 383 (오동동)1522-3232 리저브 매장 2번
진해자은DT   경상남도 창원시 진해구 진해대로 962 (자은동)1522-3232 리저브 매장 2번
창원역DT   경상남도 창원시 의창구 의창대로 68 (팔용동)1522-3232 리저브 매장 2번
창원호계DT   경상남도 창원시 마산회원구 내서읍 호원로 315 1522-3232 리저브 매장 2번
창원마창대교   경상남도 창원시 성산구 삼귀로 159 (귀곡동)1522-3232 리저브 매장 2번
삼성창원병원   경상남도 창원시 마산회원구 팔용로 158 (합성동)1522-3232 리저브 매장 2번
진해용원   경상남도 창원시 진해구 안골로 336 (용원동) 형제빌딩1522-3232 리저브 매장 2번
창원리베라   경상남도 창원시 성산구 중앙대로100번길 9 (상남동)1522-3232 리저브 매장 2번
창원상남중앙   경상남도 창원시 성산구 마디미로 20 (상남동)1522-3232 리저브 매장 2번
창원상남동   경상남도 창원시 성산구 상남로 132 (상남동)1522-3232 리저브 매장 2번
신세계마산   경상남도 창원시 마산합포구 합포로 251 (산호동) 신세계백화점 내 지하1층1522-3232 리저브 매장 2번
창원시티세븐   경상남도 창원시 성산구 원이대로 320 (대원동)1522-3232 리저브 매장 2번
경남대   경상남도 창원시 마산합포구 월영남로 3 (해운동)1522-3232 리저브 매장 2번
창원용지호수   경상남도 창원시 성산구 용지로169번길 1 (용호동)1522-3232 리저브 매장 2번
마산월남동DT   경상남도 창원시 마산합포구 3·15대로 70 (월남동2가)1522-3232 리저브 매장 2번
마산봉암로DT   경상남도 창원시 마산회원구 봉양로 118 (봉암동)1522-3232 리저브 매장 2번
진해경화역DT   경상남도 창원시 진해구 진해대로 698 (경화동)1522-3232 리저브 매장 2번
창원반림   경상남도 창원시 성산구 반송로 150 (반림동)1522-3232 리저브 매장 2번
창원유니시티   경상남도 창원시 의창구 중동중앙로 47 (중동)1522-3232 리저브 매장 2번
창원NC파크R   경상남도 창원시 마산회원구 삼호로 63 (양덕동), 창원NC파크1522-3232 리저브 매장 2번
창원중앙역   경상남도 창원시 의창구 용동로 91 (사림동)1522-3232 리저브 매장 2번
진해부산신항   경상남도 창원시 진해구 신항동로 121 (용원동) 112호1522-3232 리저브 매장 2번
창원경상대병원   경상남도 창원시 성산구 삼정자로 11 (성주동)1522-3232 리저브 매장 2번
창원대로DT   경상남도 창원시 성산구 성산패총로 182 (가음정동)1522-3232 리저브 매장 2번
창원사파   경상남도 창원시 성산구 창이대로689번길 4-4 (사파동) 1,2층1522-3232 리저브 매장 2번
창원파티마병원   경상남도 창원시 의창구 창이대로 45 (명서동)1522-3232 리저브 매장 2번
창원내서   경상남도 창원시 마산회원구 내서읍 광려천서로 81 1522-3232 리저브 매장 2번
창원대방   경상남도 창원시 성산구 가양로124번길 4 (대방동),  1층 104호1522-3232 리저브 매장 2번
마산진동DT   경상남도 창원시 마산합포구 진동면 삼진의거대로 589-1 1522-3232 리저브 매장 2번
통영이마트   경상남도 통영시 광도면 죽림4로 9 1522-3232 리저브 매장 2번
통영죽림   경상남도 통영시 광도면 죽림해안로 64-72 1522-3232 리저브 매장 2번
통영북신DT   경상남도 통영시 중앙로 273 (북신동)1522-3232 리저브 매장 2번
거제대로DT   경상남도 거제시 거제대로 4521 (수월동)1522-3232 리저브 매장 2번
거제고현   경상남도 거제시 거제중앙로 1936 (고현동)1522-3232 리저브 매장 2번
소노캄거제   경상남도 거제시 일운면 거제대로 2660 1층 110호1522-3232 리저브 매장 2번
거제상동DT   경상남도 거제시 거제중앙로 1647 (상동동)1522-3232 리저브 매장 2번
거제옥포DT   경상남도 거제시 거제대로 3718 (옥포동)1522-3232 리저브 매장 2번
거제장평   경상남도 거제시 장평3로 43 (장평동)1522-3232 리저브 매장 2번
남양산IC DT   경상남도 양산시 동면 양산대로 5321522-3232 리저브 매장 2번
양산증산역   경상남도 양산시 물금읍 증산역로 177 1522-3232 리저브 매장 2번
양산가촌   경상남도 양산시 물금읍 야리로 25 1522-3232 리저브 매장 2번
양산덕계DT   경상남도 양산시 웅상대로 860 (덕계동)1522-3232 리저브 매장 2번
양산터미널   경상남도 양산시 양산역1길 7 (중부동) 양산시외버스터미널1522-3232 리저브 매장 2번
양산범어   경상남도 양산시 물금읍 범어로 621522-3232 리저브 매장 2번
양산이마트   경상남도 양산시 양산역6길 12, 양산이마트 1층 (중부동)1522-3232 리저브 매장 2번
양산물금DT   경상남도 양산시 물금읍 황산로 346 1522-3232 리저브 매장 2번
양산통도사   경상남도 양산시 하북면 충렬로 1553 1522-3232 리저브 매장 2번
양산부산대학교병원   경상남도 양산시 물금읍 금오로 20 1522-3232 리저브 매장 2번
양산신기DT   경상남도 양산시 양산대로 947 (신기동)1522-3232 리저브 매장 2번

In [16]:
contents[0].text

' 김해구산DT   경상남도 김해시 김해대로 1918 (구산동)1522-3232 리저브 매장 2번'

In [17]:
starbucks_soup_list = soup.select('#mCSB_3 li.quickResultLstCon')
starbucks_soup_list

[<li class="quickResultLstCon" data-code="3589" data-hlytag="null" data-index="0" data-lat="35.255314991" data-long="128.866384281" data-name="김해구산DT" data-storecd="1442" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해구산DT" data-store="1442" data-yn="N">김해구산DT  </strong> <p class="result_details">경상남도 김해시 김해대로 1918 (구산동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3847" data-hlytag="null" data-index="1" data-lat="35.3060040933565" data-long="128.731753216114" data-name="김해진영DT" data-storecd="1647" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해진영DT" data-store="1647" data-yn="N">김해진영DT  </strong> <p class="result_details">경상남도 김해시 진영읍 여래로20번길 34-26 <br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3307" data-hlytag="null" data-index="2" data-lat="35.22848288" data-long="128.873045617" data-name="신세계김해" data-storecd="1083" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="신세계김해" data-store="1083" data-yn="N">신세계김해  </strong> <p class="result_details">경상남도 김해시 김해대로 2232 신세계백화점 1층<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3306" data-hlytag="null" data-index="3" data-lat="35.229997434" data-long="128.872135886" data-name="김해이마트" data-storecd="1080" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해이마트" data-store="1080" data-yn="N">김해이마트  </strong> <p class="result_details">경상남도 김해시 김해대로 2232 김해이마트 1층<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3026" data-hlytag="null" data-index="4" data-lat="35.227992" data-long="128.896545" data-name="김해대로DT" data-storecd="846" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해대로DT" data-store="846" data-yn="N">김해대로DT  </strong> <p class="result_details">경상남도 김해시 김해대로 2465 <br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9972" data-hlytag="null" data-index="5" data-lat="35.22962555422071" data-long="128.86294818906367" data-name="김해외동DT" data-storecd="802" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해외동DT" data-store="802" data-yn="N">김해외동DT  </strong> <p class="result_details">경상남도 김해시 분성로 146 (외동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9904" data-hlytag="null" data-index="6" data-lat="35.176597" data-long="128.812782" data-name="김해율하" data-storecd="711" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해율하" data-store="711" data-yn="N">김해율하  </strong> <p class="result_details">경상남도 김해시 율하카페길 77 (관동동) 1층<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9761" data-hlytag="null" data-index="7" data-lat="35.261527" data-long="128.871614" data-name="김해삼계" data-storecd="626" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해삼계" data-store="626" data-yn="N">김해삼계  </strong> <p class="result_details">경상남도 김해시 가야로 182 (삼계동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9621" data-hlytag="null" data-index="8" data-lat="35.2371519" data-long="128.86752079999996" data-name="김해내동" data-storecd="437" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해내동" data-store="437" data-yn="N">김해내동  </strong> <p class="result_details">경상남도 김해시 경원로 67 (내동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4329" data-hlytag="null" data-index="9" data-lat="35.2038771973106" data-long="128.837970580838" data-name="서김해IC DT" data-storecd="2106" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="서김해IC DT" data-store="2106" data-yn="N">서김해IC DT  </strong> <p class="result_details">경상남도 김해시 금관대로 820-22 (명법동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4083" data-hlytag="null" data-index="10" data-lat="35.23513407443546" data-long="128.84338277636144" data-name="김해주촌DT" data-storecd="1917" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해주촌DT" data-store="1917" data-yn="N">김해주촌DT  </strong> <p class="result_details">경상남도 김해시 주촌면 선천로 99 <br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4029" data-hlytag="null" data-index="11" data-lat="35.2409026" data-long="128.8843414" data-name="김해가야로DT" data-storecd="1946" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해가야로DT" data-store="1946" data-yn="N">김해가야로DT  </strong> <p class="result_details">경상남도 김해시 가야로 450 (동상동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4262" data-hlytag="null" data-index="12" data-lat="35.1904824838804" data-long="128.801458773585" data-name="장유대청" data-storecd="2121" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="장유대청" data-store="2121" data-yn="N">장유대청  </strong> <p class="result_details">경상남도 김해시 계동로 213 (대청동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4216" data-hlytag="null" data-index="13" data-lat="35.17158031793282" data-long="128.82264103029556" data-name="장유율하" data-storecd="1926" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="장유율하" data-store="1926" data-yn="N">장유율하  </strong> <p class="result_details">경상남도 김해시 율하6로 67 1층 105호 (장유동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4331" data-hlytag="null" data-index="14" data-lat="35.3074088" data-long="128.7352952" data-name="진영신도시" data-storecd="2017" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진영신도시" data-store="2017" data-yn="N">진영신도시  </strong> <p class="result_details">경상남도 김해시 진영읍 장등로10번길 1 <br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3868" data-hlytag="null" data-index="15" data-lat="35.170945" data-long="128.813901" data-name="김해율하신도시" data-storecd="1685" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해율하신도시" data-store="1685" data-yn="N">김해율하신도시  </strong> <p class="result_details">경상남도 김해시 율하3로 32 (율하동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3950" data-hlytag="null" data-index="16" data-lat="35.23984059831166" data-long="128.86103985434852" data-name="김해금관대로DT" data-storecd="1796" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해금관대로DT" data-store="1796" data-yn="N">김해금관대로DT  </strong> <p class="result_details">경상남도 김해시 금관대로 1293 (내동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3773" data-hlytag="null" data-index="17" data-lat="35.4853274" data-long="128.7512487" data-name="밀양DT" data-storecd="1598" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="밀양DT" data-store="1598" data-yn="N">밀양DT  </strong> <p class="result_details">경상남도 밀양시 밀양대로 1792 (삼문동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3710" data-hlytag="null" data-index="18" data-lat="35.080980061" data-long="128.083555012" data-name="경남사천DT" data-storecd="1523" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="경남사천DT" data-store="1523" data-yn="N">경남사천DT  </strong> <p class="result_details">경상남도 사천시 사천읍 사천대로 1844 <br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9982" data-hlytag="null" data-index="19" data-lat="34.9411367" data-long="128.0863809" data-name="사천벌리" data-storecd="795" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="사천벌리" data-store="795" data-yn="N">사천벌리  </strong> <p class="result_details">경상남도 사천시 주공로 31 (벌리동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3216" data-hlytag="null" data-index="20" data-lat="35.172324" data-long="128.060063" data-name="진주평거" data-storecd="1029" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진주평거" data-store="1029" data-yn="N">진주평거  </strong> <p class="result_details">경상남도 진주시 진양호로 206 BYC빌딩1층<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3176" data-hlytag="null" data-index="21" data-lat="35.1749073" data-long="128.0929658" data-name="진주칠암DT" data-storecd="1000" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진주칠암DT" data-store="1000" data-yn="N">진주칠암DT  </strong> <p class="result_details">경상남도 진주시 진주대로829번길 2 (주약동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9917" data-hlytag="null" data-index="22" data-lat="35.1929303" data-long="128.0830383" data-name="진주중안" data-storecd="728" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진주중안" data-store="728" data-yn="N">진주중안  </strong> <p class="result_details">경상남도 진주시 진양호로527번길 3 (중안동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9842" data-hlytag="null" data-index="23" data-lat="35.1843723" data-long="128.06821" data-name="진주신안" data-storecd="647" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진주신안" data-store="647" data-yn="N">진주신안  </strong> <p class="result_details">경상남도 진주시 진양호로 353 (신안동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9485" data-hlytag="null" data-index="24" data-lat="35.15241245" data-long="128.1057139" data-name="진주경상대" data-storecd="32" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진주경상대" data-store="32" data-yn="N">진주경상대  </strong> <p class="result_details">경상남도 진주시 진주대로 510 (가좌동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4334" data-hlytag="null" data-index="25" data-lat="35.197388" data-long="128.116032" data-name="진주초전DT" data-storecd="2131" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진주초전DT" data-store="2131" data-yn="N">진주초전DT  </strong> <p class="result_details">경상남도 진주시 대신로 411 (초전동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3954" data-hlytag="null" data-index="26" data-lat="35.180806" data-long="128.143995" data-name="진주혁신도시" data-storecd="1781" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진주혁신도시" data-store="1781" data-yn="N">진주혁신도시  </strong> <p class="result_details">경상남도 진주시 에나로127번길 30 (충무공동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4176" data-hlytag="null" data-index="27" data-lat="35.17852605" data-long="128.09362329" data-name="경상대칠암캠퍼스" data-storecd="1891" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="경상대칠암캠퍼스" data-store="1891" data-yn="N">경상대칠암캠퍼스  </strong> <p class="result_details">경상남도 진주시 동진로 22 (칠암동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3717" data-hlytag="null" data-index="28" data-lat="35.2206567" data-long="128.5744344" data-name="마산회원DT" data-storecd="1536" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="마산회원DT" data-store="1536" data-yn="N">마산회원DT  </strong> <p class="result_details">경상남도 창원시 마산회원구 3·15대로 518 (회원동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3775" data-hlytag="null" data-index="29" data-lat="35.22125492182339" data-long="128.68112777591222" data-name="창원상남로" data-storecd="1507" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원상남로" data-store="1507" data-yn="N">창원상남로  </strong> <p class="result_details">경상남도 창원시 성산구 상남로 88 (상남동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3559" data-hlytag="null" data-index="30" data-lat="35.2362004" data-long="128.5805449" data-name="마산역DT" data-storecd="1454" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="마산역DT" data-store="1454" data-yn="N">마산역DT  </strong> <p class="result_details">경상남도 창원시 마산회원구 3·15대로 715 (석전동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3560" data-hlytag="null" data-index="31" data-lat="35.204510322" data-long="128.580955938" data-name="마산해안대로DT" data-storecd="1416" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="마산해안대로DT" data-store="1416" data-yn="N">마산해안대로DT  </strong> <p class="result_details">경상남도 창원시 마산합포구 해안대로 383 (오동동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3501" data-hlytag="null" data-index="32" data-lat="35.143793" data-long="128.706881" data-name="진해자은DT" data-storecd="1310" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진해자은DT" data-store="1310" data-yn="N">진해자은DT  </strong> <p class="result_details">경상남도 창원시 진해구 진해대로 962 (자은동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3458" data-hlytag="null" data-index="33" data-lat="35.257123763205655" data-long="128.60783874514348" data-name="창원역DT" data-storecd="1312" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원역DT" data-store="1312" data-yn="N">창원역DT  </strong> <p class="result_details">경상남도 창원시 의창구 의창대로 68 (팔용동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3395" data-hlytag="null" data-index="34" data-lat="35.261507" data-long="128.523036" data-name="창원호계DT" data-storecd="1238" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원호계DT" data-store="1238" data-yn="N">창원호계DT  </strong> <p class="result_details">경상남도 창원시 마산회원구 내서읍 호원로 315 <br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3445" data-hlytag="null" data-index="35" data-lat="35.170623" data-long="128.597273" data-name="창원마창대교" data-storecd="1230" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원마창대교" data-store="1230" data-yn="N">창원마창대교  </strong> <p class="result_details">경상남도 창원시 성산구 삼귀로 159 (귀곡동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3285" data-hlytag="null" data-index="36" data-lat="35.24256504" data-long="128.59246006" data-name="삼성창원병원" data-storecd="1074" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="삼성창원병원" data-store="1074" data-yn="N">삼성창원병원  </strong> <p class="result_details">경상남도 창원시 마산회원구 팔용로 158 (합성동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9925" data-hlytag="null" data-index="37" data-lat="35.101122" data-long="128.809896" data-name="진해용원" data-storecd="738" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="진해용원" data-store="738" data-yn="N">진해용원  </strong> <p class="result_details">경상남도 창원시 진해구 안골로 336 (용원동) 형제빌딩<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9827" data-hlytag="null" data-index="38" data-lat="35.223320549409216" data-long="128.68034668776863" data-name="창원리베라" data-storecd="635" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원리베라" data-store="635" data-yn="N">창원리베라  </strong> <p class="result_details">경상남도 창원시 성산구 중앙대로100번길 9 (상남동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9820" data-hlytag="null" data-index="39" data-lat="35.22267448372802" data-long="128.68435847588333" data-name="창원상남중앙" data-storecd="624" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원상남중앙" data-store="624" data-yn="N">창원상남중앙  </strong> <p class="result_details">경상남도 창원시 성산구 마디미로 20 (상남동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9424" data-hlytag="null" data-index="40" data-lat="35.224557340244004" data-long="128.6839223863128" data-name="창원상남동" data-storecd="95" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원상남동" data-store="95" data-yn="N">창원상남동  </strong> <p class="result_details">경상남도 창원시 성산구 상남로 132 (상남동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9408" data-hlytag="null" data-index="41" data-lat="35.21936342" data-long="128.58675435" data-name="신세계마산" data-storecd="69" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="신세계마산" data-store="69" data-yn="N">신세계마산  </strong> <p class="result_details">경상남도 창원시 마산합포구 합포로 251 (산호동) 신세계백화점 내 지하1층<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9448" data-hlytag="null" data-index="42" data-lat="35.2401056" data-long="128.6535354" data-name="창원시티세븐" data-storecd="131" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원시티세븐" data-store="131" data-yn="N">창원시티세븐  </strong> <p class="result_details">경상남도 창원시 성산구 원이대로 320 (대원동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9749" data-hlytag="null" data-index="43" data-lat="35.178461" data-long="128.5586" data-name="경남대" data-storecd="570" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="경남대" data-store="570" data-yn="N">경남대  </strong> <p class="result_details">경상남도 창원시 마산합포구 월영남로 3 (해운동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="9657" data-hlytag="null" data-index="44" data-lat="35.229881" data-long="128.68189" data-name="창원용지호수" data-storecd="464" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="창원용지호수" data-store="464" data-yn="N">창원용지호수  </strong> <p class="result_details">경상남도 창원시 성산구 용지로169번길 1 (용호동)<br/>1522-3232</p> <i class="pin_general">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="3904" data-hlytag="null" data-index="45" data-lat="35.18582228792928" data-long="128.5612262376559" data-name="마산월남동DT" data-storecd="1741" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="마산월남동DT" data-store="1741" data-yn="N">마산월남동DT  </strong> <p class="result_details">경상남도 창원시 마산합포구 3·15대로 70 (월남동2가)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,
 <li class="quickResultLstCon" data-code="4126" data-hlytag="null" data-index="46" data-lat="35.218819535" data-long="128.59931839" data-name="마산봉암로DT" data-storecd="1912" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="마산봉암로DT" data-store="1912" data-yn="N">마산봉암로DT  </strong> <p class="result_details">경상남도 창원시 마산회원구 봉양로 118 (봉암동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>,

In [18]:
len(starbucks_soup_list)

80

In [19]:
starbucks_store = starbucks_soup_list[0]
starbucks_store

<li class="quickResultLstCon" data-code="3589" data-hlytag="null" data-index="0" data-lat="35.255314991" data-long="128.866384281" data-name="김해구산DT" data-storecd="1442" style="background:#fff"> <strong data-my_siren_order_store_yn="N" data-name="김해구산DT" data-store="1442" data-yn="N">김해구산DT  </strong> <p class="result_details">경상남도 김해시 김해대로 1918 (구산동)<br/>1522-3232</p> <i class="pin_generalDT">리저브 매장 2번</i></li>

In [20]:
name = starbucks_store.select('strong')[0].text.strip()

In [21]:
name

'김해구산DT'

In [22]:
lat = starbucks_store['data-lat'].strip()
lat

'35.255314991'

In [23]:
long = starbucks_store['data-long'].strip()
long

'128.866384281'

In [24]:
store_type = starbucks_store.select('i')[0]['class'][0][4:]
print(type(store_type))
store_type

<class 'str'>

'generalDT'

In [25]:
address = str(starbucks_store.select('#mCSB_3 p.result_details')[0]).split('<br/>')[0].split('>')[1]
address

'경상남도 김해시 김해대로 1918 (구산동)'

In [26]:
tel = str(starbucks_store.select('#mCSB_3 p.result_details')[0]).split('<br/>')[1].split('<')[0]
print(type(tel))
tel

<class 'str'>

'1522-3232'

In [71]:
starbucks_list = []

for item in starbucks_soup_list:
    name = item.select('strong')[0].text.strip()
    lat = item['data-lat'].strip()
    lng = item['data-long'].strip()
    store_type = item.select('i')[0]['class'][0][4:]
    address = str(item.select('#mCSB_3 p.result_details')[0]).split('<br/>')[0].split('>')[1]
    tel = str(item.select('#mCSB_3 p.result_details')[0]).split('<br/>')[1].split('<')[0]

    starbucks_list.append([name, lat, lng, store_type, address, tel])

starbucks_list

[['김해구산DT',
  '35.255314991',
  '128.866384281',
  'generalDT',
  '경상남도 김해시 김해대로 1918 (구산동)',
  '1522-3232'],
 ['김해진영DT',
  '35.3060040933565',
  '128.731753216114',
  'generalDT',
  '경상남도 김해시 진영읍 여래로20번길 34-26 ',
  '1522-3232'],
 ['신세계김해',
  '35.22848288',
  '128.873045617',
  'general',
  '경상남도 김해시 김해대로 2232 신세계백화점 1층',
  '1522-3232'],
 ['김해이마트',
  '35.229997434',
  '128.872135886',
  'general',
  '경상남도 김해시 김해대로 2232 김해이마트 1층',
  '1522-3232'],
 ['김해대로DT',
  '35.227992',
  '128.896545',
  'generalDT',
  '경상남도 김해시 김해대로 2465 ',
  '1522-3232'],
 ['김해외동DT',
  '35.22962555422071',
  '128.86294818906367',
  'generalDT',
  '경상남도 김해시 분성로 146 (외동)',
  '1522-3232'],
 ['김해율하',
  '35.176597',
  '128.812782',
  'general',
  '경상남도 김해시 율하카페길 77 (관동동) 1층',
  '1522-3232'],
 ['김해삼계',
  '35.261527',
  '128.871614',
  'general',
  '경상남도 김해시 가야로 182 (삼계동)',
  '1522-3232'],
 ['김해내동',
  '35.2371519',
  '128.86752079999996',
  'general',
  '경상남도 김해시 경원로 67 (내동)',
  '1522-3232'],
 ['서김해IC DT',
  '35.2038771973106',
  '128.837970580838',
  'generalDT',
  '경상남도 김해시 금관대로 820-22 (명법동)',
  '1522-3232'],
 ['김해주촌DT',
  '35.23513407443546',
  '128.84338277636144',
  'generalDT',
  '경상남도 김해시 주촌면 선천로 99 ',
  '1522-3232'],
 ['김해가야로DT',
  '35.2409026',
  '128.8843414',
  'generalDT',
  '경상남도 김해시 가야로 450 (동상동)',
  '1522-3232'],
 ['장유대청',
  '35.1904824838804',
  '128.801458773585',
  'general',
  '경상남도 김해시 계동로 213 (대청동)',
  '1522-3232'],
 ['장유율하',
  '35.17158031793282',
  '128.82264103029556',
  'general',
  '경상남도 김해시 율하6로 67 1층 105호 (장유동)',
  '1522-3232'],
 ['진영신도시',
  '35.3074088',
  '128.7352952',
  'general',
  '경상남도 김해시 진영읍 장등로10번길 1 ',
  '1522-3232'],
 ['김해율하신도시',
  '35.170945',
  '128.813901',
  'general',
  '경상남도 김해시 율하3로 32 (율하동)',
  '1522-3232'],
 ['김해금관대로DT',
  '35.23984059831166',
  '128.86103985434852',
  'generalDT',
  '경상남도 김해시 금관대로 1293 (내동)',
  '1522-3232'],
 ['밀양DT',
  '35.4853274',
  '128.7512487',
  'generalDT',
  '경상남도 밀양시 밀양대로 1792 (삼문동)',
  '1522-3232'],
 ['경남사천DT',
  '35.080980061',
  '128.083555012',
  'generalDT',
  '경상남도 사천시 사천읍 사천대로 1844 ',
  '1522-3232'],
 ['사천벌리',
  '34.9411367',
  '128.0863809',
  'general',
  '경상남도 사천시 주공로 31 (벌리동)',
  '1522-3232'],
 ['진주평거',
  '35.172324',
  '128.060063',
  'general',
  '경상남도 진주시 진양호로 206 BYC빌딩1층',
  '1522-3232'],
 ['진주칠암DT',
  '35.1749073',
  '128.0929658',
  'generalDT',
  '경상남도 진주시 진주대로829번길 2 (주약동)',
  '1522-3232'],
 ['진주중안',
  '35.1929303',
  '128.0830383',
  'general',
  '경상남도 진주시 진양호로527번길 3 (중안동)',
  '1522-3232'],
 ['진주신안',
  '35.1843723',
  '128.06821',
  'general',
  '경상남도 진주시 진양호로 353 (신안동)',
  '1522-3232'],
 ['진주경상대',
  '35.15241245',
  '128.1057139',
  'general',
  '경상남도 진주시 진주대로 510 (가좌동)',
  '1522-3232'],
 ['진주초전DT',
  '35.197388',
  '128.116032',
  'generalDT',
  '경상남도 진주시 대신로 411 (초전동)',
  '1522-3232'],
 ['진주혁신도시',
  '35.180806',
  '128.143995',
  'general',
  '경상남도 진주시 에나로127번길 30 (충무공동)',
  '1522-3232'],
 ['경상대칠암캠퍼스',
  '35.17852605',
  '128.09362329',
  'general',
  '경상남도 진주시 동진로 22 (칠암동)',
  '1522-3232'],
 ['마산회원DT',
  '35.2206567',
  '128.5744344',
  'generalDT',
  '경상남도 창원시 마산회원구 3·15대로 518 (회원동)',
  '1522-3232'],
 ['창원상남로',
  '35.22125492182339',
  '128.68112777591222',
  'general',
  '경상남도 창원시 성산구 상남로 88 (상남동)',
  '1522-3232'],
 ['마산역DT',
  '35.2362004',
  '128.5805449',
  'generalDT',
  '경상남도 창원시 마산회원구 3·15대로 715 (석전동)',
  '1522-3232'],
 ['마산해안대로DT',
  '35.204510322',
  '128.580955938',
  'generalDT',
  '경상남도 창원시 마산합포구 해안대로 383 (오동동)',
  '1522-3232'],
 ['진해자은DT',
  '35.143793',
  '128.706881',
  'generalDT',
  '경상남도 창원시 진해구 진해대로 962 (자은동)',
  '1522-3232'],
 ['창원역DT',
  '35.257123763205655',
  '128.60783874514348',
  'generalDT',
  '경상남도 창원시 의창구 의창대로 68 (팔용동)',
  '1522-3232'],
 ['창원호계DT',
  '35.261507',
  '128.523036',
  'generalDT',
  '경상남도 창원시 마산회원구 내서읍 호원로 315 ',
  '1522-3232'],
 ['창원마창대교',
  '35.170623',
  '128.597273',
  'general',
  '경상남도 창원시 성산구 삼귀로 159 (귀곡동)',
  '1522-3232'],
 ['삼성창원병원',
  '35.24256504',
  '128.59246006',
  'general',
  '경상남도 창원시 마산회원구 팔용로 158 (합성동)',
  '1522-3232'],
 ['진해용원',
  '35.101122',
  '128.809896',
  'general',
  '경상남도 창원시 진해구 안골로 336 (용원동) 형제빌딩',
  '1522-3232'],
 ['창원리베라',
  '35.223320549409216',
  '128.68034668776863',
  'general',
  '경상남도 창원시 성산구 중앙대로100번길 9 (상남동)',
  '1522-3232'],
 ['창원상남중앙',
  '35.22267448372802',
  '128.68435847588333',
  'general',
  '경상남도 창원시 성산구 마디미로 20 (상남동)',
  '1522-3232'],
 ['창원상남동',
  '35.224557340244004',
  '128.6839223863128',
  'general',
  '경상남도 창원시 성산구 상남로 132 (상남동)',
  '1522-3232'],
 ['신세계마산',
  '35.21936342',
  '128.58675435',
  'general',
  '경상남도 창원시 마산합포구 합포로 251 (산호동) 신세계백화점 내 지하1층',
  '1522-3232'],
 ['창원시티세븐',
  '35.2401056',
  '128.6535354',
  'general',
  '경상남도 창원시 성산구 원이대로 320 (대원동)',
  '1522-3232'],
 ['경남대',
  '35.178461',
  '128.5586',
  'general',
  '경상남도 창원시 마산합포구 월영남로 3 (해운동)',
  '1522-3232'],
 ['창원용지호수',
  '35.229881',
  '128.68189',
  'general',
  '경상남도 창원시 성산구 용지로169번길 1 (용호동)',
  '1522-3232'],
 ['마산월남동DT',
  '35.18582228792928',
  '128.5612262376559',
  'generalDT',
  '경상남도 창원시 마산합포구 3·15대로 70 (월남동2가)',
  '1522-3232'],
 ['마산봉암로DT',
  '35.218819535',
  '128.59931839',
  'generalDT',
  '경상남도 창원시 마산회원구 봉양로 118 (봉암동)',
  '1522-3232'],
 ['진해경화역DT',
  '35.159250543',
  '128.691820647',
  'generalDT',
  '경상남도 창원시 진해구 진해대로 698 (경화동)',
  '1522-3232'],
 ['창원반림',
  '35.23604777804381',
  '128.6717420588344',
  'general',
  '경상남도 창원시 성산구 반송로 150 (반림동)',
  '1522-3232'],
 ['창원유니시티',
  '35.25650979',
  '128.62529086',
  'general',
  '경상남도 창원시 의창구 중동중앙로 47 (중동)',
  '1522-3232'],
 ['창원NC파크R',
  '35.22342934',
  '128.58269298',
  'reserve',
  '경상남도 창원시 마산회원구 삼호로 63 (양덕동), 창원NC파크',
  '1522-3232'],
 ['창원중앙역',
  '35.238753',
  '128.701406',
  'general',
  '경상남도 창원시 의창구 용동로 91 (사림동)',
  '1522-3232'],
 ['진해부산신항',
  '35.08841817',
  '128.81473883',
  'general',
  '경상남도 창원시 진해구 신항동로 121 (용원동) 112호',
  '1522-3232'],
 ['창원경상대병원',
  '35.19889879953514',
  '128.70698434933143',
  'general',
  '경상남도 창원시 성산구 삼정자로 11 (성주동)',
  '1522-3232'],
 ['창원대로DT',
  '35.2095615963132',
  '128.683681913031',
  'generalDT',
  '경상남도 창원시 성산구 성산패총로 182 (가음정동)',
  '1522-3232'],
 ['창원사파',
  '35.22312859619139',
  '128.7007017411131',
  'general',
  '경상남도 창원시 성산구 창이대로689번길 4-4 (사파동) 1,2층',
  '1522-3232'],
 ['창원파티마병원',
  '35.23679725',
  '128.64583124',
  'general',
  '경상남도 창원시 의창구 창이대로 45 (명서동)',
  '1522-3232'],
 ['창원내서',
  '35.2490312214725',
  '128.510681026083',
  'general',
  '경상남도 창원시 마산회원구 내서읍 광려천서로 81 ',
  '1522-3232'],
 ['창원대방',
  '35.209242593324696',
  '128.7066600750564',
  'general',
  '경상남도 창원시 성산구 가양로124번길 4 (대방동),  1층 104호',
  '1522-3232'],
 ['마산진동DT',
  '35.114308',
  '128.482418',
  'generalDT',
  '경상남도 창원시 마산합포구 진동면 삼진의거대로 589-1 ',
  '1522-3232'],
 ['통영이마트',
  '34.886597495',
  '128.417895263',
  'general',
  '경상남도 통영시 광도면 죽림4로 9 ',
  '1522-3232'],
 ['통영죽림',
  '34.882242',
  '128.422815',
  'general',
  '경상남도 통영시 광도면 죽림해안로 64-72 ',
  '1522-3232'],
 ['통영북신DT',
  '34.8547537944604',
  '128.428162068745',
  'generalDT',
  '경상남도 통영시 중앙로 273 (북신동)',
  '1522-3232'],
 ['거제대로DT',
  '34.894667',
  '128.641559',
  'generalDT',
  '경상남도 거제시 거제대로 4521 (수월동)',
  '1522-3232'],
 ['거제고현',
  '34.8907709',
  '128.6221848',
  'general',
  '경상남도 거제시 거제중앙로 1936 (고현동)',
  '1522-3232'],
 ['소노캄거제',
  '34.84384342',
  '128.702360332',
  'general',
  '경상남도 거제시 일운면 거제대로 2660 1층 110호',
  '1522-3232'],
 ['거제상동DT',
  '34.868574',
  '128.637515',
  'generalDT',
  '경상남도 거제시 거제중앙로 1647 (상동동)',
  '1522-3232'],
 ['거제옥포DT',
  '34.88898292568363',
  '128.69150509599194',
  'generalDT',
  '경상남도 거제시 거제대로 3718 (옥포동)',
  '1522-3232'],
 ['거제장평',
  '34.892974',
  '128.608744',
  'general',
  '경상남도 거제시 장평3로 43 (장평동)',
  '1522-3232'],
 ['남양산IC DT',
  '35.319987',
  '129.030485',
  'generalDT',
  '경상남도 양산시 동면 양산대로 532',
  '1522-3232'],
 ['양산증산역',
  '35.30898019301058',
  '129.00945734552783',
  'general',
  '경상남도 양산시 물금읍 증산역로 177 ',
  '1522-3232'],
 ['양산가촌',
  '35.3171469065169',
  '129.001498744995',
  'general',
  '경상남도 양산시 물금읍 야리로 25 ',
  '1522-3232'],
 ['양산덕계DT',
  '35.3761068854677',
  '129.15552304160047',
  'generalDT',
  '경상남도 양산시 웅상대로 860 (덕계동)',
  '1522-3232'],
 ['양산터미널',
  '35.3353404',
  '129.02685',
  'general',
  '경상남도 양산시 양산역1길 7 (중부동) 양산시외버스터미널',
  '1522-3232'],
 ['양산범어',
  '35.3287435162243',
  '129.014307074921',
  'general',
  '경상남도 양산시 물금읍 범어로 62',
  '1522-3232'],
 ['양산이마트',
  '35.33706607072501',
  '129.02690161220042',
  'general',
  '경상남도 양산시 양산역6길 12, 양산이마트 1층 (중부동)',
  '1522-3232'],
 ['양산물금DT',
  '35.3075354379422',
  '128.986400471101',
  'generalDT',
  '경상남도 양산시 물금읍 황산로 346 ',
  '1522-3232'],
 ['양산통도사',
  '35.4722969553954',
  '129.079009870903',
  'general',
  '경상남도 양산시 하북면 충렬로 1553 ',
  '1522-3232'],
 ['양산부산대학교병원',
  '35.32806420490634',
  '129.0063449567268',
  'general',
  '경상남도 양산시 물금읍 금오로 20 ',
  '1522-3232'],
 ['양산신기DT',
  '35.355007631985565',
  '129.03816275068954',
  'generalDT',
  '경상남도 양산시 양산대로 947 (신기동)',
  '1522-3232']]

In [28]:
df_starbucks_list = pd.DataFrame(starbucks_list)
df_starbucks_list.head(10)

,0,1,2,3,4,5
0,김해구산DT,35.255314991,128.866384281,generalDT,경상남도 김해시 김해대로 1918 (구산동),1522-3232
1,김해진영DT,35.3060040933565,128.731753216114,generalDT,경상남도 김해시 진영읍 여래로20번길 34-26,1522-3232
2,신세계김해,35.22848288,128.873045617,general,경상남도 김해시 김해대로 2232 신세계백화점 1층,1522-3232
3,김해이마트,35.229997434,128.872135886,general,경상남도 김해시 김해대로 2232 김해이마트 1층,1522-3232
4,김해대로DT,35.227992,128.896545,generalDT,경상남도 김해시 김해대로 2465,1522-3232
5,김해외동DT,35.22962555422071,128.86294818906367,generalDT,경상남도 김해시 분성로 146 (외동),1522-3232
6,김해율하,35.176597,128.812782,general,경상남도 김해시 율하카페길 77 (관동동) 1층,1522-3232
7,김해삼계,35.261527,128.871614,general,경상남도 김해시 가야로 182 (삼계동),1522-3232
8,김해내동,35.2371519,128.86752079999996,general,경상남도 김해시 경원로 67 (내동),1522-3232
9,서김해IC DT,35.2038771973106,128.837970580838,generalDT,경상남도 김해시 금관대로 820-22 (명법동),1522-3232

In [29]:
address.split(" ")[1]

'양산시'

In [68]:
len(starbucksList)

80

In [69]:
starbucksList

[{'매장이름': '김해구산DT',
  '주소': '경상남도 김해시 김해대로 1918 (구산동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해진영DT',
  '주소': '경상남도 김해시 진영읍 여래로20번길 34-26 ',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '신세계김해',
  '주소': '경상남도 김해시 김해대로 2232 신세계백화점 1층',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해이마트',
  '주소': '경상남도 김해시 김해대로 2232 김해이마트 1층',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해대로DT',
  '주소': '경상남도 김해시 김해대로 2465 ',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해외동DT',
  '주소': '경상남도 김해시 분성로 146 (외동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해율하',
  '주소': '경상남도 김해시 율하카페길 77 (관동동) 1층',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해삼계',
  '주소': '경상남도 김해시 가야로 182 (삼계동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해내동',
  '주소': '경상남도 김해시 경원로 67 (내동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '서김해IC DT',
  '주소': '경상남도 김해시 금관대로 820-22 (명법동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해주촌DT',
  '주소': '경상남도 김해시 주촌면 선천로 99 ',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해가야로DT',
  '주소': '경상남도 김해시 가야로 450 (동상동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '장유대청',
  '주소': '경상남도 김해시 계동로 213 (대청동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '장유율하',
  '주소': '경상남도 김해시 율하6로 67 1층 105호 (장유동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진영신도시',
  '주소': '경상남도 김해시 진영읍 장등로10번길 1 ',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해율하신도시',
  '주소': '경상남도 김해시 율하3로 32 (율하동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '김해금관대로DT',
  '주소': '경상남도 김해시 금관대로 1293 (내동)',
  '구': '김해시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '밀양DT',
  '주소': '경상남도 밀양시 밀양대로 1792 (삼문동)',
  '구': '밀양시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '경남사천DT',
  '주소': '경상남도 사천시 사천읍 사천대로 1844 ',
  '구': '사천시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '사천벌리',
  '주소': '경상남도 사천시 주공로 31 (벌리동)',
  '구': '사천시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진주평거',
  '주소': '경상남도 진주시 진양호로 206 BYC빌딩1층',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진주칠암DT',
  '주소': '경상남도 진주시 진주대로829번길 2 (주약동)',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진주중안',
  '주소': '경상남도 진주시 진양호로527번길 3 (중안동)',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진주신안',
  '주소': '경상남도 진주시 진양호로 353 (신안동)',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진주경상대',
  '주소': '경상남도 진주시 진주대로 510 (가좌동)',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진주초전DT',
  '주소': '경상남도 진주시 대신로 411 (초전동)',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진주혁신도시',
  '주소': '경상남도 진주시 에나로127번길 30 (충무공동)',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '경상대칠암캠퍼스',
  '주소': '경상남도 진주시 동진로 22 (칠암동)',
  '구': '진주시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '마산회원DT',
  '주소': '경상남도 창원시 마산회원구 3·15대로 518 (회원동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원상남로',
  '주소': '경상남도 창원시 성산구 상남로 88 (상남동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '마산역DT',
  '주소': '경상남도 창원시 마산회원구 3·15대로 715 (석전동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '마산해안대로DT',
  '주소': '경상남도 창원시 마산합포구 해안대로 383 (오동동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진해자은DT',
  '주소': '경상남도 창원시 진해구 진해대로 962 (자은동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원역DT',
  '주소': '경상남도 창원시 의창구 의창대로 68 (팔용동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원호계DT',
  '주소': '경상남도 창원시 마산회원구 내서읍 호원로 315 ',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원마창대교',
  '주소': '경상남도 창원시 성산구 삼귀로 159 (귀곡동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '삼성창원병원',
  '주소': '경상남도 창원시 마산회원구 팔용로 158 (합성동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진해용원',
  '주소': '경상남도 창원시 진해구 안골로 336 (용원동) 형제빌딩',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원리베라',
  '주소': '경상남도 창원시 성산구 중앙대로100번길 9 (상남동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원상남중앙',
  '주소': '경상남도 창원시 성산구 마디미로 20 (상남동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원상남동',
  '주소': '경상남도 창원시 성산구 상남로 132 (상남동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '신세계마산',
  '주소': '경상남도 창원시 마산합포구 합포로 251 (산호동) 신세계백화점 내 지하1층',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원시티세븐',
  '주소': '경상남도 창원시 성산구 원이대로 320 (대원동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '경남대',
  '주소': '경상남도 창원시 마산합포구 월영남로 3 (해운동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원용지호수',
  '주소': '경상남도 창원시 성산구 용지로169번길 1 (용호동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '마산월남동DT',
  '주소': '경상남도 창원시 마산합포구 3·15대로 70 (월남동2가)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '마산봉암로DT',
  '주소': '경상남도 창원시 마산회원구 봉양로 118 (봉암동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진해경화역DT',
  '주소': '경상남도 창원시 진해구 진해대로 698 (경화동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원반림',
  '주소': '경상남도 창원시 성산구 반송로 150 (반림동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원유니시티',
  '주소': '경상남도 창원시 의창구 중동중앙로 47 (중동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원NC파크R',
  '주소': '경상남도 창원시 마산회원구 삼호로 63 (양덕동), 창원NC파크',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원중앙역',
  '주소': '경상남도 창원시 의창구 용동로 91 (사림동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '진해부산신항',
  '주소': '경상남도 창원시 진해구 신항동로 121 (용원동) 112호',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원경상대병원',
  '주소': '경상남도 창원시 성산구 삼정자로 11 (성주동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원대로DT',
  '주소': '경상남도 창원시 성산구 성산패총로 182 (가음정동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원사파',
  '주소': '경상남도 창원시 성산구 창이대로689번길 4-4 (사파동) 1,2층',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원파티마병원',
  '주소': '경상남도 창원시 의창구 창이대로 45 (명서동)',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원내서',
  '주소': '경상남도 창원시 마산회원구 내서읍 광려천서로 81 ',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '창원대방',
  '주소': '경상남도 창원시 성산구 가양로124번길 4 (대방동),  1층 104호',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '마산진동DT',
  '주소': '경상남도 창원시 마산합포구 진동면 삼진의거대로 589-1 ',
  '구': '창원시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '통영이마트',
  '주소': '경상남도 통영시 광도면 죽림4로 9 ',
  '구': '통영시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '통영죽림',
  '주소': '경상남도 통영시 광도면 죽림해안로 64-72 ',
  '구': '통영시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '통영북신DT',
  '주소': '경상남도 통영시 중앙로 273 (북신동)',
  '구': '통영시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '거제대로DT',
  '주소': '경상남도 거제시 거제대로 4521 (수월동)',
  '구': '거제시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '거제고현',
  '주소': '경상남도 거제시 거제중앙로 1936 (고현동)',
  '구': '거제시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '소노캄거제',
  '주소': '경상남도 거제시 일운면 거제대로 2660 1층 110호',
  '구': '거제시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '거제상동DT',
  '주소': '경상남도 거제시 거제중앙로 1647 (상동동)',
  '구': '거제시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '거제옥포DT',
  '주소': '경상남도 거제시 거제대로 3718 (옥포동)',
  '구': '거제시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '거제장평',
  '주소': '경상남도 거제시 장평3로 43 (장평동)',
  '구': '거제시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '남양산IC DT',
  '주소': '경상남도 양산시 동면 양산대로 532',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산증산역',
  '주소': '경상남도 양산시 물금읍 증산역로 177 ',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산가촌',
  '주소': '경상남도 양산시 물금읍 야리로 25 ',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산덕계DT',
  '주소': '경상남도 양산시 웅상대로 860 (덕계동)',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산터미널',
  '주소': '경상남도 양산시 양산역1길 7 (중부동) 양산시외버스터미널',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산범어',
  '주소': '경상남도 양산시 물금읍 범어로 62',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산이마트',
  '주소': '경상남도 양산시 양산역6길 12, 양산이마트 1층 (중부동)',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산물금DT',
  '주소': '경상남도 양산시 물금읍 황산로 346 ',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산통도사',
  '주소': '경상남도 양산시 하북면 충렬로 1553 ',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산부산대학교병원',
  '주소': '경상남도 양산시 물금읍 금오로 20 ',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None},
 {'매장이름': '양산신기DT',
  '주소': '경상남도 양산시 양산대로 947 (신기동)',
  '구': '양산시',
  '브랜드': '스타벅스',
  '위도': None,
  '경도': None}]

In [73]:
# starbucks_list : [[name, lat, lng, store_type, address, tel], ...] 형태
starbucks_df_list = []

for item in starbucks_list:
    name = item[0]
    lat = float(item[1])   # 문자열 → 실수
    lng = float(item[2])
    address = item[4]
    gu = address.split(" ")[1]  # 주소에서 구 추출
    brand = "스타벅스"

    starbucks_df_list.append({
        "매장이름": name,
        "주소": address,
        "구": gu,
        "브랜드": brand,
        "위도": lat,
        "경도": lng
    })

# DataFrame 생성
df = pd.DataFrame(starbucks_df_list)
df

,매장이름,주소,구,브랜드,위도,경도
0,김해구산DT,경상남도 김해시 김해대로 1918 (구산동),김해시,스타벅스,35.255315,128.866384
1,김해진영DT,경상남도 김해시 진영읍 여래로20번길 34-26,김해시,스타벅스,35.306004,128.731753
2,신세계김해,경상남도 김해시 김해대로 2232 신세계백화점 1층,김해시,스타벅스,35.228483,128.873046
3,김해이마트,경상남도 김해시 김해대로 2232 김해이마트 1층,김해시,스타벅스,35.229997,128.872136
4,김해대로DT,경상남도 김해시 김해대로 2465,김해시,스타벅스,35.227992,128.896545
...,...,...,...,...,...,...
75,양산이마트,"경상남도 양산시 양산역6길 12, 양산이마트 1층 (중부동)",양산시,스타벅스,35.337066,129.026902
76,양산물금DT,경상남도 양산시 물금읍 황산로 346,양산시,스타벅스,35.307535,128.986400
77,양산통도사,경상남도 양산시 하북면 충렬로 1553,양산시,스타벅스,35.472297,129.079010
78,양산부산대학교병원,경상남도 양산시 물금읍 금오로 20,양산시,스타벅스,35.328064,129.006345
79,양산신기DT,경상남도 양산시 양산대로 947 (신기동),양산시,스타벅스,35.355008,129.038163

In [74]:
df.to_csv("C:/Users/USER/WEEK04_03_스타벅스크롤링/data/경남_raw_selenium.csv")

In [52]:
import requests
from urllib.parse import quote

In [93]:
import folium

# 1) 지도 중심 설정 (한국 평균 좌표)
map_center = [df['위도'].mean(), df['경도'].mean()]
starbucks_map = folium.Map(location=map_center, zoom_start=9)

# 2) 매장별 마커 추가
for idx, row in df.iterrows():
    folium.Marker(
        location=[row['위도'], row['경도']],
        popup=f"{row['매장이름']}<br>{row['주소']}",
        icon=folium.Icon(color='green', icon='coffee', prefix='fa')
    ).add_to(starbucks_map)

# 3) 지도 표시
starbucks_map

In [99]:
!pip install ipyleaflet

Collecting ipyleaflet
  Downloading ipyleaflet-0.20.0-py3-none-any.whl (31 kB)
Collecting jupyter-leaflet<0.21,>=0.20
  Downloading jupyter_leaflet-0.20.0-py3-none-any.whl (1.1 MB)
Requirement already satisfied: ipywidgets<9,>=7.6.0 in c:\users\user\anaconda3\lib\site-packages (from ipyleaflet) (7.6.5)
Requirement already satisfied: xyzservices>=2021.8.1 in c:\users\user\anaconda3\lib\site-packages (from ipyleaflet) (2025.11.0)
Collecting traittypes<3,>=0.2.1
  Downloading traittypes-0.2.3-py2.py3-none-any.whl (8.1 kB)
Requirement already satisfied: branca>=0.5.0 in c:\users\user\anaconda3\lib\site-packages (from ipyleaflet) (0.8.2)
Requirement already satisfied: jinja2>=3 in c:\users\user\anaconda3\lib\site-packages (from branca>=0.5.0->ipyleaflet) (3.1.6)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (1.0.0)
Requirement already satisfied: ipython>=4.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (8.2.0)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (6.9.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (3.5.2)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (5.3.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (5.1.1)
Requirement already satisfied: jupyter-client<8.0 in c:\users\user\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (6.1.12)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (1.5.1)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in c:\users\user\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (0.1.2)
Requirement already satisfied: nest-asyncio in c:\users\user\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (1.5.5)
Requirement already satisfied: tornado<7.0,>=4.2 in c:\users\user\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (6.1)
Requirement already satisfied: jedi>=0.16 in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.18.1)
Requirement already satisfied: backcall in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.0)
Requirement already satisfied: decorator in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (5.1.1)
Requirement already satisfied: pygments>=2.4.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.11.2)
Requirement already satisfied: setuptools>=18.5 in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (61.2.0)
Requirement already satisfied: pickleshare in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.7.5)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.4.4)
Requirement already satisfied: stack-data in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (3.0.20)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\anaconda3\lib\site-packages (from jinja2>=3->branca>=0.5.0->ipyleaflet) (2.0.1)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (4.9.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\user\anaconda3\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (2.8.2)
Requirement already satisfied: pyzmq>=13 in c:\users\user\anaconda3\lib\site-packages (from jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (22.3.0)
Requirement already satisfied: pywin32>=1.0 in c:\users\user\anaconda3\lib\site-packages (from jupyter-core>=4.6.0->jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (302)
Requirement already satisfied: fastjsonschema in c:\users\user\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.15.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\user\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.4.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (25.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.18.0)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.1->jupyter-client<8.0->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (1.16.0)
Requirement already satisfied: notebook>=4.4.1 in c:\users\user\anaconda3\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (6.4.8)
Requirement already satisfied: nbconvert in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (6.4.4)
Requirement already satisfied: argon2-cffi in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (21.3.0)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.13.1)
Requirement already satisfied: prometheus-client in c:\users\user\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.13.1)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\user\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.0.2)
Requirement already satisfied: argon2-cffi-bindings in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (1.15.0)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.21)
Requirement already satisfied: jupyterlab-pygments in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.8.4)
Requirement already satisfied: testpath in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.5.0)
Requirement already satisfied: defusedxml in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.7.1)
Requirement already satisfied: bleach in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (1.5.0)
Requirement already satisfied: beautifulsoup4 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.11.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.5.13)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\user\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.3.1)
Requirement already satisfied: webencodings in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.5.1)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\user\anaconda3\lib\site-packages (from packaging->bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (3.0.4)
Requirement already satisfied: pure-eval in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.2)
Requirement already satisfied: asttokens in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.0.5)
Requirement already satisfied: executing in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.8.3)
Installing collected packages: traittypes, jupyter-leaflet, ipyleaflet
Successfully installed ipyleaflet-0.20.0 jupyter-leaflet-0.20.0 traittypes-0.2.3

In [109]:
import folium

m = folium.Map(location=[35.1665, 128.5780], zoom_start=12)  # 서울 중심
m

In [113]:
res = requests.get("https://www.naver.com/")
html = res.text

In [114]:
html

'   <!doctype html> <html lang="ko" class="fzoom"> <head> <meta charset="utf-8"> <meta name="Referrer" content="origin"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=1190"> <title>NAVER</title> <meta name="apple-mobile-web-app-title" content="NAVER"/> <meta name="robots" content="index,nofollow"/> <meta name="description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta property="og:title" content="네이버"> <meta property="og:url" content="https://www.naver.com/"> <meta property="og:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta property="og:description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta name="twitter:card" content="summary"> <meta name="twitter:title" content=""> <meta name="twitter:url" content="https://www.naver.com/"> <meta name="twitter:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta name="twitter:description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta name="google-site-verification" content="uru5NJKa1Bfr5nv5AdQ26Qat7UrPU_02l-PIZRLzI-g"/> <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?1"> <link rel="apple-touch-icon-precomposed" href="https://s.pstatic.net/static/www/nFavicon96.png"/> <link rel="apple-touch-icon" sizes="114x114" href="https://s.pstatic.net/static/www/u/2014/0328/mma_204243574.png"/> <link rel="apple-touch-icon" href="https://s.pstatic.net/static/www/u/2014/0328/mma_20432863.png"/> <link rel="stylesheet" href="https://ssl.pstatic.net/sstatic/search/pc/css/sp_autocomplete_251001.css"> <link rel="canonical" href="https://www.naver.com/"> <link rel="alternate" media="only screen and (max-width: 767px)" href="https://m.naver.com/"> <script>window.gladsdk=window.gladsdk||{},window.gladsdk.cmd=window.gladsdk.cmd||[],window.ndpsdk=window.ndpsdk||{},window.ndpsdk.cmd=window.ndpsdk.cmd||[],window.ndpsdk.polyfill=window.ndpsdk.polyfill||{cmd:[]};var g_ssc="navertop.v5";window.nsc=g_ssc,window.nmain=window.nmain||{},window.nmain.jsOrigin="www"</script> <script>window.ntm=window.ntm||[]</script> <script async src="https://ssl.pstatic.net/tveta/libs/ndpsdk/prod/ndp-loader.js"></script> <script async src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js"></script> <script src="https://ssl.pstatic.net/tveta/libs/assets/js/pc/main/min/pc.veta.core.min.js" defer="defer"></script>  <script>\nwindow["EAGER-DATA"] = window["EAGER-DATA"] || {};\nwindow["EAGER-DATA"]["PC-FEED-WRAPPER"] = {"@type":"BLOCK","blocks":[{"@type":"BLOCK","blocks":[{"@type":"BLOCK","blocks":[{"@type":"PC-CAS-EDIT-CONTENTS-BLOCK","blocks":null,"materials":[{"@type":"MATERIAL-PC-FEED-EDIT","title":"파닉스스타터부터 스토리북 론칭까지","url":"https://brand.naver.com/nobuyoung","image":{"url":"https://s.pstatic.net/static/www/mobile/edit/20251125_1095/upload_1764065199071pvu4p.png"},"highlight":"노부영 x 신규 론칭 기획전","title2":"우리 아이 첫 영어는 노부영과 함께","source":{"name":"더 자세한 내용 만나보기"},"_id":"68c3b0ddeaf13652d094140c"},{"@type":"MATERIAL-PC-FEED-EDIT","title":"전집부터 사운드북까지","url":"https://shopping.naver.com/festa/onsale/68c0e103d6bdc9272d53f786","image":{"url":"https://s.pstatic.net/static/www/mobile/edit/20251117_1095/upload_1763357034585DYKdU.jpg"},"highlight":"인플루언서 픽!","title2":"육아 인플루언서 추천 도서 특가 기획전","source":{"name":"더 자세한 내용 만나보기"},"_id":"68c3b0ddeaf13652d094140d"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"layout":"BIG-IMAGE-2","orderRandom":false,"_id":null,"@type":"PC-CAS-EDIT-CONTENTS-BLOCK","@code":null,"@template":"NONE","@flowId":null,"@flowExecutionId":null,"@provider":null,"@lastModifiedAt":null}],"materials":null,"excludeInPaging":false,"positionForPaging":0,"realtime":false,"_id":null,"@type":"BLOCK","@code":"PC-FEED-CULTURE-CAS-EDIT","@template":"PC-FEED-CAS-EDIT","@flowId":null,"@flowExecutionId":null,"@provider":null,"@lastModifiedAt":null},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"세계의 주인 각본집","url":"https://msearch.shopping.naver.com/book/catalog/57537373683","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5753737%2F57537373683.20251104090618.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"윤가은","service":"안온북스"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b727"},{"@type":"MATERIAL-PC-FEED","title":"나노 바나나","url":"https://msearch.shopping.naver.com/book/catalog/57259885634","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5725988%2F57259885634.20251017092849.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"문수민, 박범희, 앤미디어","service":"생능북스"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b728"},{"@type":"MATERIAL-PC-FEED","title":"저스트고 동유럽 3개국(2025~2026)","url":"https://msearch.shopping.naver.com/book/catalog/57341025788","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5734102%2F57341025788.20251024093501.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"백상현","service":"시공사"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b729"},{"@type":"MATERIAL-PC-FEED","title":"정승제의 수학 대모험 1","url":"https://msearch.shopping.naver.com/book/catalog/57634638251","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5763463%2F57634638251.20251108091744.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"설민석, 조영선","service":"단꿈아이"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b72a"},{"@type":"MATERIAL-PC-FEED","title":"Xistory 자이스토리 영어 독해 기본 (2026년)","url":"https://msearch.shopping.naver.com/book/catalog/57345150915","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5734515%2F57345150915.20251023202351.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"김현아, 박형우, 신수진, 윤혜경, 이아영","service":"수경출판사"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b72b"},{"@type":"MATERIAL-PC-FEED","title":"피치 바이 매거진 Pitch by Magazine (계간) : vol.18 [2025]","url":"https://msearch.shopping.naver.com/book/catalog/57756476006","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5775647%2F57756476006.20251113201841.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"피치바이피치㈜ 편집부","service":"(주)피치바이피치"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b72c"},{"@type":"MATERIAL-PC-FEED","title":"성수동","url":"https://msearch.shopping.naver.com/book/catalog/57640484036","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5764048%2F57640484036.20251108091756.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"정원오","service":"메디치미디어"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b72d"},{"@type":"MATERIAL-PC-FEED","title":"본능적 연출","url":"https://msearch.shopping.naver.com/book/catalog/57611923301","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5761192%2F57611923301.20251108071544.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"정영택","service":"다이브캐스트"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b72e"},{"@type":"MATERIAL-PC-FEED","title":"Highlights brainPLAY(브레인플레이) Vol 7","url":"https://msearch.shopping.naver.com/book/catalog/57410605599","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5741060%2F57410605599.20251030071216.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"하이라이츠 어린이","service":"소란i(소란아이)"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b72f"},{"@type":"MATERIAL-PC-FEED","title":"크리스마스까지 24일 행복한 도서관 Advent Calendar","url":"https://msearch.shopping.naver.com/book/catalog/57328095194","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5732809%2F57328095194.20251024071543.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"레슬리 심스","service":"어스본코리아"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b730"},{"@type":"MATERIAL-PC-FEED","title":"영어 회화 패턴 훈련 1차 임계점","url":"https://msearch.shopping.naver.com/book/catalog/57394991333","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5739499%2F57394991333.20251028075351.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"신원섭, Diana Salazar","service":"사람in"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b731"},{"@type":"MATERIAL-PC-FEED","title":"2026 양승아 응급처치학개론 단원별예상문제","url":"https://msearch.shopping.naver.com/book/catalog/57640486405","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5764048%2F57640486405.20251108091745.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"양승아","service":"포러스"},"showLiveBadge":false,"_id":"660a0b5d0f404c1848d9b732"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"title":"분야별 신간 도서","needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-CULTURE-NEW-BOOK","@template":"SIX-COLUMNS-POSTER-TWO-ROW"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"최소한의 삼국지","url":"https://msearch.shopping.naver.com/book/catalog/57802041140","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5780204%2F57802041140.20251118093122.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"최태성","service":"프런트페이지"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52aec"},{"@type":"MATERIAL-PC-FEED","title":"위버멘쉬","url":"https://msearch.shopping.naver.com/book/catalog/53211770996","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5321177%2F53211770996.20250226094407.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"프리드리히 니체","service":"떠오름(RISE)"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52aed"},{"@type":"MATERIAL-PC-FEED","title":"박곰희 연금 부자 수업","url":"https://msearch.shopping.naver.com/book/catalog/55482086306","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5548208%2F55482086306.20250626091147.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"박곰희","service":"인플루엔셜"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52aee"},{"@type":"MATERIAL-PC-FEED","title":"어른의 행복은 조용하다","url":"https://msearch.shopping.naver.com/book/catalog/51018313618","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5101831%2F51018313618.20241025071109.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"태수","service":"페이지2북스"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52aef"},{"@type":"MATERIAL-PC-FEED","title":"이재명 대통령과 함께 365 일력","url":"https://msearch.shopping.naver.com/book/catalog/57824369931","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5782436%2F57824369931.20251120083155.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"김준혁","service":"생각의힘"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af0"},{"@type":"MATERIAL-PC-FEED","title":"대형주 추세추종 투자법칙","url":"https://msearch.shopping.naver.com/book/catalog/57323535686","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5732353%2F57323535686.20251023094143.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"이종호(전황)","service":"사피엔테스"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af1"},{"@type":"MATERIAL-PC-FEED","title":"처음 만나는 양자의 세계","url":"https://msearch.shopping.naver.com/book/catalog/56715477763","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5671547%2F56715477763.20250914080711.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"채은미","service":"북플레저"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af2"},{"@type":"MATERIAL-PC-FEED","title":"어른의 품위","url":"https://msearch.shopping.naver.com/book/catalog/56798851720","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5679885%2F56798851720.20250920092359.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"최서영","service":"북로망스"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af3"},{"@type":"MATERIAL-PC-FEED","title":"모순","url":"https://msearch.shopping.naver.com/book/catalog/32486402650","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_3248640%2F32486402650.20241002094141.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"양귀자","service":"쓰다"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af4"},{"@type":"MATERIAL-PC-FEED","title":"2026 임용 면접레시피 평가원 지역 - 전2권","url":"https://msearch.shopping.naver.com/book/catalog/57537815322","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5753781%2F57537815322.20251119072130.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"류은진, 양왕경, 이광한, 이지혜","service":"위더스"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af5"},{"@type":"MATERIAL-PC-FEED","title":"머니 트렌드 2026","url":"https://msearch.shopping.naver.com/book/catalog/56503977076","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5650397%2F56503977076.20250830091342.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"김도윤, 정태익, 김광석, 김승주, 김용섭, 김학렬(빠숑), 김현준, 최재붕","service":"북모먼트"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af6"},{"@type":"MATERIAL-PC-FEED","title":"해커스 토익 기출 VOCA(보카)","url":"https://msearch.shopping.naver.com/book/catalog/32436333110","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_3243633%2F32436333110.20230614072541.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"David Cho","service":"해커스어학연구소"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af7"},{"@type":"MATERIAL-PC-FEED","title":"탁! 깨달음의 대화","url":"https://msearch.shopping.naver.com/book/catalog/57824369970","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5782436%2F57824369970.20251121083010.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"법륜","service":"정토출판"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af8"},{"@type":"MATERIAL-PC-FEED","title":"트렌드 코리아 2026","url":"https://msearch.shopping.naver.com/book/catalog/56589756898","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5658975%2F56589756898.20250905095929.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"김난도, 전미영, 최지혜, 권정윤, 한다혜, 이혜원, 이수진, 서유현, 이준영, 이향은, 김나은, 전다현","service":"미래의창"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52af9"},{"@type":"MATERIAL-PC-FEED","title":"손자병법","url":"https://msearch.shopping.naver.com/book/catalog/56926813298","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5692681%2F56926813298.20250927071315.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"손무(손자)","service":"현대지성"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52afa"},{"@type":"MATERIAL-PC-FEED","title":"열두 번의 음성과 열세 번의 환상","url":"https://msearch.shopping.naver.com/book/catalog/57824370015","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5782437%2F57824370015.20251119125905.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"손현보","service":"킹덤북스"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52afb"},{"@type":"MATERIAL-PC-FEED","title":"헤맨 만큼 내 땅이다","url":"https://msearch.shopping.naver.com/book/catalog/57823506488","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5782350%2F57823506488.20251120083418.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"김상현","service":"필름(Feelm)"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52afc"},{"@type":"MATERIAL-PC-FEED","title":"단 한 줄만 내 마음에 새긴다고 해도","url":"https://msearch.shopping.naver.com/book/catalog/55077483010","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5507748%2F55077483010.20250603080706.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"나민애","service":"포레스트북스"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52afd"},{"@type":"MATERIAL-PC-FEED","title":"절창","url":"https://msearch.shopping.naver.com/book/catalog/56641617233","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5664161%2F56641617233.20250909080129.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"구병모","service":"문학동네"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52afe"},{"@type":"MATERIAL-PC-FEED","title":"다크 심리학","url":"https://msearch.shopping.naver.com/book/catalog/55897358373","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fshopping.phinf%2Fmain_5589735%2F55897358373.20250723101012.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"다크 사이드 프로젝트","service":"어센딩"},"showLiveBadge":false,"_id":"653a42c958a9ce6eb3e52aff"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"title":"베스트셀러 TOP20","moreText":"(인터넷 교보문고 제공)","needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-CULTURE-BEST-SELLER-TOP-20","@template":"SIX-COLUMNS-POSTER-BOOK"},{"@type":"PC-FEED-BLOCK","materials":[],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-CULTURE-INFLUENCER-REVIEW","@template":"FOUR-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"과학동아","url":"https://m.smartstore.naver.com/inflow/outlink/url?url=https%3A%2F%2Fm.smartstore.naver.com%2Fdongascience%2Fproducts%2F6696237360&tr=bookct","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20251029_1095%2Fupload_1761724845649gPtzp.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"동아사이언스"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c53e"},{"@type":"MATERIAL-PC-FEED","title":"매경이코노미","url":"https://m.smartstore.naver.com/inflow/outlink/url?url=https%3A%2F%2Fm.smartstore.naver.com%2Fmkbook%2Fproducts%2F5735014017&tr=bookct","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20251029_1095%2Fupload_1761724844776idpvv.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"매일경제신문사"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c53f"},{"@type":"MATERIAL-PC-FEED","title":"뉴필로소퍼","url":"https://m.smartstore.naver.com/inflow/outlink/url?url=https%3A%2F%2Fm.smartstore.naver.com%2Fbadabooks%2Fproducts%2F2437953202&tr=bookct","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20250930_1095%2Fupload_175921177457971JwL.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"바다출판사"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c540"},{"@type":"MATERIAL-PC-FEED","title":"씨네21","url":"https://m.smartstore.naver.com/inflow/outlink/url?url=https%3A%2F%2Fm.smartstore.naver.com%2Fcine21%2Fproducts%2F12552060095&tr=bookct","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fstatic%2Fwww%2Fmobile%2Fedit%2F20251029_1095%2Fupload_1761724844242h9QTk.jpg%22&type=nf216_312&service=navermain"},"source":{"name":"씨네21"},"showLiveBadge":false,"_id":"6441ca92c499cc07f334c541"},{"@type":"MATERIAL-PC-FEED","title":"내셔널지오그래픽","url":"https://m.sma

In [115]:
soup = BeautifulSoup(html, "html.parser")
titles = soup.select("h2.title")

In [152]:
url = "http://books.toscrape.com/"
res = requests.get(url)
html = res.text

In [153]:
soup = BeautifulSoup(html, 'html.parser')

In [139]:
books_list = []

for book in soup.select("article.product_pod"):
    title = book.h3.a["title"]  # 책 제목
    price = book.select_one("p.price_color").text  # 가격
    rating = book.p["class"][1]  # 평점 (One, Two, Three, Four, Five)
    books_list.append([title, price, rating])

In [140]:
df_books = pd.DataFrame(books_list, columns=["제목", "가격", "평점"])
df_books

                                                   제목       가격     평점
0                                A Light in the Attic  Â£51.77  Three
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
3                                       Sharp Objects  Â£47.82   Four
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
5                                     The Requiem Red  Â£22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
9                                     The Black Maria  Â£52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99    Two
11                              Shakespeare's Sonnets  Â£20.66   Four
12                                        Set Me Free  Â£17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
14                          Rip it Up and Start Again  Â£35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  Three
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One
18                       Libertarianism for Beginners  Â£51.33    Two
19                            It's Only the Himalayas  Â£45.17    Two

In [2]:
url = 'https://www.aladin.co.kr/shop/common/wbest.aspx?BranchType=1&start=we'
res = requests.get(url)
html = res.text

In [3]:
soup = BeautifulSoup(html, 'html.parser')

In [12]:
books_list = []

for i in soup.select('div.ss_book_box'):
    #랭킹
    rate = i.select_one("div[style='text-align: center;']")
    rating = rate.text.strip().replace('.', '') if rate else None
    #제목
    title_tag = i.select_one('a.bo3')
    title = title_tag.text.strip() if rate else None
    # 가격
    price_tag = i.select_one("span.ss_p2 em")
    price = price_tag.text.strip() if price_tag else None
    
      # 평점 (없으면 None)
    rating = None

    books_list.append([rating, title, price])

In [13]:
df = pd.DataFrame(books_list)
df

       0                                              1        2
0   None                                       나나 올리브에게  13,500원
1   None                                  괴테는 모든 것을 말했다  15,300원
2   None                     2026 임용 면접레시피 평가원 지역 - 전2권  34,200원
3   None                              지금 나를 위해 해야 하는 것들  17,820원
4   None                                   트렌드 코리아 2026  18,000원
5   None                                   사카모토 홀리데이즈 2   5,850원
6   None                                        지각의 현상학  37,800원
7   None                                  극락가 5 (더블특전판)   5,850원
8   None                                            혼모노  16,200원
9   None                                        에그박사 17  15,120원
10  None                                             절창  16,200원
11  None                                     탁! 깨달음의 대화  15,300원
12  None                                   박곰희 연금 부자 수업  18,900원
13  None                                    어스탐 경의 임사전언  18,000원
14  None                                           위버멘쉬  16,020원
15  None                                    2026 사이다 면접  42,300원
16  None                                       체인소 맨 21   5,400원
17  None                                카구라바치 8 (더블특전판)   5,850원
18  None                                       최소한의 삼국지  17,550원
19  None                                             모순  11,700원
20  None                                  대형주 추세추종 투자법칙  19,800원
21  None                                 이상한 문장 그만 쓰는 법  16,020원
22  None                       기분이 태도가 되지 않게 (헬로키티 에디션)  16,200원
23  None                                  아무도 오지 않는 곳에서  15,300원
24  None                             이재명 대통령과 함께 365 일력  20,520원
25  None                                      프로젝트 헤일메리  19,800원
26  None                                           손자병법  11,700원
27  None                                부자 아빠 투자 불변의 법칙  18,000원
28  None                  모모세 아키라의 첫사랑 파탄 중 2 (트리플 특전판)   6,750원
29  None                                겨울어 사전 (PVC 커버)  16,200원
30  None                                북유럽 모티브 손뜨개 완전판  17,820원
31  None     ETS 토익 정기시험 기출문제집 1000 Vol. 4 Reading (리딩)  17,820원
32  None                                    길을 찾는 책 도덕경  16,020원
33  None                                        호의에 대하여  16,920원
34  None                      얼굴만으론 좋아할 수 없어요 15 (더블특전)   5,400원
35  None                                          렛뎀 이론  18,000원
36  None                                           사탄탱고  17,820원
37  None                                    도쿄 에일리언즈 11   5,400원
38  None                                     10년 째 합숙 중  16,200원
39  None                                   ETF 투자의 모든 것  18,900원
40  None  ETS 토익 정기시험 기출문제집 1000 Vol. 4 Listening (리스닝)  17,820원
41  None                                        흔한남매 20  15,120원
42  None                                설민석의 한국사 대모험 35  14,400원
43  None                                     실패를 통과하는 일  18,000원
44  None                                       안녕이라 그랬어  15,120원
45  None                                         자몽살구클럽  10,800원
46  None                                         소년이 온다  13,500원
47  None                           단 한 줄만 내 마음에 새긴다고 해도  21,420원
48  None                            해커스 토익 기출 VOCA (보카)  11,610원
49  None                                            스토너  15,120원

In [ ]:
for book in soup.select("article.product_pod"):
    title = book.h3.a["title"]  # 책 제목
    price = book.select_one("p.price_color").text  # 가격
    rating = book.p["class"][1]  # 평점 (One, Two, Three, Four, Five)
    books_list.append([title, price, rating])