# MariaDB 설치 및 데이터적재 (실습)

## Step.1 관련 툴 설치

- [MariaDB 설치방법](https://cha-coding.tistory.com/entry/MariaDB-%EC%9C%88%EB%8F%84%EC%9A%B010-MariaDB-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)

    **(주의) id/password 는 root/root1234 로 통일**  
    -- Enable access from remote machines for 'root' user : 외부 원격 시스템에서 'root' 계정에 대해 접근을 허용한다.   
    -- User UTF8 as default server's charactor set (필수) : 서버의 문자셋을 UTF8로 설정한다.    
    -- MySQL과 MariaDB는 기본적으로 3306 포트를 이용한다.


- [MariaDB 다운로드](https://mariadb.org/download/?t=mariadb&p=mariadb&r=11.3.2&os=windows&cpu=x86_64&pkg=msi&mirror=blendbyte)


- [HeidiSQL다운로드](https://www.heidisql.com/download.php)

    **(신규 데이터베이스 생성**   
    -- <새로생성> - <데이터베이스> - 이름은 'dbmaria'    
          
    **(신규 사용자 등록)**    
    -- 1. 프로그램 상단의 [도구] - [사용자 관리자] 메뉴 클릭   
    -- 2. [추가] 버튼 클릭    
    -- 3. 사용자 이름(user), 암호(user1234), 호스트(모든곳에서접근), 데이터베이스(dbmaria) 설정을 해준다.

## Step.2 데이터 파일 다운로드

- (공공데이터분석) 국토부 아파트매매 실거래가 API[data.go.kr] 연동

-  XML 국토교통부_아파트매매 실거래자료 : https://www.data.go.kr/data/15058747/openapi.do

-  행정표준관리시스템 : https://www.code.go.kr/index.do ( [메뉴] 자주이용하는 코드 > 법정동 > [법정동코드전체자료] )

- **(필수) 특정월에 서울시 전체 구의 데이터를 한번에 가져오기(입력값: 연월 202402)**
- (선택) 특정 서울시 하나의 구의 과거 1년치 데이터를 한번에 가져오기(입력값: 특정구 하나) 
- 또는 첨부된 data 폴더 파일 사용

## Step.3 데이터 파일 통합 읽기

- 폴더내 CSV 파일 전체 읽기
- 하나의 데이터프레임으로 통합
- (문제점) 파일명의 정보(예시: 구이름)가 모두 포함되지 않음 ... 포함하는 방안은?

In [5]:
import os
import pandas as pd
directory = 'C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data'

In [6]:
os.listdir(directory)

['result_강남구_202511.csv',
 'result_강동구_202511.csv',
 'result_강북구_202511.csv',
 'result_강서구_202511.csv',
 'result_관악구_202511.csv',
 'result_광진구_202511.csv',
 'result_구로구_202511.csv',
 'result_금천구_202511.csv',
 'result_노원구_202511.csv',
 'result_도봉구_202511.csv',
 'result_동대문구_202511.csv',
 'result_동작구_202511.csv',
 'result_마포구_202511.csv',
 'result_서대문구_202511.csv',
 'result_서초구_202511.csv',
 'result_성동구_202511.csv',
 'result_성북구_202511.csv',
 'result_송파구_202511.csv',
 'result_양천구_202511.csv',
 'result_영등포구_202511.csv',
 'result_용산구_202511.csv',
 'result_은평구_202511.csv',
 'result_종로구_202511.csv',
 'result_중구_202511.csv',
 'result_중랑구_202511.csv']

In [7]:
filename = os.listdir(directory)[0]

In [8]:
filename

'result_강남구_202511.csv'

In [9]:
directory+filename

'C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/dataresult_강남구_202511.csv'

In [10]:
df = pd.read_csv(os.path.join(directory, filename), encoding='cp949')

In [11]:
filename.split("_")#[2].split(".")[0]

['result', '강남구', '202511.csv']

In [12]:
df = df.drop_duplicates()
df['GU'] = filename.split("_")[1]
df['YM'] = filename.split("_")[2].split(".")[0]

In [13]:
df.index+1

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [15]:
import os
import pandas as pd

# CSV 파일이 들어있는 디렉토리 경로
directory = 'C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data'

# 빈 리스트 생성
dfs = []

# 디렉토리 내 모든 CSV 파일 가져오기
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        filepath = os.path.join(directory, filename)
        print(f"Reading file: {filename}")
        
        # CSV 파일을 데이터프레임으로 읽기
        df = pd.read_csv(filepath, encoding='cp949')
        df = df.drop_duplicates()
        df['GU'] = filename.split("_")[1]
        df['YM'] = filename.split("_")[2].split(".")[0]
        df['TID'] = df.index + 1
        
        # 데이터프레임을 리스트에 추가
        dfs.append(df)

Reading file: result_강남구_202511.csv
Reading file: result_강동구_202511.csv
Reading file: result_강북구_202511.csv
Reading file: result_강서구_202511.csv
Reading file: result_관악구_202511.csv
Reading file: result_광진구_202511.csv
Reading file: result_구로구_202511.csv
Reading file: result_금천구_202511.csv
Reading file: result_노원구_202511.csv
Reading file: result_도봉구_202511.csv
Reading file: result_동대문구_202511.csv
Reading file: result_동작구_202511.csv
Reading file: result_마포구_202511.csv
Reading file: result_서대문구_202511.csv
Reading file: result_서초구_202511.csv
Reading file: result_성동구_202511.csv
Reading file: result_성북구_202511.csv
Reading file: result_송파구_202511.csv
Reading file: result_양천구_202511.csv
Reading file: result_영등포구_202511.csv
Reading file: result_용산구_202511.csv
Reading file: result_은평구_202511.csv
Reading file: result_종로구_202511.csv
Reading file: result_중구_202511.csv
Reading file: result_중랑구_202511.csv

In [16]:
df#.head(1)

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,...,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm,GU,YM,TID
0,NaN,신내,1996,개인,NaN,NaN,"57,700",22,11,2025,...,5,13,N,NaN,11260,개인,묵동,중랑구,202511,1
1,NaN,성원상떼빌,1997,개인,NaN,NaN,"69,000",30,11,2025,...,11,1515,N,NaN,11260,개인,면목동,중랑구,202511,2
2,NaN,화성.두산아파트,1995,개인,NaN,NaN,"61,800",15,11,2025,...,5,656,N,NaN,11260,개인,신내동,중랑구,202511,3
3,NaN,중앙하이츠,1996,개인,NaN,NaN,"59,000",26,11,2025,...,4,479,N,NaN,11260,개인,신내동,중랑구,202511,4
4,NaN,신내11대명,1996,개인,NaN,NaN,"54,500",30,11,2025,...,11,661,N,NaN,11260,개인,신내동,중랑구,202511,5
5,NaN,면목한신,1987,개인,NaN,NaN,"45,000",23,11,2025,...,12,193-1,N,NaN,11260,개인,면목동,중랑구,202511,6
6,NaN,성도아트빌,2008,개인,NaN,NaN,"44,700",29,11,2025,...,6,202-16,N,NaN,11260,개인,망우동,중랑구,202511,7
7,NaN,늘푸른동아,2002,개인,NaN,NaN,"88,000",29,11,2025,...,18,715,N,NaN,11260,개인,면목동,중랑구,202511,8
8,NaN,신내우디안1단지,2014,개인,NaN,NaN,"77,000",29,11,2025,...,19,816,N,NaN,11260,개인,신내동,중랑구,202511,9
9,NaN,신내9진흥,1996,개인,NaN,NaN,"31,500",27,11,2025,...,9,657,N,NaN,11260,개인,신내동,중랑구,202511,10

In [17]:
dfs

[   aptDong        aptNm  buildYear buyerGbn  cdealDay  cdealType dealAmount  \
 0      NaN   성원대치2단지아파트       1992       개인       NaN        NaN    155,000
 1      NaN         대치르엘       2021       개인       NaN        NaN    395,000
 2      NaN         도곡렉슬       2006       개인       NaN        NaN    299,500
 3      NaN        포스코더샵       2004       개인       NaN        NaN    370,000
 4      NaN      알파임하우스1       2002       개인       NaN        NaN    485,000
 5      NaN      개포주공7단지       1983       개인       NaN        NaN    391,000
 6      NaN         청담자이       2011       개인       NaN        NaN    385,000
 7      NaN  LG선릉에클라트(B)       2004       개인       NaN        NaN     72,000
 8      NaN         도곡렉슬       2006       개인       NaN        NaN    441,000
 9      NaN          현대2       1986       개인       NaN        NaN    320,000

    dealDay  dealMonth  dealYear  ... floor   jibun  landLeaseholdGbn  \
 0        4         11      2025  ...     8      12                 N
 1       16         11      2025  ...     8    1030                 N
 2       14         11      2025  ...    12     527                 N
 3       28         11      2025  ...    15     902                 N
 4       28         11      2025  ...     3   649-5                 N
 5       27         11      2025  ...     2     185                 N
 6       18         11      2025  ...     2  134-38                 N
 7       22         11      2025  ...     9   142-3                 N
 8       19         11      2025  ...    18     527                 N
 9        5         11      2025  ...     9     654                 N

    rgstDate  sggCd slerGbn  umdNm   GU      YM TID
 0       NaN  11680      개인    개포동  강남구  202511   1
 1       NaN  11680      개인    대치동  강남구  202511   2
 2       NaN  11680      개인    도곡동  강남구  202511   3
 3       NaN  11680      개인    대치동  강남구  202511   4
 4       NaN  11680      개인    신사동  강남구  202511   5
 5       NaN  11680      개인    개포동  강남구  202511   6
 6       NaN  11680      개인    청담동  강남구  202511   7
 7       NaN  11680      개인    삼성동  강남구  202511   8
 8       NaN  11680      개인    도곡동  강남구  202511   9
 9       NaN  11680      개인    개포동  강남구  202511  10

 [10 rows x 23 columns],
    aptDong       aptNm  buildYear buyerGbn  cdealDay  cdealType dealAmount  \
 0      NaN  고덕롯데캐슬베네루체       2019       개인       NaN        NaN    174,000
 1      NaN  고덕센트럴IPARK       2019       개인       NaN        NaN    170,000
 2      NaN       고덕주공9       1985       개인       NaN        NaN    158,500
 3      NaN    동아하이빌아파트       2000       개인       NaN        NaN     87,500
 4      NaN  강동역신동아파밀리에       2015       개인       NaN        NaN    143,000
 5      NaN       유덕휴먼빌       2003       개인       NaN        NaN     58,500
 6      NaN        라움포레       2020       개인       NaN        NaN     80,000
 7      NaN      둔촌푸르지오       2010       개인       NaN        NaN    140,000
 8      NaN      삼익그린2차       1983       개인       NaN        NaN    170,000
 9      NaN        강동큐브       2013       개인       NaN        NaN      9,000

    dealDay  dealMonth  dealYear  ... floor    jibun  landLeaseholdGbn  \
 0       29         11      2025  ...    11      514                 N
 1       29         11      2025  ...    24      513                 N
 2       29         11      2025  ...     1      257                 N
 3       24         11      2025  ...     4  217-132                 N
 4       18         11      2025  ...    26   447-17                 N
 5       24         11      2025  ...     1   353-40                 N
 6       21         11      2025  ...     3      607                 N
 7       21         11      2025  ...    15      630                 N
 8       21         11      2025  ...     4       15                 N
 9       21         11      2025  ...    11    456-3                 N

    rgstDate  sggCd slerGbn  umdNm   GU      YM TID
 0       NaN  11740      개인    상일동  강동구  202511   1
 1       NaN  11740      개인    상일동  강동구  202511   2
 2       NaN  11740      개인    명일동  강동구  202511   3
 3       NaN  11740      개인    천호동  강동구  202511   4
 4       NaN  11740      개인    천호동  강동구  202511   5
 5       NaN  11740      개인     길동  강동구  202511   6
 6       NaN  11740      개인    성내동  강동구  202511   7
 7       NaN  11740      개인    둔촌동  강동구  202511   8
 8       NaN  11740      개인    명일동  강동구  202511   9
 9       NaN  11740      개인     길동  강동구  202511  10

 [10 rows x 23 columns],
    aptDong         aptNm  buildYear buyerGbn  cdealDay  cdealType dealAmount  \
 0      NaN       벽산라이브파크       2004       개인       NaN        NaN     55,800
 1      NaN     에스케이북한산시티       2004       개인       NaN        NaN     67,200
 2      NaN     에스케이북한산시티       2004       개인       NaN        NaN     70,950
 3      NaN  삼성래미안트리베라2단지       2010       개인       NaN        NaN     79,300
 4      NaN      두산위브트레지움       2011       개인       NaN        NaN     83,500
 5      NaN       벽산라이브파크       2004       개인       NaN        NaN     55,700
 6      NaN     에스케이북한산시티       2004       개인       NaN        NaN     64,000
 7      NaN        북한산굿모닝       2003       개인       NaN        NaN     38,500
 8      NaN  삼성래미안트리베라2단지       2010       개인       NaN        NaN    108,000
 9      NaN  삼성래미안트리베라2단지       2010       개인       NaN        NaN     82,500

    dealDay  dealMonth  dealYear  ... floor jibun  landLeaseholdGbn  rgstDate  \
 0       22         11      2025  ...    23  1354                 N       NaN
 1       26         11      2025  ...     5  1353                 N       NaN
 2       29         11      2025  ...    17  1353                 N       NaN
 3       29         11      2025  ...    15   812                 N       NaN
 4       24         11      2025  ...     2   811                 N       NaN
 5       27         11      2025  ...    12  1354                 N       NaN
 6       27         11      2025  ...     5  1353                 N       NaN
 7       26         11      2025  ...     2   175                 N       NaN
 8       26         11      2025  ...    14   812                 N       NaN
 9       26         11      2025  ...     6   812                 N       NaN

    sggCd slerGbn  umdNm   GU      YM TID
 0  11305      개인    미아동  강북구  202511   1
 1  11305      개인    미아동  강북구  202511   2
 2  11305      개인    미아동  강북구  202511   3
 3  11305      개인    미아동  강북구  202511   4
 4  11305      개인    미아동  강북구  202511   5
 5  11305      개인    미아동  강북구  202511   6
 6  11305      개인    미아동  강북구  202511   7
 7  11305      개인    우이동  강북구  202511   8
 8  11305      개인    미아동  강북구  202511   9
 9  11305      개인    미아동  강북구  202511  10

 [10 rows x 23 columns],
    aptDong          aptNm  buildYear buyerGbn  cdealDay  cdealType dealAmount  \
 0      NaN  삼성다빈치(917-14)       2015       개인       NaN        NaN     10,400
 2      NaN        마곡루나플라체       2021       개인       NaN        NaN     26,700
 3      NaN             대림       1995       개인       NaN        NaN    132,000
 4      NaN             진흥       1992       개인       NaN        NaN     26,500
 5      NaN          방화4단지       1994       개인       NaN        NaN     89,500
 6      NaN        등촌동아이파크       2004       개인       NaN        NaN     85,100
 7      NaN       주상복합태진가람       1995       개인       NaN        NaN     57,750
 8      NaN           방화그린       1993       기타       NaN        NaN     40,000
 9      NaN             동성       1995       개인       NaN        NaN    117,000

    dealDay  dealMonth  dealYear  ... floor   jibun  landLeaseholdGbn  \
 0       28         11      2025  ...    11  917-14                 N
 2       28         11      2025  ...     2     725                 N
 3       17         11      2025  ...    12     694                 N
 4       21         11      2025  ...     5  824-13                 N
 5       12         11      2025  ...    14     831                 N
 6       18         11      2025  ...     9     715                 N
 7       23         11      2025  ...     8   263-2                 N
 8       22         11      2025  ...     1     839                 N
 9       21         11      2025  ...    12   691-1                 N

    rgstDate  sggCd slerGbn  umdNm   GU      YM TID
 0       NaN  11500      개인    화곡동  강서구  202511   1
 2       NaN  11500      개인    등촌동  강서구  202511   3
 3       NaN  11500      개인    등촌동  강서구  202511   4
 4       NaN  11500      개인    화곡동  강서구  202511   5
 5       NaN  11500      개인    방화동  강서구  202511   6
 6       NaN  11500      개인    등촌동  강서구  202511   7
 7       NaN  11500      개인    염창동  강서구  202511   8
 8       NaN  11500      개인    방화동  강서구  202511   9
 9       NaN  11500      개인    등촌동  강서구  202511  10

 [9 rows x 23 columns],
    aptDong       aptNm  buildYear buyerGbn  cdealDay  cdealType dealAmount  \
 0      NaN          청화       2004       개인       NaN        NaN     68,000
 1      NaN    힐스테이트뉴포레       2022       개인       NaN        NaN    128,500
 2      NaN       관악캐스빌       2002       개인       NaN        NaN     52,300
 3      NaN      관악푸르지오       2004       개인       NaN        NaN     97,000
 4      NaN  관악산휴먼시아2단지       2008       개인       NaN        NaN     69,500
 5      NaN  관악산휴먼시아2단지       2008       개인       NaN        NaN     71,500
 6      NaN      신림푸르지오       2005       개인       NaN        NaN     92,000
 7      NaN      관악푸르지오       2004       개인       NaN        NaN     97,300
 8      NaN       벽산블루밍       2005       개인       NaN        NaN     96,000
 9      NaN  관악산휴먼시아2단지       2008       개인       NaN        NaN     76,500

    dealDay  dealMonth  dealYear  ... floor     jibun  landLeaseholdGbn  \
 0       30         11      2025  ...     9      1729                 N
 1       29         11      2025  ...    31      1746                 N
 2       25         11      2025  ...     6  1690-162                 N
 3       22         11      2025  ...    18      1717                 N
 4       29         11      2025  ...    12      1735                 N
 5       24         11      2025  ...    16      1735                 N
 6       29         11      2025  ...    19      1730                 N
 7       29         11      2025  ...    12      1717                 N
 8       29         11      2025  ...     5      1718                 N
 9       29         11      2025  ...     5      1735                 N

    rgstDate  sggCd slerGbn  umdNm   GU      YM TID
 0       NaN  11620      개인    신림동  관악구  202511   1
 1       NaN  11620      개인    신림동  관악구  202511   2
 2       NaN  11620      개인    봉천동  관악구  202511   3
 3       NaN  11620      개인    봉천동  관악구  202511   4
 4       NaN  11620      개인    신림동  관악구  202511   5
 5       NaN  11620      개인    신림동  관악구  202511   6
 6       NaN  11620      개인    신림동  관악구  202511   7
 7       NaN  11620      개인    봉천동  관악구  202511   8
 8       NaN  11620      개인    봉천동  관악구  202511   9
 9       NaN  11620      개인    신림동  관악구  202511  10

 [10 rows x 23 columns],
    aptDong           aptNm  buildYear buyerGbn  cdealDay  cdealType  \
 0      NaN             퓨전빌       2003       개인       NaN        NaN
 1      NaN         구의현대2단지       1996       개인       NaN        NaN
 2      NaN         광진파크하우스       2023       개인       NaN        NaN
 3      NaN          구의자이르네       2021       개인       NaN        NaN
 4      NaN  화양동동도센트리움캠퍼스파크       2019       개인       NaN        NaN
 5      NaN         워커힐푸르지오       1987       개인       NaN        NaN
 6      NaN             현대5       1989       개인       NaN        NaN
 7      NaN          자양호반써밋       2021       개인       NaN        NaN
 8      NaN          구의자이르네       2021       개인       NaN        NaN
 9    110.0        래미안파크스위트       2018       개인       NaN        NaN

   dealAmount  dealDay  dealMonth  dealYear  ... floor  jibun  \
 0     73,000       28         11      2025  ...     1  244-6
 1    214,000       18         11      2025  ...    12    611
 2     60,000       24         11      2025  ...     7    682
 3     93,000        8         11      2025  ...     8    671
 4     22,300       11         11      2025  ...    15  116-2
 5    125,000       11         11      2025  ...    11  148-4
 6    220,000       14         11      2025  ...    16  554-7
 7    162,000       13         11      2025  ...    11    861
 8     95,000        8         11      2025  ...     9    671
 9    119,000        3         11      2025  ...    11    668

    landLeaseholdGbn  rgstDate  sggCd slerGbn umdNm   GU      YM TID
 0                 N       NaN  11215      개인   구의동  광진구  202511   1
 1                 N       NaN  11215      개인   구의동  광진구  202511   2
 2                 N       NaN  11215      개인   구의동  광진구  202511   3
 3                 N       NaN  11215      개인   구의동  광진구  202511   4
 4                 N       NaN  11215      개인   화양동  광진구  202511   5
 5                 N       NaN  11215      개인   광장동  광진구  202511   6
 6                 N       NaN  11215      개인   광장동  광진구  202511   7
 7                 N       NaN  11215      개인   자양동  광진구  202511   8
 8                 N       NaN  11215      개인   구의동  광진구  202511   9
 9                 N  25.11.13  11215      개인   구의동  광진구  202511  10

 [10 rows x 23 columns],
    aptDong      aptNm  buildYear buyerGbn  cdealDay  cdealType dealAmount  \
 0      NaN         벽산       2003       개인       NaN        NaN     91,000
 1      NaN  케어빌(98-8)       2007       개인       NaN        NaN     48,500
 2      NaN        한마을       1999       개인       NaN        NaN     75,500
 3      NaN    오류동푸르지오       2004       개인       NaN        NaN     63,800
 4      NaN       동부골든       1998       개인       NaN        NaN     58,500
 5      NaN         한진       2000       개인       NaN        NaN     73,000
 6      NaN      현대연예인       1989       개인       NaN        NaN     51,700
 7      NaN       구로두산       1998       개인       NaN        NaN     48,700
 8      NaN    신도림LG자이       2004       개인       NaN        NaN    106,000
 9      NaN     거성푸르뫼2       1994       개인       NaN        NaN     60,500

    dealDay  dealMonth  dealYear  ... floor   jibun  landLeaseholdGbn  \
 0       27         11      2025  ...     6     334                 N
 1       21         11      2025  ...     6    98-8                 N
 2       29         11      2025  ...    25     476                 N
 3       29         11      2025  ...    12     346                 N
 4       26         11      2025  ...    20     338                 N
 5       26         11      2025  ...     8     478                 N
 6       26         11      2025  ...     7  685-70                 N
 7       23         11      2025  ...    23    1265                 N
 8       22         11      2025  ...    18      42                 N
 9       22         11      2025  ...    16   60-82                 N

    rgstDate  sggCd slerGbn  umdNm   GU      YM TID
 0       NaN  11530      개인    고척동  구로구  202511   1
 1       NaN  11530      개인    구로동  구로구  202511   2
 2       NaN  11530      개인    개봉동  구로구  202511   3
 3       NaN  11530      개인    오류동  구로구  202511   4
 4       NaN  11530      개인    오류동  구로구  202511   5
 5       NaN  11530      개인    개봉동  구로구  202511   6
 6       NaN  11530      개인    구로동  구로구  202511   7
 7       NaN  11530      개인    구로동  구로구  202511   8
 8       NaN  11530      개인    구로동  구로구  202511   9
 9       NaN  11530      개인    개봉동  구로구  202511  10

 [10 rows x 23 columns],
    aptDong                 aptNm  buildYear buyerGbn  cdealDay  cdealType  \
 0      NaN                  독산현대       1999       개인       NaN        NaN
 1      NaN          금천롯데캐슬골드파크1차       2016       개인       NaN        NaN
 2      NaN  금천롯데캐슬골드파크2차201동202동       2017       개인       NaN        NaN
 3      NaN                남서울건영2       1989       개인       NaN        NaN
 4      NaN  금천롯데캐슬골드파크2차201동202동       2017       개인       NaN        NaN
 5      NaN                 신도브래뉴       2002       개인       NaN        NaN
 6      NaN                    두산       1998       개인       NaN        NaN
 7      NaN          금천롯데캐슬골드파크3차       2018       개인       NaN        NaN
 8      NaN          금천롯데캐슬골드파크1차       2016       개인       NaN        NaN
 9      NaN                    두산       1998       개인       NaN        NaN

   dealAmount  dealDay  dealMonth  dealYear  ... floor   jibun  \
 0     61,000       25         11      2025  ...    15  293-10
 1    115,000       29         11      2025  ...    13    1147
 2     88,000       22         11      2025  ...    14    1150
 3     31,000       26         11      2025  ...     6  384-12
 4    108,000       15         11      2025  ...    20    1150
 5     79,600       20         11      2025  ...     3     955
 6     58,700       20         11      2025  ...     1     769
 7    110,000       24         11      2025  ...     6    1155
 8    111,200       21         11      2025  ...    10    1147
 9     71,000       22         11      2025  ...     6     769

    landLeaseholdGbn  rgstDate  sggCd slerGbn  umdNm   GU      YM TID
 0                 N       NaN  11545      개인    독산동  금천구  202511   1
 1                 N       NaN  11545      개인    독산동  금천구  202511   2
 2                 N       NaN  11545      개인    독산동  금천구  202511   3
 3                 N       NaN  11545      개인    시흥동  금천구  202511   4
 4                 N       NaN  11545      개인    독산동  금천구  202511   5
 5                 N       NaN  11545      개인    독산동  금천구  202511   6
 6                 N       NaN  11545      개인    가산동  금천구  202511   7
 7                 N       NaN  11545      개인    독산동  금천구  202511   8
 8                 N       NaN  11545      개인    독산동  금천구  202511   9
 9                 N       NaN  11545      개인    가산동  금천구  202511  10

 [10 rows x 23 columns],
    aptDong       aptNm  buildYear buyerGbn  cdealDay  cdealType dealAmount  \
 0      NaN   상계주공1(고층)       1988       개인       NaN        NaN     57,800
 1      NaN    신동아(366)       1993       개인       NaN        NaN    133,500
 2      NaN   상계주공1(저층)       1988       개인       NaN        NaN     69,500
 3      NaN   상계주공2(고층)       1987       개인       NaN        NaN     58,000
 4      NaN       중계무지개       1991       개인       NaN        NaN     37,000
 5      NaN         미라쉘       2018       개인       NaN        NaN     13,700
 6      NaN       중계무지개       1991       개인       NaN        NaN     56,700
 7      NaN  상계주공14(저층)       1989       개인       NaN        NaN     77,300
 8      NaN   상계주공7(고층)       1988       개인       NaN        NaN     52,500
 9      NaN   상계주공3(고층)       1987       개인       NaN        NaN     53,000

    dealDay  dealMonth  dealYear  ... floor  jibun  landLeaseholdGbn  rgstDate  \
 0       21         11      2025  ...     4    765                 N       NaN
 1       29         11      2025  ...     6    366                 N       NaN
 2       29         11      2025  ...     4    765                 N       NaN
 3       19         11      2025  ...    14    740                 N       NaN
 4       26         11      2025  ...     1    512                 N       NaN
 5       26         11      2025  ...    16  670-6                 N       NaN
 6       27         11      2025  ...    14    512                 N       NaN
 7       24         11      2025  ...     1    626                 N       NaN
 8       21         11      2025  ...     8    691                 N       NaN
 9       21         11      2025  ...     6  730-2                 N       NaN

    sggCd slerGbn  umdNm   GU      YM TID
 0  11350      개인    상계동  노원구  202511   1
 1  11350      개인    중계동  노원구  202511   2
 2  11350      개인    상계동  노원구  202511   3
 3  11350      개인    상계동  노원구  202511   4
 4  11350      개인    중계동  노원구  202511   5
 5  11350      개인    공릉동  노원구  202511   6
 6  11350      개인    중계동  노원구  202511   7
 7  11350      개인    상계동  노원구  202511   8
 8  11350      개인    상계동  노원구  202511   9
 9  11350      개인    상계동  노원구  202511  10

 [10 rows x 23 columns],
    aptDong           aptNm  buildYear buyerGbn  cdealDay  cdealType  \

In [18]:
# 리스트에 있는 모든 데이터프레임을 합치기
result = pd.concat(dfs, ignore_index=True)
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   aptDong           2 non-null      float64
 1   aptNm             246 non-null    object
 2   buildYear         246 non-null    int64
 3   buyerGbn          246 non-null    object
 4   cdealDay          1 non-null      object
 5   cdealType         1 non-null      object
 6   dealAmount        246 non-null    object
 7   dealDay           246 non-null    int64
 8   dealMonth         246 non-null    int64
 9   dealYear          246 non-null    int64
 10  dealingGbn        246 non-null    object
 11  estateAgentSggNm  229 non-null    object
 12  excluUseAr        246 non-null    float64
 13  floor             246 non-null    int64
 14  jibun             246 non-null    object
 15  landLeaseholdGbn  246 non-null    object
 16  rgstDate          2 non-null      object
 17  sggCd             246 non-null    int64
 18  slerGbn           246 non-null    object
 19  umdNm             246 non-null    object
 20  GU                246 non-null    object
 21  YM                246 non-null    object
 22  TID               246 non-null    int64
dtypes: float64(2), int64(7), object(14)
memory usage: 44.3+ KB

In [19]:
result#[result.duplicated(keep=False)]

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,...,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm,GU,YM,TID
0,NaN,성원대치2단지아파트,1992,개인,NaN,NaN,"155,000",4,11,2025,...,8,12,N,NaN,11680,개인,개포동,강남구,202511,1
1,NaN,대치르엘,2021,개인,NaN,NaN,"395,000",16,11,2025,...,8,1030,N,NaN,11680,개인,대치동,강남구,202511,2
2,NaN,도곡렉슬,2006,개인,NaN,NaN,"299,500",14,11,2025,...,12,527,N,NaN,11680,개인,도곡동,강남구,202511,3
3,NaN,포스코더샵,2004,개인,NaN,NaN,"370,000",28,11,2025,...,15,902,N,NaN,11680,개인,대치동,강남구,202511,4
4,NaN,알파임하우스1,2002,개인,NaN,NaN,"485,000",28,11,2025,...,3,649-5,N,NaN,11680,개인,신사동,강남구,202511,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,NaN,면목한신,1987,개인,NaN,NaN,"45,000",23,11,2025,...,12,193-1,N,NaN,11260,개인,면목동,중랑구,202511,6
242,NaN,성도아트빌,2008,개인,NaN,NaN,"44,700",29,11,2025,...,6,202-16,N,NaN,11260,개인,망우동,중랑구,202511,7
243,NaN,늘푸른동아,2002,개인,NaN,NaN,"88,000",29,11,2025,...,18,715,N,NaN,11260,개인,면목동,중랑구,202511,8
244,NaN,신내우디안1단지,2014,개인,NaN,NaN,"77,000",29,11,2025,...,19,816,N,NaN,11260,개인,신내동,중랑구,202511,9
245,NaN,신내9진흥,1996,개인,NaN,NaN,"31,500",27,11,2025,...,9,657,N,NaN,11260,개인,신내동,중랑구,202511,10

In [57]:
# 결과 저장 및 확인
result.to_csv("result_all.csv", index=False, encoding='cp949')

## Step.4 MariaDB에 통합데이터를 to_sql로 적재 (sqlalchemy 사용)

In [59]:
import pymysql

In [60]:
conn = pymysql.connect(host='127.0.0.1',port = 3306, user='root', 
                       password='1234', db='company', charset='utf8')

In [61]:
#C:\Users\salix\anaconda3\lib\site-packages\pandas\io\sql.py:761: 
#UserWarning: pandas only support SQLAlchemy connectable(engine/connection) 
#ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects 
#are not tested, please consider using SQLAlchemy warnings

#result.to_sql(name='gu_land_data', con=conn, if_exists='replace', index=False) #append, replace

In [62]:
result = pd.read_csv("result_all.csv", index_col=None, encoding='cp949')

In [63]:
result.tail()

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,...,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm,GU,YM,TID
241,NaN,면목한신,1987,개인,NaN,NaN,"45,000",23,11,2025,...,12,193-1,N,NaN,11260,개인,면목동,중랑구,202511,6
242,NaN,성도아트빌,2008,개인,NaN,NaN,"44,700",29,11,2025,...,6,202-16,N,NaN,11260,개인,망우동,중랑구,202511,7
243,NaN,늘푸른동아,2002,개인,NaN,NaN,"88,000",29,11,2025,...,18,715,N,NaN,11260,개인,면목동,중랑구,202511,8
244,NaN,신내우디안1단지,2014,개인,NaN,NaN,"77,000",29,11,2025,...,19,816,N,NaN,11260,개인,신내동,중랑구,202511,9
245,NaN,신내9진흥,1996,개인,NaN,NaN,"31,500",27,11,2025,...,9,657,N,NaN,11260,개인,신내동,중랑구,202511,10

In [64]:
#!pip install sqlalchemy

In [65]:
from sqlalchemy import create_engine

db_con_str = 'mysql+pymysql://root:1234@localhost:3306/dbmaria'
db_con_ac = create_engine(db_con_str)

In [66]:
conn_ac = db_con_ac.connect()

result.to_sql(name='result', con=conn_ac, if_exists='replace', index=False) #append, replace

246

## Step5. MariaDB에 통합데이터를 insert로 적재

- pymysql을 사용하여 데이터를 삽입하는 예제 코드

In [67]:
import pandas as pd
import pymysql
import numpy as np

# 데이터 프레임 생성
result = pd.read_csv("result_all.csv", index_col=None, encoding='cp949')
df = result

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   aptDong           2 non-null      float64
 1   aptNm             246 non-null    object
 2   buildYear         246 non-null    int64
 3   buyerGbn          246 non-null    object
 4   cdealDay          1 non-null      object
 5   cdealType         1 non-null      object
 6   dealAmount        246 non-null    object
 7   dealDay           246 non-null    int64
 8   dealMonth         246 non-null    int64
 9   dealYear          246 non-null    int64
 10  dealingGbn        246 non-null    object
 11  estateAgentSggNm  229 non-null    object
 12  excluUseAr        246 non-null    float64
 13  floor             246 non-null    int64
 14  jibun             246 non-null    object
 15  landLeaseholdGbn  246 non-null    object
 16  rgstDate          2 non-null      object
 17  sggCd             246 non-null    int64
 18  slerGbn           246 non-null    object
 19  umdNm             246 non-null    object
 20  GU                246 non-null    object
 21  YM                246 non-null    int64
 22  TID               246 non-null    int64
dtypes: float64(2), int64(8), object(13)
memory usage: 44.3+ KB

In [69]:
 df.astype(str).applymap(len).max()

aptDong              5
aptNm               26
buildYear            4
buyerGbn             2
cdealDay             8
cdealType            3
dealAmount           7
dealDay              2
dealMonth            2
dealYear             4
dealingGbn           4
estateAgentSggNm    19
excluUseAr           8
floor                2
jibun                8
landLeaseholdGbn     1
rgstDate             8
sggCd                5
slerGbn              2
umdNm                6
GU                   4
YM                   6
TID                  2
dtype: int64

In [70]:
df.dtypes

aptDong             float64
aptNm                object
buildYear             int64
buyerGbn             object
cdealDay             object
cdealType            object
dealAmount           object
dealDay               int64
dealMonth             int64
dealYear              int64
dealingGbn           object
estateAgentSggNm     object
excluUseAr          float64
floor                 int64
jibun                object
landLeaseholdGbn     object
rgstDate             object
sggCd                 int64
slerGbn              object
umdNm                object
GU                   object
YM                    int64
TID                   int64
dtype: object

In [71]:
df.tail()

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,...,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm,GU,YM,TID
241,NaN,면목한신,1987,개인,NaN,NaN,"45,000",23,11,2025,...,12,193-1,N,NaN,11260,개인,면목동,중랑구,202511,6
242,NaN,성도아트빌,2008,개인,NaN,NaN,"44,700",29,11,2025,...,6,202-16,N,NaN,11260,개인,망우동,중랑구,202511,7
243,NaN,늘푸른동아,2002,개인,NaN,NaN,"88,000",29,11,2025,...,18,715,N,NaN,11260,개인,면목동,중랑구,202511,8
244,NaN,신내우디안1단지,2014,개인,NaN,NaN,"77,000",29,11,2025,...,19,816,N,NaN,11260,개인,신내동,중랑구,202511,9
245,NaN,신내9진흥,1996,개인,NaN,NaN,"31,500",27,11,2025,...,9,657,N,NaN,11260,개인,신내동,중랑구,202511,10

In [72]:
df.columns

Index(['aptDong', 'aptNm', 'buildYear', 'buyerGbn', 'cdealDay', 'cdealType',
       'dealAmount', 'dealDay', 'dealMonth', 'dealYear', 'dealingGbn',
       'estateAgentSggNm', 'excluUseAr', 'floor', 'jibun', 'landLeaseholdGbn',
       'rgstDate', 'sggCd', 'slerGbn', 'umdNm', 'GU', 'YM', 'TID'],
      dtype='object')

In [73]:
# 데이터프레임의 NaN 값을 NULL로 대체
df = df.fillna("")

In [ ]:
##############################
# ChatGPT 활용 및 테이블 생성
##############################
# 판다스 데이터 프레임을 MariaDB에 저장하기 위한 테이블을 만들려고해. 
# 테이블 이름은 real_estate_seoul 으로 만들고
# 가급적 데이터가 짤리지 않게 DB 데이터타입을 넉넉하게 만들고 컬럼명도 영어로 변환해줘.
# 그리고, YM, GU, TID 컬럼이 기본키가 되게 해주고 형식은 문자열이 되게 해주고,
# 기본키는 테이블 맨앞 컬럼에 배치하고 컬럼명은 그대로 사용해줘.
# 연도 관련된 컬럼 건축년도, 등기일자, 해제사유발생일 컬럼과 지역코드는 문자열로 바꾸어줘
# 다음 데이터프레임 정보를 참고해서 만들려고 해.

# CREATE TABLE real_estate_seoul (
#     YM VARCHAR(10) NOT NULL,
#     GU VARCHAR(100) NOT NULL,
#     TID VARCHAR(50) NOT NULL,
#     transaction_amount VARCHAR(100),
#     transaction_type VARCHAR(100),
#     construction_year VARCHAR(100),
#     year VARCHAR(100),
#     dong VARCHAR(100),
#     registration_date VARCHAR(100),
#     seller VARCHAR(100),
#     buyer VARCHAR(100),
#     legal_dong VARCHAR(100),
#     apartment VARCHAR(100),
#     month INT,
#     day INT,
#     exclusive_area FLOAT,
#     agent_location VARCHAR(100),
#     jibun VARCHAR(100),
#     region_code VARCHAR(100),
#     floor INT,
#     cancellation_reason_date VARCHAR(100),
#     cancellation_status VARCHAR(100),
#     PRIMARY KEY (YM, GU, TID)
# );

In [ ]:
# pymysql을 사용하여 MariaDB에 연결
conn = pymysql.connect(host='127.0.0.1', user='user', password='user1234', db='dbmaria', charset='utf8')
# 커서 생성
cur = conn.cursor()

In [ ]:
# User 테이블 생성
# cur.execute('''CREATE TABLE IF NOT EXISTS user (
#                 nameUser VARCHAR(255),
#                 ageUser INTEGER,
#                 phoneUser VARCHAR(20)
#             )''')

In [ ]:
# # 데이터 프레임의 데이터를 데이터베이스에 삽입
for index, row in df.iterrows():
    cur.execute("""
        INSERT INTO real_estate_seoul (
            YM, GU, TID, 
            transaction_amount, 
            transaction_type, 
            construction_year, 
            year,
            dong, 
            registration_date, 
            seller, buyer, 
            legal_dong, 
            apartment, 
            month, 
            day,
            exclusive_area, 
            agent_location, 
            jibun, 
            region_code, 
            floor,
            cancellation_reason_date, 
            cancellation_status
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        row['YM'],
        row['GU'],
        row['TID'],
        row['거래금액'],
        row['거래유형'],
        row['건축년도'],
        row['년'],
        row['동'],
        row['등기일자'],
        row['매도자'],
        row['매수자'],
        row['법정동'],
        row['아파트'],
        row['월'],
        row['일'],
        row['전용면적'],
        row['중개사소재지'],
        row['지번'],
        row['지역코드'],
        row['층'],
        row['해제사유발생일'],
        row['해제여부']
    ))

In [ ]:
# 변경사항 커밋
conn.commit()

# 연결 종료
conn.close()

- 또다른 INSERT 구문 예시 (수정 필요)

In [ ]:
#############################################
### 최종 버전
# cursor.execute("select * from sbuck_address2")
# rows = cursor.fetchall()

# if rows : # 레코드 있는 경우 : 레코드 조회
#     for row in rows :
#         for i in range(0,len(rows[0])):
#             print(f"{row[i]}", end = ' ')
#         print(f"\n")
#     print('전체 레코드 수 : ', len(rows))
    
# else: # 레코드 없는 경우 : 레코드 추가
#     len_df = len(df) 
#     print(f"{len_df} : 레코드 추가")
#     for i in range(0, len(df)):
#         sql = """INSERT INTO sbuck_address2 \
#         (sido_code, gugun_code, s_code, doro_address, open_dt) \
#         VALUES (%s, %s, %s, %s, %s)"""
#         val = (df.iloc[i,0], df.iloc[i,1], df.iloc[i,2], df.iloc[i,3],
#                df.iloc[i,4])
#         cursor.execute(sql, val)
#         conn.commit()