# 입문자를 위한, 파이썬/R 데이터 분석

]

###  (공공데이터분석) 국토부 아파트매매 실거래가 API[data.go.kr] 연동

- XML 국토교통부_아파트매매 실거래자료 : https://www.data.go.kr/data/15126469/openapi.do
- 행정표준관리시스템 : https://www.code.go.kr/index.do ( [메뉴] 자주이용하는 코드 > 법정동 )
- 개별적 실습을 위해 회원가입 및 API 발급 필요

]

### 1. Import Packages

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

### 2. Data Loading

#### : API Key Setting

In [2]:
#f=open("C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/api_key.txt","r")
#lines=f.readlines()
#my_key=lines[0]
#f.close()

my_key = pd.read_csv("C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/api_key.txt",
                     header=None).iloc[0,0]

In [3]:
my_key

'accc226aba90e01bb632eb0bc06e1fe71b711c4f1144a8512c3a589482c0c514'

#### : Pre-defined

In [4]:
#"http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
#        ?
#        LAWD_CD=11110
#        &
#        DEAL_YMD=201512
#        &
#        serviceKey=서비스키"

In [5]:
base_url = "https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade"

In [6]:
area_cd = "LAWD_CD=" + "11680"    # 11680 : 강남구
deal_dt = "DEAL_YMD=" + "202405"
svc_key = "serviceKey=" + my_key

In [7]:
url = base_url + "?" + area_cd + "&" + deal_dt + "&" + svc_key
url

'https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade?LAWD_CD=11680&DEAL_YMD=202405&serviceKey=accc226aba90e01bb632eb0bc06e1fe71b711c4f1144a8512c3a589482c0c514'

#### : Request Test

In [8]:
response = requests.get(url)
response

In [9]:
response.text

'<?xml version="1.0" encoding="utf-8" standalone="yes"?><response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong>109</aptDong><aptNm>신현대11차</aptNm><buildYear>1983</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>690,000</dealAmount><dealDay>17</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>183.41</excluUseAr><floor>3</floor><jibun>433</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.10.31</rgstDate><sggCd>11680</sggCd><slerGbn>법인</slerGbn><umdNm>압구정동</umdNm></item><item><aptDong>101</aptDong><aptNm>아크로힐스논현</aptNm><buildYear>2014</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>201,000</dealAmount><dealDay>31</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>84.208</excluUseAr><floor>2</floor><jibun>276-1</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.09.23</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>논현동</umdNm></item><item><aptDong>22</aptDong><aptNm>한양2</aptNm><buildYear>1978</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>590,000</dealAmount><dealDay>3</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>175.92</excluUseAr><floor>10</floor><jibun>493</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.09.12</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>압구정동</umdNm></item><item><aptDong>104</aptDong><aptNm>경남</aptNm><buildYear>2005</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>156,500</dealAmount><dealDay>27</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>59.76</excluUseAr><floor>3</floor><jibun>967</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.08.20</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>도곡동</umdNm></item><item><aptDong>101</aptDong><aptNm>럭키(963)</aptNm><buildYear>1995</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>193,000</dealAmount><dealDay>30</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>84.97</excluUseAr><floor>9</floor><jibun>963</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.07.26</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>도곡동</umdNm></item><item><aptDong>106</aptDong><aptNm>우성7</aptNm><buildYear>1987</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>205,000</dealAmount><dealDay>8</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>84.06</excluUseAr><floor>1</floor><jibun>615</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.07.15</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>일원동</umdNm></item><item><aptDong>청담스위트</aptDong><aptNm>청담스위트</aptNm><buildYear>2015</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>22,900</dealAmount><dealDay>29</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>13.425</excluUseAr><floor>8</floor><jibun>34-13</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.07.15</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>청담동</umdNm></item><item><aptDong>111</aptDong><aptNm>역삼래미안</aptNm><buildYear>2005</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>193,500</dealAmount><dealDay>26</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>59.4</excluUseAr><floor>11</floor><jibun>757</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.09.03</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>역삼동</umdNm></item><item><aptDong>2</aptDong><aptNm>경남1</aptNm><buildYear>1984</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>310,000</dealAmount><dealDay>29</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>123.28</excluUseAr><floor>7</floor><jibun>649</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>24.09.02</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>개포동</umdNm></item><item><aptDong>209</aptDong><aptNm>현대2</aptNm><buildYear>1986</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>305,000</dealAmount><dealDay>8</dealDay><dealMonth>5</dealMonth><dealYear>2024</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>131.83</excluUseAr><floor>4</floor><jibun>654</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.03.31</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>개포동</umdNm></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>328</totalCount></body></response>'

### Addtional Preparation :

#### -1)  Input Data : lawd_cd / 법정동 코드(지역코드) 가공

In [10]:
lawd_cd = pd.read_csv("C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/법정동코드 전체자료.txt",
                      sep='\t', encoding ='cp949') #'euc-kr', 'utf-8'
lawd_cd

            법정동코드                  법정동명 폐지여부
0      1100000000                 서울특별시   존재
1      1111000000             서울특별시 종로구   존재
2      1111010100         서울특별시 종로구 청운동   존재
3      1111010200         서울특별시 종로구 신교동   존재
4      1111010300         서울특별시 종로구 궁정동   존재
...           ...                   ...  ...
49856  5280042024    전북특별자치도 부안군 위도면 대리   존재
49857  5280042025   전북특별자치도 부안군 위도면 거륜리   존재
49858  5280042026   전북특별자치도 부안군 위도면 식도리   존재
49859  5280042027  전북특별자치도 부안군 위도면 상왕등리   존재
49860  5280042028  전북특별자치도 부안군 위도면 하왕등리   존재

[49861 rows x 3 columns]

In [11]:
# Column 이름 변경 : 데이터 조작 편의성을 위함
lawd_cd.columns

Index(['법정동코드', '법정동명', '폐지여부'], dtype='object')

In [12]:
lawd_cd.columns = ["code", "name", "check"]
lawd_cd

             code                  name check
0      1100000000                 서울특별시    존재
1      1111000000             서울특별시 종로구    존재
2      1111010100         서울특별시 종로구 청운동    존재
3      1111010200         서울특별시 종로구 신교동    존재
4      1111010300         서울특별시 종로구 궁정동    존재
...           ...                   ...   ...
49856  5280042024    전북특별자치도 부안군 위도면 대리    존재
49857  5280042025   전북특별자치도 부안군 위도면 거륜리    존재
49858  5280042026   전북특별자치도 부안군 위도면 식도리    존재
49859  5280042027  전북특별자치도 부안군 위도면 상왕등리    존재
49860  5280042028  전북특별자치도 부안군 위도면 하왕등리    존재

[49861 rows x 3 columns]

In [13]:
lawd_cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49861 entries, 0 to 49860
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   code    49861 non-null  int64
 1   name    49861 non-null  object
 2   check   49861 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.1+ MB

In [14]:
in_name = "남구"

In [15]:
lawd_cd['name'].str.contains(in_name)

0        False
1        False
2        False
3        False
4        False
         ...
49856    False
49857    False
49858    False
49859    False
49860    False
Name: name, Length: 49861, dtype: bool

In [16]:
lawd_cd['check'] == "존재"

0        True
1        True
2        True
3        True
4        True
         ...
49856    True
49857    True
49858    True
49859    True
49860    True
Name: check, Length: 49861, dtype: bool

In [17]:
(lawd_cd['name'].str.contains(in_name)) & (lawd_cd['check'] == "존재")

0        False
1        False
2        False
3        False
4        False
         ...
49856    False
49857    False
49858    False
49859    False
49860    False
Length: 49861, dtype: bool

In [18]:
lawd_cd[(lawd_cd['name'].str.contains(in_name)) & (lawd_cd['check'] == "존재")]

             code                   name check
1003   1168000000              서울특별시 강남구    존재
1037   1168010100          서울특별시 강남구 역삼동    존재
1039   1168010300          서울특별시 강남구 개포동    존재
1040   1168010400          서울특별시 강남구 청담동    존재
1041   1168010500          서울특별시 강남구 삼성동    존재
...           ...                    ...   ...
31310  4711135000       경상북도 포항시 남구 호미곶면    존재
31311  4711135021   경상북도 포항시 남구 호미곶면 강사리    존재
31312  4711135022   경상북도 포항시 남구 호미곶면 대보리    존재
31313  4711135023   경상북도 포항시 남구 호미곶면 구만리    존재
31314  4711135024  경상북도 포항시 남구 호미곶면 대동배리    존재

[300 rows x 3 columns]

In [19]:
tmp = lawd_cd[(lawd_cd['name'].str.contains('서울특별시')) &
              (lawd_cd['name'].str.contains(in_name)) & 
               (lawd_cd['check'] == "존재")].head(1)
tmp

            code       name check
1003  1168000000  서울특별시 강남구    존재

In [20]:
tmp.loc[1003,'code']    # 가져오기는 하나 문제 : 인덱스 값을 알아야 함

1168000000

In [21]:
tmp.iloc[0,0]           # 인덱스로 데이터를 가져오도록 === 문제없음

1168000000

In [22]:
tmp = tmp.iloc[0,0]
print(tmp)
type(tmp)

1168000000

numpy.int64

In [23]:
tmp

1168000000

In [24]:
str(tmp)

'1168000000'

In [25]:
tmp.astype(str)

'1168000000'

In [26]:
tmp = tmp.astype(str)
tmp

'1168000000'

In [27]:
tmp[:5]

'11680'

In [28]:
lawd_cd[(lawd_cd['name'].str.contains(in_name)) & (lawd_cd['check'] == "존재")].head(1).iloc[0,0].astype(str)[0:5]

'11680'

In [29]:
# Function 작성 :
def find_lawd_cd(in_text):
    result = lawd_cd[(lawd_cd['name'].str.contains(in_text)) & (lawd_cd['check'] == "존재")].head(1).iloc[0,0].astype(str)[0:5]    
    return result

In [30]:
in_name = "강남구"
find_lawd_cd(in_name)

'11680'

In [31]:
find_lawd_cd('중구')

'11140'

#### -2)  Input Data : lawd_cd, deal_ymd 입력받기

In [37]:
in_lawd = input("검색지역 입력 : ")

검색지역 입력 : 강남구

In [38]:
in_lawd

'강남구'

In [39]:
in_deal_ymd = input("계약월 입력(예: 201912) : ")

계약월 입력(예: 201912) : 202506

In [40]:
in_deal_ymd

'202506'

In [41]:
in_svckey = my_key

In [42]:
in_lawd_cd = find_lawd_cd(in_lawd)
in_lawd_cd

'11680'

In [43]:
area_cd = "LAWD_CD=" + in_lawd_cd
deal_dt = "DEAL_YMD=" + in_deal_ymd
svc_key = "serviceKey=" + in_svckey

In [44]:
url = base_url + "?" + area_cd + "&" + deal_dt + "&" + svc_key
url

'https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade?LAWD_CD=11680&DEAL_YMD=202506&serviceKey=accc226aba90e01bb632eb0bc06e1fe71b711c4f1144a8512c3a589482c0c514'

In [45]:
response = requests.get(url)
response

In [46]:
response.text

'<?xml version="1.0" encoding="utf-8" standalone="yes"?><response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong> </aptDong><aptNm>개포우성1</aptNm><buildYear>1983</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>620,000</dealAmount><dealDay>26</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>158.54</excluUseAr><floor>5</floor><jibun>503</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>대치동</umdNm></item><item><aptDong> </aptDong><aptNm>한양2</aptNm><buildYear>1978</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>786,000</dealAmount><dealDay>30</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>147.41</excluUseAr><floor>2</floor><jibun>493</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>압구정동</umdNm></item><item><aptDong> </aptDong><aptNm>현대2</aptNm><buildYear>1986</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>413,000</dealAmount><dealDay>27</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>165.08</excluUseAr><floor>6</floor><jibun>654</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>개포동</umdNm></item><item><aptDong>15</aptDong><aptNm>은마</aptNm><buildYear>1979</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>378,000</dealAmount><dealDay>17</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>84.43</excluUseAr><floor>14</floor><jibun>316</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.11.03</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>대치동</umdNm></item><item><aptDong>116</aptDong><aptNm>개포래미안포레스트</aptNm><buildYear>2020</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>289,000</dealAmount><dealDay>22</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>74.66</excluUseAr><floor>19</floor><jibun>1282</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.10.23</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>개포동</umdNm></item><item><aptDong>1단지 113</aptDong><aptNm>삼성동힐스테이트 1단지</aptNm><buildYear>2008</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>348,000</dealAmount><dealDay>24</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>84.236</excluUseAr><floor>11</floor><jibun>16-2</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.10.10</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>삼성동</umdNm></item><item><aptDong>10</aptDong><aptNm>현대2차(10,11,20,23,24,25동)</aptNm><buildYear>1976</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>1,200,000</dealAmount><dealDay>16</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>196.84</excluUseAr><floor>8</floor><jibun>369-1</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.10.02</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>압구정동</umdNm></item><item><aptDong>28</aptDong><aptNm>미성2차</aptNm><buildYear>1987</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>470,000</dealAmount><dealDay>25</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>74.4</excluUseAr><floor>3</floor><jibun>397</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.10.24</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>압구정동</umdNm></item><item><aptDong> </aptDong><aptNm>선경2차(8동-12동)</aptNm><buildYear>1985</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>530,000</dealAmount><dealDay>26</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>127.75</excluUseAr><floor>4</floor><jibun>506</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>대치동</umdNm></item><item><aptDong>104</aptDong><aptNm>디에이치포레센트</aptNm><buildYear>2021</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>290,000</dealAmount><dealDay>27</dealDay><dealMonth>6</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강남구</estateAgentSggNm><excluUseAr>84.94</excluUseAr><floor>4</floor><jibun>742</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate>25.09.19</rgstDate><sggCd>11680</sggCd><slerGbn>개인</slerGbn><umdNm>일원동</umdNm></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>610</totalCount></body></response>'

### 3. Data Preprocessng

#### : web data / API output

In [47]:
#### BS 시도 : 잘안됨
soup = BeautifulSoup(response.text, "lxml")
soup#print(soup.prettify())

C:\Users\USER\anaconda3\lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

<?xml version="1.0" encoding="utf-8" standalone="yes"?><html><body><response><header><resultcode>000</resultcode><resultmsg>OK</resultmsg></header><items><item><aptdong> </aptdong><aptnm>개포우성1</aptnm><buildyear>1983</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>620,000</dealamount><dealday>26</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>158.54</excluusear><floor>5</floor><jibun>503</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>대치동</umdnm></item><item><aptdong> </aptdong><aptnm>한양2</aptnm><buildyear>1978</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>786,000</dealamount><dealday>30</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>147.41</excluusear><floor>2</floor><jibun>493</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>압구정동</umdnm></item><item><aptdong> </aptdong><aptnm>현대2</aptnm><buildyear>1986</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>413,000</dealamount><dealday>27</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>165.08</excluusear><floor>6</floor><jibun>654</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>개포동</umdnm></item><item><aptdong>15</aptdong><aptnm>은마</aptnm><buildyear>1979</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>378,000</dealamount><dealday>17</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>84.43</excluusear><floor>14</floor><jibun>316</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.11.03</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>대치동</umdnm></item><item><aptdong>116</aptdong><aptnm>개포래미안포레스트</aptnm><buildyear>2020</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>289,000</dealamount><dealday>22</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>74.66</excluusear><floor>19</floor><jibun>1282</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.23</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>개포동</umdnm></item><item><aptdong>1단지 113</aptdong><aptnm>삼성동힐스테이트 1단지</aptnm><buildyear>2008</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>348,000</dealamount><dealday>24</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>84.236</excluusear><floor>11</floor><jibun>16-2</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.10</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>삼성동</umdnm></item><item><aptdong>10</aptdong><aptnm>현대2차(10,11,20,23,24,25동)</aptnm><buildyear>1976</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>1,200,000</dealamount><dealday>16</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>196.84</excluusear><floor>8</floor><jibun>369-1</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.02</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>압구정동</umdnm></item><item><aptdong>28</aptdong><aptnm>미성2차</aptnm><buildyear>1987</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>470,000</dealamount><dealday>25</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>74.4</excluusear><floor>3</floor><jibun>397</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.24</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>압구정동</umdnm></item><item><aptdong> </aptdong><aptnm>선경2차(8동-12동)</aptnm><buildyear>1985</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>530,000</dealamount><dealday>26</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>127.75</excluusear><floor>4</floor><jibun>506</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>대치동</umdnm></item><item><aptdong>104</aptdong><aptnm>디에이치포레센트</aptnm><buildyear>2021</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>290,000</dealamount><dealday>27</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>84.94</excluusear><floor>4</floor><jibun>742</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.09.19</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>일원동</umdnm></item></items><numofrows>10</numofrows><pageno>1</pageno><totalcount>610</totalcount></response></body></html>

In [48]:
soup.find_all('item')

[<item><aptdong> </aptdong><aptnm>개포우성1</aptnm><buildyear>1983</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>620,000</dealamount><dealday>26</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>158.54</excluusear><floor>5</floor><jibun>503</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>대치동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>한양2</aptnm><buildyear>1978</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>786,000</dealamount><dealday>30</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>147.41</excluusear><floor>2</floor><jibun>493</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>압구정동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>현대2</aptnm><buildyear>1986</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>413,000</dealamount><dealday>27</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>165.08</excluusear><floor>6</floor><jibun>654</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>개포동</umdnm></item>,
 <item><aptdong>15</aptdong><aptnm>은마</aptnm><buildyear>1979</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>378,000</dealamount><dealday>17</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>84.43</excluusear><floor>14</floor><jibun>316</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.11.03</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>대치동</umdnm></item>,
 <item><aptdong>116</aptdong><aptnm>개포래미안포레스트</aptnm><buildyear>2020</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>289,000</dealamount><dealday>22</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>74.66</excluusear><floor>19</floor><jibun>1282</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.23</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>개포동</umdnm></item>,
 <item><aptdong>1단지 113</aptdong><aptnm>삼성동힐스테이트 1단지</aptnm><buildyear>2008</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>348,000</dealamount><dealday>24</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>84.236</excluusear><floor>11</floor><jibun>16-2</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.10</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>삼성동</umdnm></item>,
 <item><aptdong>10</aptdong><aptnm>현대2차(10,11,20,23,24,25동)</aptnm><buildyear>1976</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>1,200,000</dealamount><dealday>16</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>196.84</excluusear><floor>8</floor><jibun>369-1</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.02</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>압구정동</umdnm></item>,
 <item><aptdong>28</aptdong><aptnm>미성2차</aptnm><buildyear>1987</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>470,000</dealamount><dealday>25</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>74.4</excluusear><floor>3</floor><jibun>397</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.10.24</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>압구정동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>선경2차(8동-12동)</aptnm><buildyear>1985</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>530,000</dealamount><dealday>26</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>127.75</excluusear><floor>4</floor><jibun>506</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>대치동</umdnm></item>,
 <item><aptdong>104</aptdong><aptnm>디에이치포레센트</aptnm><buildyear>2021</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>290,000</dealamount><dealday>27</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>84.94</excluusear><floor>4</floor><jibun>742</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate>25.09.19</rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>일원동</umdnm></item>]

In [49]:
item = soup.find('item')
print(item)

<item><aptdong> </aptdong><aptnm>개포우성1</aptnm><buildyear>1983</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>620,000</dealamount><dealday>26</dealday><dealmonth>6</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강남구</estateagentsggnm><excluusear>158.54</excluusear><floor>5</floor><jibun>503</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11680</sggcd><slergbn>개인</slergbn><umdnm>대치동</umdnm></item>

In [50]:
#item.find('거래금액')#.text

In [51]:
#### XML 파서로 시도
import xml.etree.ElementTree as ET

In [52]:
response#.content#.text

In [53]:
root = ET.fromstring(response.content)
root

In [54]:
item_list = []

In [55]:
root.find('body').find('items')[0]

In [56]:
type(root.find('body').find('items'))

xml.etree.ElementTree.Element

In [57]:
child = root.find('body').find('items')[0]
child

In [58]:
child.findall('*')#[0]

[<Element 'aptDong' at 0x00000147500CE310>,
 <Element 'aptNm' at 0x00000147500CE360>,
 <Element 'buildYear' at 0x00000147500CE3B0>,
 <Element 'buyerGbn' at 0x00000147500CE400>,
 <Element 'cdealDay' at 0x00000147500CE450>,
 <Element 'cdealType' at 0x00000147500CE4A0>,
 <Element 'dealAmount' at 0x00000147500CE4F0>,
 <Element 'dealDay' at 0x00000147500CE540>,
 <Element 'dealMonth' at 0x00000147500CE590>,
 <Element 'dealYear' at 0x00000147500CE5E0>,
 <Element 'dealingGbn' at 0x00000147500CE630>,
 <Element 'estateAgentSggNm' at 0x00000147500CE6D0>,
 <Element 'excluUseAr' at 0x00000147500CE720>,
 <Element 'floor' at 0x00000147500CE770>,
 <Element 'jibun' at 0x00000147500CE7C0>,
 <Element 'landLeaseholdGbn' at 0x00000147500CE860>,
 <Element 'rgstDate' at 0x00000147500CE8B0>,
 <Element 'sggCd' at 0x00000147500CE900>,
 <Element 'slerGbn' at 0x00000147500CE950>,
 <Element 'umdNm' at 0x00000147500CE9A0>]

In [59]:
element = child.findall('*')[0]

In [60]:
element.tag.strip()

'aptDong'

In [61]:
element.text.strip()

''

In [62]:
data = {}

In [63]:
tag = element.tag.strip()
text = element.text.strip()
data[tag] = text

In [64]:
data

{'aptDong': ''}

In [65]:
def find_xml_items(response):
    root = ET.fromstring(response.content)
    item_list = []
    for child in root.find('body').find('items'):
        elements = child.findall('*')
        data = {}
        for element in elements:
            tag = element.tag.strip()
            text = element.text.strip()
            data[tag] = text
        item_list.append(data)  
    return item_list

In [66]:
items_list = find_xml_items(response)
items_list

[{'aptDong': '',
  'aptNm': '개포우성1',
  'buildYear': '1983',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '620,000',
  'dealDay': '26',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '158.54',
  'floor': '5',
  'jibun': '503',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '대치동'},
 {'aptDong': '',
  'aptNm': '한양2',
  'buildYear': '1978',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '786,000',
  'dealDay': '30',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '147.41',
  'floor': '2',
  'jibun': '493',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '압구정동'},
 {'aptDong': '',
  'aptNm': '현대2',
  'buildYear': '1986',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '413,000',
  'dealDay': '27',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '165.08',
  'floor': '6',
  'jibun': '654',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '개포동'},
 {'aptDong': '15',
  'aptNm': '은마',
  'buildYear': '1979',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '378,000',
  'dealDay': '17',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '84.43',
  'floor': '14',
  'jibun': '316',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.11.03',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '대치동'},
 {'aptDong': '116',
  'aptNm': '개포래미안포레스트',
  'buildYear': '2020',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '289,000',
  'dealDay': '22',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '74.66',
  'floor': '19',
  'jibun': '1282',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.23',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '개포동'},
 {'aptDong': '1단지 113',
  'aptNm': '삼성동힐스테이트 1단지',
  'buildYear': '2008',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '348,000',
  'dealDay': '24',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '84.236',
  'floor': '11',
  'jibun': '16-2',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.10',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '삼성동'},
 {'aptDong': '10',
  'aptNm': '현대2차(10,11,20,23,24,25동)',
  'buildYear': '1976',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '1,200,000',
  'dealDay': '16',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '196.84',
  'floor': '8',
  'jibun': '369-1',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.02',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '압구정동'},
 {'aptDong': '28',
  'aptNm': '미성2차',
  'buildYear': '1987',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '470,000',
  'dealDay': '25',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '74.4',
  'floor': '3',
  'jibun': '397',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.24',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '압구정동'},
 {'aptDong': '',
  'aptNm': '선경2차(8동-12동)',
  'buildYear': '1985',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '530,000',
  'dealDay': '26',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '127.75',
  'floor': '4',
  'jibun': '506',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '대치동'},
 {'aptDong': '104',
  'aptNm': '디에이치포레센트',
  'buildYear': '2021',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '290,000',
  'dealDay': '27',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '84.94',
  'floor': '4',
  'jibun': '742',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.09.19',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '일원동'}]

### 4. Result : Display & Save as file

In [67]:
result = pd.DataFrame(items_list)

In [68]:
result

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,dealingGbn,estateAgentSggNm,excluUseAr,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm
0,,개포우성1,1983,개인,,,"620,000",26,6,2025,중개거래,서울 강남구,158.54,5,503,N,,11680,개인,대치동
1,,한양2,1978,개인,,,"786,000",30,6,2025,중개거래,서울 강남구,147.41,2,493,N,,11680,개인,압구정동
2,,현대2,1986,개인,,,"413,000",27,6,2025,중개거래,서울 강남구,165.08,6,654,N,,11680,개인,개포동
3,15,은마,1979,개인,,,"378,000",17,6,2025,중개거래,서울 강남구,84.43,14,316,N,25.11.03,11680,개인,대치동
4,116,개포래미안포레스트,2020,개인,,,"289,000",22,6,2025,중개거래,서울 강남구,74.66,19,1282,N,25.10.23,11680,개인,개포동
5,1단지 113,삼성동힐스테이트 1단지,2008,개인,,,"348,000",24,6,2025,중개거래,서울 강남구,84.236,11,16-2,N,25.10.10,11680,개인,삼성동
6,10,"현대2차(10,11,20,23,24,25동)",1976,개인,,,"1,200,000",16,6,2025,중개거래,서울 강남구,196.84,8,369-1,N,25.10.02,11680,개인,압구정동
7,28,미성2차,1987,개인,,,"470,000",25,6,2025,중개거래,서울 강남구,74.4,3,397,N,25.10.24,11680,개인,압구정동
8,,선경2차(8동-12동),1985,개인,,,"530,000",26,6,2025,중개거래,서울 강남구,127.75,4,506,N,,11680,개인,대치동
9,104,디에이치포레센트,2021,개인,,,"290,000",27,6,2025,중개거래,서울 강남구,84.94,4,742,N,25.09.19,11680,개인,일원동

In [69]:
result.shape

(10, 20)

In [70]:
result.head()

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,dealingGbn,estateAgentSggNm,excluUseAr,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm
0,,개포우성1,1983,개인,,,"620,000",26,6,2025,중개거래,서울 강남구,158.54,5,503,N,,11680,개인,대치동
1,,한양2,1978,개인,,,"786,000",30,6,2025,중개거래,서울 강남구,147.41,2,493,N,,11680,개인,압구정동
2,,현대2,1986,개인,,,"413,000",27,6,2025,중개거래,서울 강남구,165.08,6,654,N,,11680,개인,개포동
3,15,은마,1979,개인,,,"378,000",17,6,2025,중개거래,서울 강남구,84.43,14,316,N,25.11.03,11680,개인,대치동
4,116,개포래미안포레스트,2020,개인,,,"289,000",22,6,2025,중개거래,서울 강남구,74.66,19,1282,N,25.10.23,11680,개인,개포동

#### : file name

In [71]:
name_info = in_lawd + "_" + in_deal_ymd
name_info

'강남구_202506'

In [72]:
file_name = f"C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/result_{name_info}.csv"
file_name

'C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/result_강남구_202506.csv'

In [73]:
result.to_csv(file_name, index=False, encoding='cp949')

## Appendix : Function

In [74]:
find_lawd_cd(in_lawd)

'11680'

In [75]:
find_xml_items(response)

[{'aptDong': '',
  'aptNm': '개포우성1',
  'buildYear': '1983',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '620,000',
  'dealDay': '26',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '158.54',
  'floor': '5',
  'jibun': '503',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '대치동'},
 {'aptDong': '',
  'aptNm': '한양2',
  'buildYear': '1978',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '786,000',
  'dealDay': '30',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '147.41',
  'floor': '2',
  'jibun': '493',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '압구정동'},
 {'aptDong': '',
  'aptNm': '현대2',
  'buildYear': '1986',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '413,000',
  'dealDay': '27',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '165.08',
  'floor': '6',
  'jibun': '654',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '개포동'},
 {'aptDong': '15',
  'aptNm': '은마',
  'buildYear': '1979',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '378,000',
  'dealDay': '17',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '84.43',
  'floor': '14',
  'jibun': '316',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.11.03',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '대치동'},
 {'aptDong': '116',
  'aptNm': '개포래미안포레스트',
  'buildYear': '2020',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '289,000',
  'dealDay': '22',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '74.66',
  'floor': '19',
  'jibun': '1282',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.23',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '개포동'},
 {'aptDong': '1단지 113',
  'aptNm': '삼성동힐스테이트 1단지',
  'buildYear': '2008',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '348,000',
  'dealDay': '24',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '84.236',
  'floor': '11',
  'jibun': '16-2',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.10',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '삼성동'},
 {'aptDong': '10',
  'aptNm': '현대2차(10,11,20,23,24,25동)',
  'buildYear': '1976',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '1,200,000',
  'dealDay': '16',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '196.84',
  'floor': '8',
  'jibun': '369-1',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.02',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '압구정동'},
 {'aptDong': '28',
  'aptNm': '미성2차',
  'buildYear': '1987',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '470,000',
  'dealDay': '25',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '74.4',
  'floor': '3',
  'jibun': '397',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.10.24',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '압구정동'},
 {'aptDong': '',
  'aptNm': '선경2차(8동-12동)',
  'buildYear': '1985',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '530,000',
  'dealDay': '26',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '127.75',
  'floor': '4',
  'jibun': '506',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '대치동'},
 {'aptDong': '104',
  'aptNm': '디에이치포레센트',
  'buildYear': '2021',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '290,000',
  'dealDay': '27',
  'dealMonth': '6',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': '84.94',
  'floor': '4',
  'jibun': '742',
  'landLeaseholdGbn': 'N',
  'rgstDate': '25.09.19',
  'sggCd': '11680',
  'slerGbn': '개인',
  'umdNm': '일원동'}]

In [76]:
def deal_by_lawd(cd_name, ymd):
    
    func_cd = find_lawd_cd(cd_name)
    
    svckey = my_key
    
    area_cd = "LAWD_CD=" + func_cd
    deal_dt = "DEAL_YMD=" + ymd
    svc_key = "serviceKey=" + svckey
    url = base_url + "?" + area_cd + "&" + deal_dt + "&" + svc_key

    response = requests.get(url)
    items_list = find_xml_items(response)
    result = pd.DataFrame(items_list)
    
    name_info = cd_name + "_" + ymd
    file_name = f"C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/result_{name_info}.csv"

    result.to_csv(file_name, index=False, encoding='cp949')
    
    return file_name

In [77]:
#### - Input Data : LAWD_CD, DEAL_YMD, serviceKey  입력받기
func_gu = input("검색지역 입력 : ")
print(func_gu)

func_ymd = input("계약월 입력(예: 201911) : ")
print(func_ymd)

검색지역 입력 : 서울특별시
서울특별시
계약월 입력(예: 201911) : 202506
202506

In [78]:
deal_by_lawd(func_gu, func_ymd)

'C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/result_서울특별시_202506.csv'

### 추가 실습 :
- 공공API 데이터 끌어오기 친숙해지기
- **(필수) 특정월에 서울시 전체 구의 데이터를 한번에 가져오기(입력값: 연월 202402)**
- (선택) 특정 서울시 하나의 구의 과거 1년치 데이터를 한번에 가져오기(입력값: 특정구 하나)

- 기상청_중기예보 조회서비스 (추가 API 사용신청 필요)    
https://www.data.go.kr/tcs/dss/selectApiDataDetailView.do?publicDataPk=15059468

### 코드리뷰 과제(1)

- 서울시 모든 구의 리스트 추려내는 방법

In [79]:
lawd_cd

             code                  name check
0      1100000000                 서울특별시    존재
1      1111000000             서울특별시 종로구    존재
2      1111010100         서울특별시 종로구 청운동    존재
3      1111010200         서울특별시 종로구 신교동    존재
4      1111010300         서울특별시 종로구 궁정동    존재
...           ...                   ...   ...
49856  5280042024    전북특별자치도 부안군 위도면 대리    존재
49857  5280042025   전북특별자치도 부안군 위도면 거륜리    존재
49858  5280042026   전북특별자치도 부안군 위도면 식도리    존재
49859  5280042027  전북특별자치도 부안군 위도면 상왕등리    존재
49860  5280042028  전북특별자치도 부안군 위도면 하왕등리    존재

[49861 rows x 3 columns]

- 파이썬으로 구하는 방법

In [174]:
#1번 for 문
seoul = []
for i in range(len(lawd_cd)):
    if '서울특별시' in lawd_cd.loc[i, 'name']:
        seoul.append(i)
        
seoul_df = lawd_cd.loc[seoul]

In [175]:
seoul_df

            code           name check
0     1100000000          서울특별시    존재
1     1111000000      서울특별시 종로구    존재
2     1111010100  서울특별시 종로구 청운동    존재
3     1111010200  서울특별시 종로구 신교동    존재
4     1111010300  서울특별시 종로구 궁정동    존재
...          ...            ...   ...
1107  1174010600  서울특별시 강동구 둔촌동    존재
1108  1174010700  서울특별시 강동구 암사동    존재
1109  1174010800  서울특별시 강동구 성내동    존재
1110  1174010900  서울특별시 강동구 천호동    존재
1111  1174011000  서울특별시 강동구 강일동    존재

[1112 rows x 3 columns]

In [179]:
#2번 for 문
mask = []
for i in lawd_cd['name']:
    mask.append('서울특별시' in i)
    
seoul_df = lawd_cd[mask]

In [180]:
seoul_df

            code           name check
0     1100000000          서울특별시    존재
1     1111000000      서울특별시 종로구    존재
2     1111010100  서울특별시 종로구 청운동    존재
3     1111010200  서울특별시 종로구 신교동    존재
4     1111010300  서울특별시 종로구 궁정동    존재
...          ...            ...   ...
1107  1174010600  서울특별시 강동구 둔촌동    존재
1108  1174010700  서울특별시 강동구 암사동    존재
1109  1174010800  서울특별시 강동구 성내동    존재
1110  1174010900  서울특별시 강동구 천호동    존재
1111  1174011000  서울특별시 강동구 강일동    존재

[1112 rows x 3 columns]

- 판다스로 구하는 방법

In [ ]:
lawd_cd_seoule = lawd_cd[lawd_cd['name'].str.contains('서울특별시')]

In [ ]:
lawd_cd_seoule['name'].value_counts()

In [185]:
name_list = list(lawd_cd_seoule['name'])
name_list

['서울특별시',
 '서울특별시 종로구',
 '서울특별시 종로구 청운동',
 '서울특별시 종로구 신교동',
 '서울특별시 종로구 궁정동',
 '서울특별시 종로구 효자동',
 '서울특별시 종로구 창성동',
 '서울특별시 종로구 통의동',
 '서울특별시 종로구 적선동',
 '서울특별시 종로구 통인동',
 '서울특별시 종로구 누상동',
 '서울특별시 종로구 누하동',
 '서울특별시 종로구 옥인동',
 '서울특별시 종로구 체부동',
 '서울특별시 종로구 필운동',
 '서울특별시 종로구 내자동',
 '서울특별시 종로구 사직동',
 '서울특별시 종로구 도렴동',
 '서울특별시 종로구 당주동',
 '서울특별시 종로구 내수동',
 '서울특별시 종로구 세종로',
 '서울특별시 종로구 신문로1가',
 '서울특별시 종로구 신문로2가',
 '서울특별시 종로구 청진동',
 '서울특별시 종로구 서린동',
 '서울특별시 종로구 수송동',
 '서울특별시 종로구 중학동',
 '서울특별시 종로구 종로1가',
 '서울특별시 종로구 공평동',
 '서울특별시 종로구 관훈동',
 '서울특별시 종로구 견지동',
 '서울특별시 종로구 와룡동',
 '서울특별시 종로구 권농동',
 '서울특별시 종로구 운니동',
 '서울특별시 종로구 익선동',
 '서울특별시 종로구 경운동',
 '서울특별시 종로구 관철동',
 '서울특별시 종로구 인사동',
 '서울특별시 종로구 낙원동',
 '서울특별시 종로구 종로2가',
 '서울특별시 종로구 팔판동',
 '서울특별시 종로구 삼청동',
 '서울특별시 종로구 안국동',
 '서울특별시 종로구 소격동',
 '서울특별시 종로구 화동',
 '서울특별시 종로구 사간동',
 '서울특별시 종로구 송현동',
 '서울특별시 종로구 가회동',
 '서울특별시 종로구 재동',
 '서울특별시 종로구 계동',
 '서울특별시 종로구 원서동',
 '서울특별시 종로구 훈정동',
 '서울특별시 종로구 묘동',
 '서울특별시 종로구 봉익동',
 '서울특별시 종로구 돈의동',
 '서울특별시 종로구 장사동',
 '서울특별시 종로구 관수동',
 '서울특별시 종로구 종로3가',
 '서울특별시 종로구 인의동',
 '서울특별시 종로구 예지동',
 '서울특별시 종로구 원남동',
 '서울특별시 종로구 연지동',
 '서울특별시 종로구 종로4가',
 '서울특별시 종로구 효제동',
 '서울특별시 종로구 종로5가',
 '서울특별시 종로구 종로6가',
 '서울특별시 종로구 이화동',
 '서울특별시 종로구 연건동',
 '서울특별시 종로구 충신동',
 '서울특별시 종로구 동숭동',
 '서울특별시 종로구 혜화동',
 '서울특별시 종로구 명륜1가',
 '서울특별시 종로구 명륜2가',
 '서울특별시 종로구 명륜4가',
 '서울특별시 종로구 명륜3가',
 '서울특별시 종로구 창신동',
 '서울특별시 종로구 숭인동',
 '서울특별시 종로구 교남동',
 '서울특별시 종로구 평동',
 '서울특별시 종로구 송월동',
 '서울특별시 종로구 홍파동',
 '서울특별시 종로구 교북동',
 '서울특별시 종로구 행촌동',
 '서울특별시 종로구 구기동',
 '서울특별시 종로구 평창동',
 '서울특별시 종로구 부암동',
 '서울특별시 종로구 홍지동',
 '서울특별시 종로구 신영동',
 '서울특별시 종로구 무악동',
 '서울특별시 종로구 창신1동',
 '서울특별시 종로구 창신2동',
 '서울특별시 종로구 창신3동',
 '서울특별시 종로구 숭인1동',
 '서울특별시 종로구 숭인2동',
 '서울특별시 중구',
 '서울특별시 중구 동자동',
 '서울특별시 중구 도동1가',
 '서울특별시 중구 도동2가',
 '서울특별시 중구 양동',
 '서울특별시 중구 무교동',
 '서울특별시 중구 다동',
 '서울특별시 중구 태평로1가',
 '서울특별시 중구 을지로1가',
 '서울특별시 중구 을지로2가',
 '서울특별시 중구 남대문로1가',
 '서울특별시 중구 삼각동',
 '서울특별시 중구 수하동',
 '서울특별시 중구 장교동',
 '서울특별시 중구 수표동',
 '서울특별시 중구 소공동',
 '서울특별시 중구 남창동',
 '서울특별시 중구 북창동',
 '서울특별시 중구 태평로2가',
 '서울특별시 중구 남대문로2가',
 '서울특별시 중구 남대문로3가',
 '서울특별시 중구 남대문로4가',
 '서울특별시 중구 남대문로5가',
 '서울특별시 중구 봉래동1가',
 '서울특별시 중구 봉래동2가',
 '서울특별시 중구 회현동1가',
 '서울특별시 중구 회현동2가',
 '서울특별시 중구 회현동3가',
 '서울특별시 중구 충무로1가',
 '서울특별시 중구 충무로2가',
 '서울특별시 중구 명동1가',
 '서울특별시 중구 명동2가',
 '서울특별시 중구 남산동1가',
 '서울특별시 중구 남산동2가',
 '서울특별시 중구 남산동3가',
 '서울특별시 중구 저동1가',
 '서울특별시 중구 충무로4가',
 '서울특별시 중구 충무로5가',
 '서울특별시 중구 인현동2가',
 '서울특별시 중구 예관동',
 '서울특별시 중구 묵정동',
 '서울특별시 중구 필동1가',
 '서울특별시 중구 필동2가',
 '서울특별시 중구 필동3가',
 '서울특별시 중구 남학동',
 '서울특별시 중구 주자동',
 '서울특별시 중구 예장동',
 '서울특별시 중구 장충동1가',
 '서울특별시 중구 장충동2가',
 '서울특별시 중구 광희동1가',
 '서울특별시 중구 광희동2가',
 '서울특별시 중구 쌍림동',
 '서울특별시 중구 을지로6가',
 '서울특별시 중구 을지로7가',
 '서울특별시 중구 을지로4가',
 '서울특별시 중구 을지로5가',
 '서울특별시 중구 주교동',
 '서울특별시 중구 방산동',
 '서울특별시 중구 오장동',
 '서울특별시 중구 을지로3가',
 '서울특별시 중구 입정동',
 '서울특별시 중구 산림동',
 '서울특별시 중구 충무로3가',
 '서울특별시 중구 초동',
 '서울특별시 중구 인현동1가',
 '서울특별시 중구 저동2가',
 '서울특별시 중구 신당동',
 '서울특별시 중구 흥인동',
 '서울특별시 중구 무학동',
 '서울특별시 중구 황학동',
 '서울특별시 중구 서소문동',
 '서울특별시 중구 정동',
 '서울특별시 중구 순화동',
 '서울특별시 중구 의주로1가',
 '서울특별시 중구 충정로1가',
 '서울특별시 중구 중림동',
 '서울특별시 중구 의주로2가',
 '서울특별시 중구 만리동1가',
 '서울특별시 중구 만리동2가',
 '서울특별시 중구 신당1동',
 '서울특별시 중구 신당2동',
 '서울특별시 중구 신당3동',
 '서울특별시 중구 신당4동',
 '서울특별시 중구 신당5동',
 '서울특별시 중구 신당6동',
 '서울특별시 용산구',
 '서울특별시 용산구 옥수동',
 '서울특별시 용산구 도동1가',
 '서울특별시 용산구 도동2가',
 '서울특별시 용산구 만리동1가',
 '서울특별시 용산구 만리동2가',
 '서울특별시 용산구 후암동',
 '서울특별시 용산구 용산동2가',
 '서울특별시 용산구 용산동4가',
 '서울특별시 용산구 갈월동',
 '서울특별시 용산구 남영동',
 '서울특별시 용산구 용산동1가',
 '서울특별시 용산구 동자동',
 '서울특별시 용산구 서계동',
 '서울특별시 용산구 청파동1가',
 '서울특별시 용산구 청파동2가',
 '서울특별시 용산구 청파동3가',
 '서울특별시 용산구 원효로1가',
 '서울특별시 용산구 원효로2가',
 '서울특별시 용산구 신창동',
 '서울특별시 용산구 산천동',
 '서울특별시 용산구 청암동',
 '서울특별시 용산구 원효로3가',
 '서울특별시 용산구 원효로4가',
 '서울특별시 용산구 효창동',
 '서울특별시 용산구 도원동',
 '서울특별시 용산구 용문동',
 '서울특별시 용산구 문배동',
 '서울특별시 용산구 신계동',
 '서울특별시 용산구 한강로1가',
 '서울특별시 용산구 한강로2가',
 '서울특별시 용산구 용산동3가',
 '서울특별시 용산구 용산동5가',
 '서울특별시 용산구 한강로3가',
 '서울특별시 용산구 이촌동',
 '서울특별시 용산구 이태원동',
 '서울특별시 용산구 한남동',
 '서울특별시 용산구 동빙고동',
 '서울특별시 용산구 서빙고동',
 '서울특별시 용산구 주성동',
 '서울특별시 용산구 용산동6가',
 '서울특별시 용산구 보광동',
 '서울특별시 용산구 청파1동',
 '서울특별시 용산구 청파2동',
 '서울특별시 용산구 이촌1동',
 '서울특별시 용산구 이촌2동',
 '서울특별시 용산구 이태원1동',
 '서울특별시 용산구 이태원2동',
 '서울특별시 용산구 한남1동',
 '서울특별시 용산구 한남2동',
 '서울특별시 성동구',
 '서울특별시 성동구 상일동',
 '서울특별시 성동구 길동',
 '서울특별시 성동구 둔촌동',
 '서울특별시 성동구 암사동',
 '서울특별시 성동구 성내동',
 '서울특별시 성동구 풍납동',
 '서울특별시 성동구 천호동',
 '서울특별시 성동구 송파동',
 '서울특별시 성동구 석촌동',
 '서울특별시 성동구 삼전동',
 '서울특별시 성동구 가락동',
 '서울특별시 성동구 이동',
 '서울특별시 성동구 오금동',
 '서울특별시 성동구 방이동',
 '서울특별시 성동구 문정동',
 '서울특별시 성동구 장지동',
 '서울특별시 성동구 거여동',
 '서울특별시 성동구 마천동',
 '서울특별시 성동구 잠실동',
 '서울특별시 성동구 신천동',
 '서울특별시 성동구 일원동',
 '서울특별시 성동구 수서동',
 '서울특별시 성동구 자곡동',
 '서울특별시 성동구 율현동',
 '서울특별시 성동구 세곡동',
 '서울특별시 성동구 역삼동',
 '서울특별시 성동구 포이동',
 '서울특별시 성동구 개포동',
 '서울특별시 성동구 도곡동',
 '서울특별시 성동구 논현동',
 '서울특별시 성동구 신사동',
 '서울특별시 성동구 학동',
 '서울특별시 성동구 압구정동',
 '서울특별시 성동구 청담동',
 '서울특별시 성동구 삼성동',
 '서울특별시 성동구 대치동',
 '서울특별시 성동구 염곡동',
 '서울특별시 성동구 내곡동',
 '서울특별시 성동구 신원동',
 '서울특별시 성동구 반포동',
 '서울특별시 성동구 잠원동',
 '서울특별시 성동구 서초동',
 '서울특별시 성동구 양재동',
 '서울특별시 성동구 우면동',
 '서울특별시 성동구 원지동',
 '서울특별시 성동구 황학동',
 '서울특별시 성동구 무학동',
 '서울특별시 성동구 흥인동',
 '서울특별시 성동구 신당동',
 '서울특별시 성동구 용두동',
 '서울특별시 성동구 답십리동',
 '서울특별시 성동구 면목동',
 '서울특별시 성동구 금호동',
 '서울특별시 성동구 명일동',
 '서울특별시 성동구 하일동',
 '서울특별시 성동구 고덕동',
 '서울특별시 성동구 상왕십리동',
 '서울특별시 성동구 하왕십리동',
 '서울특별시 성동구 홍익동',
 '서울특별시 성동구 도선동',
 '서울특별시 성동구 마장동',
 '서울특별시 성동구 사근동',
 '서울특별시 성동구 행당동',
 '서울특별시 성동구 응봉동',
 '서울특별시 성동구 금호동1가',
 '서울특별시 성동구 금호동2가',
 '서울특별시 성동구 금호동3가',
 '서울특별시 성동구 금호동4가',
 '서울특별시 성동구 옥수동',
 '서울특별시 성동구 성수동1가',
 '서울특별시 성동구 성수동2가',
 '서울특별시 성동구 화양동',
 '서울특별시 성동구 모진동',
 '서울특별시 성동구 송정동',
 '서울특별시 성동구 군자동',
 '서울특별시 성동구 중곡동',
 '서울특별시 성동구 능동',
 '서울특별시 성동구 용답동',
 '서울특별시 성동구 광장동',
 '서울특별시 성동구 구의동',
 '서울특별시 성동구 자양동',
 '서울특별시 성동구 왕십리1동',
 '서울특별시 성동구 왕십리2동',
 '서울특별시 성동구 행당1동',
 '서울특별시 성동구 행당2동',
 '서울특별시 성동구 중곡1동',
 '서울특별시 성동구 중곡2동',
 '서울특별시 성동구 중곡3동',
 '서울특별시 성동구 중곡4동',
 '서울특별시 성동구 옥수1동',
 '서울특별시 성동구 옥수2동',
 '서울특별시 성동구 성수1가1동',
 '서울특별시 성동구 성수1가2동',
 '서울특별시 성동구 성수2가1동',
 '서울특별시 성동구 성수2가2동',
 '서울특별시 성동구 성수2가3동',
 '서울특별시 성동구 성수2가4동',
 '서울특별시 성동구 자양1동',
 '서울특별시 성동구 자양2동',
 '서울특별시 성동구 자양3동',
 '서울특별시 성동구 구의1동',
 '서울특별시 성동구 구의2동',
 '서울특별시 광진구',
 '서울특별시 광진구 중곡동',
 '서울특별시 광진구 능동',
 '서울특별시 광진구 구의동',
 '서울특별시 광진구 광장동',
 '서울특별시 광진구 자양동',
 '서울특별시 광진구 노유동',
 '서울특별시 광진구 화양동',
 '서울특별시 광진구 모진동',
 '서울특별시 광진구 군자동',
 '서울특별시 동대문구',
 '서울특별시 동대문구 면목동',
 '서울특별시 동대문구 상봉동',
 '서울특별시 동대문구 중화동',
 '서울특별시 동대문구 묵동',
 '서울특별시 동대문구 망우동',
 '서울특별시 동대문구 신내동',
 '서울특별시 동대문구 중곡동',
 '서울특별시 동대문구 능동',
 '서울특별시 동대문구 군자동',
 '서울특별시 동대문구 종암동',
 '서울특별시 동대문구 안암동4가',
 '서울특별시 동대문구 안암동5가',
 '서울특별시 동대문구 석관동',
 '서울특별시 동대문구 보문동1가',
 '서울특별시 동대문구 보문동2가',
 '서울특별시 동대문구 보문동3가',
 '서울특별시 동대문구 보문동4가',
 '서울특별시 동대문구 보문동5가',
 '서울특별시 동대문구 보문동6가',
 '서울특별시 동대문구 보문동7가',
 '서울특별시 동대문구 창신동',
 '서울특별시 동대문구 숭인동',
 '서울특별시 동대문구 신설동',
 '서울특별시 동대문구 용두동',
 '서울특별시 동대문구 제기동',
 '서울특별시 동대문구 전농동',
 '서울특별시 동대문구 답십리동',
 '서울특별시 동대문구 장안동',
 '서울특별시 동대문구 청량리동',
 '서울특별시 동대문구 회기동',
 '서울특별시 동대문구 휘경동',
 '서울특별시 동대문구 이문동',
 '서울특별시 동대문구 용두1동',
 '서울특별시 동대문구 용두2동',
 '서울특별시 동대문구 제기1동',
 '서울특별시 동대문구 제기2동',
 '서울특별시 동대문구 전농1동',
 '서울특별시 동대문구 전농2동',
 '서울특별시 동대문구 전농3동',
 '서울특별시 동대문구 전농4동',
 '서울특별시 동대문구 답십리1동',
 '서울특별시 동대문구 답십리2동',
 '서울특별시 동대문구 답십리3동',
 '서울특별시 동대문구 답십리4동',
 '서울특별시 동대문구 답십리5동',
 '서울특별시 동대문구 장안1동',
 '서울특별시 동대문구 장안2동',
 '서울특별시 동대문구 장안3동',
 '서울특별시 동대문구 장안4동',
 '서울특별시 동대문구 청량리1동',
 '서울특별시 동대문구 청량리2동',
 '서울특별시 동대문구 휘경1동',
 '서울특별시 동대문구 휘경2동',
 '서울특별시 동대문구 이문1동',
 '서울특별시 동대문구 이문2동',
 '서울특별시 동대문구 이문3동',
 '서울특별시 중랑구',
 '서울특별시 중랑구 면목동',
 '서울특별시 중랑구 상봉동',
 '서울특별시 중랑구 중화동',
 '서울특별시 중랑구 묵동',
 '서울특별시 중랑구 망우동',
 '서울특별시 중랑구 신내동',
 '서울특별시 중랑구 면목1동',
 '서울특별시 중랑구 면목2동',
 '서울특별시 중랑구 면목3동',
 '서울특별시 중랑구 면목4동',
 '서울특별시 중랑구 면목5동',
 '서울특별시 중랑구 면목6동',
 '서울특별시 중랑구 면목7동',
 '서울특별시 중랑구 상봉1동',
 '서울특별시 중랑구 상봉2동',
 '서울특별시 중랑구 중화1동',
 '서울특별시 중랑구 중화2동',
 '서울특별시 중랑구 묵1동',
 '서울특별시 중랑구 묵2동',
 '서울특별시 중랑구 망우1동',
 '서울특별시 중랑구 망우2동',
 '서울특별시 중랑구 망우3동',
 '서울특별시 성북구',
 '서울특별시 성북구 미아동',
 '서울특별시 성북구 번동',
 '서울특별시 성북구 수유동',
 '서울특별시 성북구 우이동',
 '서울특별시 성북구 창동',
 '서울특별시 성북구 월계동',
 '서울특별시 성북구 쌍문동',
 '서울특별시 성북구 공릉동',
 '서울특별시 성북구 하계동',
 '서울특별시 성북구 상계동',
 '서울특별시 성북구 중계동',
 '서울특별시 성북구 도봉동',
 '서울특별시 성북구 방학동',
 '서울특별시 성북구 성북동2가',
 '서울특별시 성북구 동소문동8가',
 '서울특별시 성북구 성북동',
 '서울특별시 성북구 성북동1가',
 '서울특별시 성북구 돈암동',
 '서울특별시 성북구 동소문동1가',
 '서울특별시 성북구 동소문동2가',
 '서울특별시 성북구 동소문동3가',
 '서울특별시 성북구 동소문동4가',
 '서울특별시 성북구 동소문동5가',
 '서울특별시 성북구 동소문동6가',
 '서울특별시 성북구 동소문동7가',
 '서울특별시 성북구 삼선동1가',
 '서울특별시 성북구 삼선동2가',
 '서울특별시 성북구 삼선동3가',
 '서울특별시 성북구 삼선동4가',
 '서울특별시 성북구 삼선동5가',
 '서울특별시 성북구 동선동1가',
 '서울특별시 성북구 동선동2가',
 '서울특별시 성북구 동선동3가',
 '서울특별시 성북구 동선동4가',
 '서울특별시 성북구 동선동5가',
 '서울특별시 성북구 안암동1가',
 '서울특별시 성북구 안암동2가',
 '서울특별시 성북구 안암동3가',
 '서울특별시 성북구 안암동4가',
 '서울특별시 성북구 안암동5가',
 '서울특별시 성북구 보문동4가',
 '서울특별시 성북구 보문동5가',
 '서울특별시 성북구 보문동6가',
 '서울특별시 성북구 보문동7가',
 '서울특별시 성북구 보문동1가',
 '서울특별시 성북구 보문동2가',
 '서울특별시 성북구 보문동3가',
 '서울특별시 성북구 정릉동',
 '서울특별시 성북구 길음동',
 '서울특별시 성북구 종암동',
 '서울특별시 성북구 하월곡동',
 '서울특별시 성북구 상월곡동',
 '서울특별시 성북구 장위동',
 '서울특별시 성북구 석관동',
 '서울특별시 성북구 성북1동',
 '서울특별시 성북구 성북2동',
 '서울특별시 성북구 삼선1동',
 '서울특별시 성북구 삼선2동',
 '서울특별시 성북구 동선1동',
 '서울특별시 성북구 동선2동',
 '서울특별시 성북구 돈암1동',
 '서울특별시 성북구 돈암2동',
 '서울특별시 성북구 정릉1동',
 '서울특별시 성북구 정릉2동',
 '서울특별시 성북구 정릉3동',
 '서울특별시 성북구 정릉4동',
 '서울특별시 성북구 길음1동',
 '서울특별시 성북구 길음2동',
 '서울특별시 성북구 길음3동',
 '서울특별시 성북구 종암1동',
 '서울특별시 성북구 종암2동',
 '서울특별시 성북구 하월곡1동',
 '서울특별시 성북구 하월곡2동',
 '서울특별시 성북구 하월곡3동',
 '서울특별시 성북구 하월곡4동',
 '서울특별시 성북구 장위1동',
 '서울특별시 성북구 장위2동',
 '서울특별시 성북구 장위3동',
 '서울특별시 성북구 석관1동',
 '서울특별시 성북구 석관2동',
 '서울특별시 강북구',
 '서울특별시 강북구 미아동',
 '서울특별시 강북구 번동',
 '서울특별시 강북구 수유동',
 '서울특별시 강북구 우이동',
 '서울특별시 도봉구',
 '서울특별시 도봉구 상계동',
 '서울특별시 도봉구 중계동',
 '서울특별시 도봉구 하계동',
 '서울특별시 도봉구 월계동',
 '서울특별시 도봉구 공릉동',
 '서울특별시 도봉구 미아동',
 '서울특별시 도봉구 번동',
 '서울특별시 도봉구 수유동',
 '서울특별시 도봉구 우이동',
 '서울특별시 도봉구 쌍문동',
 '서울특별시 도봉구 방학동',
 '서울특별시 도봉구 창동',
 '서울특별시 도봉구 도봉동',
 '서울특별시 도봉구 창1동',
 '서울특별시 도봉구 창2동',
 '서울특별시 도봉구 창3동',
 '서울특별시 도봉구 도봉1동',
 '서울특별시 도봉구 도봉2동',
 '서울특별시 도봉구 미아1동',
 '서울특별시 도봉구 미아2동',
 '서울특별시 도봉구 미아3동',
 '서울특별시 도봉구 미아4동',
 '서울특별시 도봉구 미아5동',
 '서울특별시 도봉구 미아6동',
 '서울특별시 도봉구 미아7동',
 '서울특별시 도봉구 미아8동',
 '서울특별시 도봉구 번1동',
 '서울특별시 도봉구 번2동',
 '서울특별시 도봉구 수유1동',
 '서울특별시 도봉구 수유2동',
 '서울특별시 도봉구 수유3동',
 '서울특별시 도봉구 수유4동',
 '서울특별시 도봉구 수유5동',
 '서울특별시 도봉구 쌍문1동',
 '서울특별시 도봉구 쌍문2동',
 '서울특별시 도봉구 쌍문3동',
 '서울특별시 도봉구 방학1동',
 '서울특별시 도봉구 방학2동',
 '서울특별시 도봉구 방학3동',
 '서울특별시 노원구',
 '서울특별시 노원구 창동',
 '서울특별시 노원구 월계동',
 '서울특별시 노원구 공릉동',
 '서울특별시 노원구 하계동',
 '서울특별시 노원구 상계동',
 '서울특별시 노원구 중계동',
 '서울특별시 노원구 도봉동',
 '서울특별시 노원구 도봉1동',
 '서울특별시 노원구 도봉2동',
 '서울특별시 노원구 창1동',
 '서울특별시 노원구 창2동',
 '서울특별시 노원구 창3동',
 '서울특별시 노원구 월계1동',
 '서울특별시 노원구 월계2동',
 '서울특별시 노원구 월계3동',
 '서울특별시 노원구 공릉1동',
 '서울특별시 노원구 공릉2동',
 '서울특별시 노원구 상계1동',
 '서울특별시 노원구 상계2동',
 '서울특별시 노원구 상계3동',
 '서울특별시 노원구 상계4동',
 '서울특별시 노원구 상계5동',
 '서울특별시 노원구 상계6동',
 '서울특별시 노원구 상계7동',
 '서울특별시 은평구',
 '서울특별시 은평구 수색동',
 '서울특별시 은평구 녹번동',
 '서울특별시 은평구 불광동',
 '서울특별시 은평구 갈현동',
 '서울특별시 은평구 구산동',
 '서울특별시 은평구 대조동',
 '서울특별시 은평구 응암동',
 '서울특별시 은평구 역촌동',
 '서울특별시 은평구 신사동',
 '서울특별시 은평구 증산동',
 '서울특별시 은평구 진관내동',
 '서울특별시 은평구 구파발동',
 '서울특별시 은평구 진관외동',
 '서울특별시 은평구 진관동',
 '서울특별시 은평구 불광1동',
 '서울특별시 은평구 불광2동',
 '서울특별시 은평구 불광3동',
 '서울특별시 은평구 응암1동',
 '서울특별시 은평구 응암2동',
 '서울특별시 은평구 응암3동',
 '서울특별시 은평구 역촌1동',
 '서울특별시 은평구 역촌2동',
 '서울특별시 은평구 응암4동',
 '서울특별시 서대문구',
 '서울특별시 서대문구 평창동',
 '서울특별시 서대문구 구기동',
 '서울특별시 서대문구 부암동',
 '서울특별시 서대문구 홍지동',
 '서울특별시 서대문구 신영동',
 '서울특별시 서대문구 행촌동',
 '서울특별시 서대문구 송월동',
 '서울특별시 서대문구 홍파동',
 '서울특별시 서대문구 평동',
 '서울특별시 서대문구 교남동',
 '서울특별시 서대문구 교북동',
 '서울특별시 서대문구 서소문동',
 '서울특별시 서대문구 정동',
 '서울특별시 서대문구 순화동',
 '서울특별시 서대문구 의주로2가',
 '서울특별시 서대문구 중림동',
 '서울특별시 서대문구 의주로1가',
 '서울특별시 서대문구 충정로1가',
 '서울특별시 서대문구 노고산동',
 '서울특별시 서대문구 만리동1가',
 '서울특별시 서대문구 만리동2가',
 '서울특별시 서대문구 상암동',
 '서울특별시 서대문구 성산동',
 '서울특별시 서대문구 수색동',
 '서울특별시 서대문구 중동',
 '서울특별시 서대문구 녹번동',
 '서울특별시 서대문구 불광동',
 '서울특별시 서대문구 갈현동',
 '서울특별시 서대문구 역촌동',
 '서울특별시 서대문구 신사동',
 '서울특별시 서대문구 구파발동',
 '서울특별시 서대문구 구산동',
 '서울특별시 서대문구 진관내동',
 '서울특별시 서대문구 진관외동',
 '서울특별시 서대문구 응암동',
 '서울특별시 서대문구 대조동',
 '서울특별시 서대문구 증산동',
 '서울특별시 서대문구 충정로2가',
 '서울특별시 서대문구 충정로3가',
 '서울특별시 서대문구 합동',
 '서울특별시 서대문구 미근동',
 '서울특별시 서대문구 냉천동',
 '서울특별시 서대문구 천연동',
 '서울특별시 서대문구 옥천동',
 '서울특별시 서대문구 영천동',
 '서울특별시 서대문구 현저동',
 '서울특별시 서대문구 북아현동',
 '서울특별시 서대문구 홍제동',
 '서울특별시 서대문구 대현동',
 '서울특별시 서대문구 대신동',
 '서울특별시 서대문구 신촌동',
 '서울특별시 서대문구 봉원동',
 '서울특별시 서대문구 창천동',
 '서울특별시 서대문구 연희동',
 '서울특별시 서대문구 홍은동',
 '서울특별시 서대문구 북가좌동',
 '서울특별시 서대문구 남가좌동',
 '서울특별시 서대문구 충정로동',
 '서울특별시 서대문구 북아현1동',
 '서울특별시 서대문구 북아현2동',
 '서울특별시 서대문구 북아현3동',
 '서울특별시 서대문구 연희1동',
 '서울특별시 서대문구 연희2동',
 '서울특별시 서대문구 연희3동',
 '서울특별시 서대문구 홍제1동',
 '서울특별시 서대문구 홍제2동',
 '서울특별시 서대문구 홍제3동',
 '서울특별시 서대문구 홍제4동',
 '서울특별시 서대문구 홍은1동',
 '서울특별시 서대문구 홍은2동',
 '서울특별시 서대문구 홍은3동',
 '서울특별시 서대문구 남가좌1동',
 '서울특별시 서대문구 남가좌2동',
 '서울특별시 서대문구 북가좌1동',
 '서울특별시 서대문구 북가좌1동',
 '서울특별시 마포구',
 '서울특별시 마포구 연희동',
 '서울특별시 마포구 남가좌동',
 '서울특별시 마포구 수색동',
 '서울특별시 마포구 율도동',
 '서울특별시 마포구 아현동',
 '서울특별시 마포구 공덕동',
 '서울특별시 마포구 신공덕동',
 '서울특별시 마포구 도화동',
 '서울특별시 마포구 용강동',
 '서울특별시 마포구 토정동',
 '서울특별시 마포구 마포동',
 '서울특별시 마포구 대흥동',
 '서울특별시 마포구 염리동',
 '서울특별시 마포구 노고산동',
 '서울특별시 마포구 신수동',
 '서울특별시 마포구 현석동',
 '서울특별시 마포구 구수동',
 '서울특별시 마포구 창전동',
 '서울특별시 마포구 상수동',
 '서울특별시 마포구 하중동',
 '서울특별시 마포구 신정동',
 '서울특별시 마포구 당인동',
 '서울특별시 마포구 하수동',
 '서울특별시 마포구 서교동',
 '서울특별시 마포구 동교동',
 '서울특별시 마포구 합정동',
 '서울특별시 마포구 망원동',
 '서울특별시 마포구 연남동',
 '서울특별시 마포구 성산동',
 '서울특별시 마포구 중동',
 '서울특별시 마포구 상암동',
 '서울특별시 마포구 아현1동',
 '서울특별시 마포구 아현2동',
 '서울특별시 마포구 아현3동',
 '서울특별시 마포구 공덕1동',
 '서울특별시 마포구 공덕2동',
 '서울특별시 마포구 도화1동',
 '서울특별시 마포구 도화2동',
 '서울특별시 마포구 망원1동',
 '서울특별시 마포구 망원2동',
 '서울특별시 마포구 성산1동',
 '서울특별시 마포구 성산2동',
 '서울특별시 양천구',
 '서울특별시 양천구 신정동',
 '서울특별시 양천구 목동',
 '서울특별시 양천구 신월동',
 '서울특별시 양천구 목1동',
 '서울특별시 양천구 목2동',
 '서울특별시 양천구 목3동',
 '서울특별시 양천구 목4동',
 '서울특별시 양천구 목5동',
 '서울특별시 양천구 신월1동',
 '서울특별시 양천구 신월2동',
 '서울특별시 양천구 신월3동',
 '서울특별시 양천구 신월4동',
 '서울특별시 양천구 신월5동',
 '서울특별시 양천구 신월6동',
 '서울특별시 양천구 신정1동',
 '서울특별시 양천구 신정2동',
 '서울특별시 양천구 신정3동',
 '서울특별시 양천구 신정4동',
 '서울특별시 양천구 신정5동',
 '서울특별시 양천구 신정6동',
 '서울특별시 강서구',
 '서울특별시 강서구 신정동',
 '서울특별시 강서구 신월동',
 '서울특별시 강서구 염창동',
 '서울특별시 강서구 등촌동',
 '서울특별시 강서구 화곡동',
 '서울특별시 강서구 가양동',
 '서울특별시 강서구 마곡동',
 '서울특별시 강서구 내발산동',
 '서울특별시 강서구 외발산동',
 '서울특별시 강서구 공항동',
 '서울특별시 강서구 방화동',
 '서울특별시 강서구 개화동',
 '서울특별시 강서구 과해동',
 '서울특별시 강서구 오곡동',
 '서울특별시 강서구 오쇠동',
 '서울특별시 강서구 목동',
 '서울특별시 강서구 등촌1동',
 '서울특별시 강서구 등촌2동',
 '서울특별시 강서구 화곡1동',
 '서울특별시 강서구 화곡2동',
 '서울특별시 강서구 화곡3동',
 '서울특별시 강서구 화곡4동',
 '서울특별시 강서구 화곡5동',
 '서울특별시 강서구 화곡본동',
 '서울특별시 강서구 발산동',
 '서울특별시 강서구 방화1동',
 '서울특별시 강서구 방화2동',
 '서울특별시 구로구',
 '서울특별시 구로구 신도림동',
 '서울특별시 구로구 구로동',
 '서울특별시 구로구 가리봉동',
 '서울특별시 구로구 독산동',
 '서울특별시 구로구 시흥동',
 '서울특별시 구로구 고척동',
 '서울특별시 구로구 개봉동',
 '서울특별시 구로구 오류동',
 '서울특별시 구로구 궁동',
 '서울특별시 구로구 온수동',
 '서울특별시 구로구 천왕동',
 '서울특별시 구로구 항동',
 '서울특별시 구로구 구로1동',
 '서울특별시 구로구 구로2동',
 '서울특별시 구로구 구로3동',
 '서울특별시 구로구 구로4동',
 '서울특별시 구로구 구로5동',
 '서울특별시 구로구 구로6동',
 '서울특별시 구로구 가리봉1동',
 '서울특별시 구로구 가리봉2동',
 '서울특별시 구로구 가리봉3동',
 '서울특별시 구로구 독산1동',
 '서울특별시 구로구 독산2동',
 '서울특별시 구로구 독산3동',
 '서울특별시 구로구 독산4동',
 '서울특별시 구로구 독산본동',
 '서울특별시 구로구 시흥본동',
 '서울특별시 구로구 시흥1동',
 '서울특별시 구로구 시흥2동',
 '서울특별시 구로구 시흥3동',
 '서울특별시 구로구 시흥4동',
 '서울특별시 구로구 시흥5동',
 '서울특별시 구로구 고척1동',
 '서울특별시 구로구 고척2동',
 '서울특별시 구로구 개봉1동',
 '서울특별시 구로구 개봉2동',
 '서울특별시 구로구 개봉3동',
 '서울특별시 구로구 오류1동',
 '서울특별시 구로구 오류2동',
 '서울특별시 구로구 수궁동',
 '서울특별시 금천구',
 '서울특별시 금천구 가산동',
 '서울특별시 금천구 독산동',
 '서울특별시 금천구 시흥동',
 '서울특별시 영등포구',
 '서울특별시 영등포구 독산동',
 '서울특별시 영등포구 염창동',
 '서울특별시 영등포구 목동',
 '서울특별시 영등포구 등촌동',
 '서울특별시 영등포구 화곡동',
 '서울특별시 영등포구 신월동',
 '서울특별시 영등포구 마곡동',
 '서울특별시 영등포구 가양동',
 '서울특별시 영등포구 내발산동',
 '서울특별시 영등포구 외발산동',
 '서울특별시 영등포구 공항동',
 '서울특별시 영등포구 방화동',
 '서울특별시 영등포구 과해동',
 '서울특별시 영등포구 신정동',
 '서울특별시 영등포구 오곡동',
 '서울특별시 영등포구 오쇠동',
 '서울특별시 영등포구 구로동',
 '서울특별시 영등포구 가리봉동',
 '서울특별시 영등포구 시흥동',
 '서울특별시 영등포구 고척동',
 '서울특별시 영등포구 개봉동',
 '서울특별시 영등포구 오류동',
 '서울특별시 영등포구 궁동',
 '서울특별시 영등포구 온수동',
 '서울특별시 영등포구 천왕동',
 '서울특별시 영등포구 항동',
 '서울특별시 영등포구 신도림동',
 '서울특별시 영등포구 개화동',
 '서울특별시 영등포구 반포동',
 '서울특별시 영등포구 잠원동',
 '서울특별시 영등포구 서초동',
 '서울특별시 영등포구 양재동',
 '서울특별시 영등포구 우면동',
 '서울특별시 영등포구 원지동',
 '서울특별시 영등포구 노량진동',
 '서울특별시 영등포구 상도동',
 '서울특별시 영등포구 상도제1동',
 '서울특별시 영등포구 봉천동',
 '서울특별시 영등포구 본동',
 '서울특별시 영등포구 흑석동',
 '서울특별시 영등포구 동작동',
 '서울특별시 영등포구 사당동',
 '서울특별시 영등포구 방배동',
 '서울특별시 영등포구 신림동',
 '서울특별시 영등포구 대방동',
 '서울특별시 영등포구 신대방동',
 '서울특별시 영등포구 양평동',
 '서울특별시 영등포구 영등포동',
 '서울특별시 영등포구 영등포동1가',
 '서울특별시 영등포구 영등포동2가',
 '서울특별시 영등포구 영등포동3가',
 '서울특별시 영등포구 영등포동4가',
 '서울특별시 영등포구 영등포동5가',
 '서울특별시 영등포구 영등포동6가',
 '서울특별시 영등포구 영등포동7가',
 '서울특별시 영등포구 영등포동8가',
 '서울특별시 영등포구 여의도동',
 '서울특별시 영등포구 당산동1가',
 '서울특별시 영등포구 당산동2가',
 '서울특별시 영등포구 당산동3가',
 '서울특별시 영등포구 당산동4가',
 '서울특별시 영등포구 당산동5가',
 '서울특별시 영등포구 당산동6가',
 '서울특별시 영등포구 당산동',
 '서울특별시 영등포구 도림동',
 '서울특별시 영등포구 문래동1가',
 '서울특별시 영등포구 문래동2가',
 '서울특별시 영등포구 문래동3가',
 '서울특별시 영등포구 문래동4가',
 '서울특별시 영등포구 문래동5가',
 '서울특별시 영등포구 문래동6가',
 '서울특별시 영등포구 양평동1가',
 '서울특별시 영등포구 양평동2가',
 '서울특별시 영등포구 양평동3가',
 '서울특별시 영등포구 양평동4가',
 '서울특별시 영등포구 양평동5가',
 '서울특별시 영등포구 양평동6가',
 '서울특별시 영등포구 양화동',
 '서울특별시 영등포구 신길동',
 '서울특별시 영등포구 대림동',
 '서울특별시 영등포구 양평동',
 '서울특별시 영등포구 영등포1동',
 '서울특별시 영등포구 영등포2동',
 '서울특별시 영등포구 영등포3동',
 '서울특별시 영등포구 당산1동',
 '서울특별시 영등포구 당산2동',
 '서울특별시 영등포구 도림1동',
 '서울특별시 영등포구 도림2동',
 '서울특별시 영등포구 문래1동',
 '서울특별시 영등포구 문래2동',
 '서울특별시 영등포구 양평1동',
 '서울특별시 영등포구 양평2동',
 '서울특별시 영등포구 신길1동',
 '서울특별시 영등포구 신길2동',
 '서울특별시 영등포구 신길3동',
 '서울특별시 영등포구 신길4동',
 '서울특별시 영등포구 신길5동',
 '서울특별시 영등포구 신길6동',
 '서울특별시 영등포구 신길7동',
 '서울특별시 영등포구 대림1동',
 '서울특별시 영등포구 대림2동',
 '서울특별시 영등포구 대림3동',
 '서울특별시 동작구',
 '서울특별시 동작구 노량진동',
 '서울특별시 동작구 상도동',
 '서울특별시 동작구 상도1동',
 '서울특별시 동작구 본동',
 '서울특별시 동작구 흑석동',
 '서울특별시 동작구 동작동',
 '서울특별시 동작구 사당동',
 '서울특별시 동작구 대방동',
 '서울특별시 동작구 신대방동',
 '서울특별시 동작구 노량진1동',
 '서울특별시 동작구 노량진2동',
 '서울특별시 동작구 상도2동',
 '서울특별시 동작구 상도3동',
 '서울특별시 동작구 상도4동',
 '서울특별시 동작구 흑석1동',
 '서울특별시 동작구 흑석2동',
 '서울특별시 동작구 흑석3동',
 '서울특별시 동작구 사당1동',
 '서울특별시 동작구 사당2동',
 '서울특별시 동작구 사당3동',
 '서울특별시 동작구 사당4동',
 '서울특별시 동작구 신대방1동',
 '서울특별시 동작구 신대방2동',
 '서울특별시 관악구',
 '서울특별시 관악구 대방동',
 '서울특별시 관악구 신대방동',
 '서울특별시 관악구 노량진동',
 '서울특별시 관악구 상도동',
 '서울특별시 관악구 본동',
 '서울특별시 관악구 흑석동',
 '서울특별시 관악구 동작동',
 '서울특별시 관악구 사당동',
 '서울특별시 관악구 방배동',
 '서울특별시 관악구 상도제1동',
 '서울특별시 관악구 봉천동',
 '서울특별시 관악구 신림동',
 '서울특별시 관악구 남현동',
 '서울특별시 관악구 봉천본동',
 '서울특별시 관악구 봉천1동',
 '서울특별시 관악구 봉천2동',
 '서울특별시 관악구 봉천3동',
 '서울특별시 관악구 봉천4동',
 '서울특별시 관악구 봉천5동',
 '서울특별시 관악구 봉천6동',
 '서울특별시 관악구 봉천7동',
 '서울특별시 관악구 봉천8동',
 '서울특별시 관악구 봉천9동',
 '서울특별시 관악구 봉천10동',
 '서울특별시 관악구 봉천11동',
 '서울특별시 관악구 신림본동',
 '서울특별시 관악구 신림1동',
 '서울특별시 관악구 신림2동',
 '서울특별시 관악구 신림3동',
 '서울특별시 관악구 신림4동',
 '서울특별시 관악구 신림5동',
 '서울특별시 관악구 신림6동',
 '서울특별시 관악구 신림7동',
 '서울특별시 관악구 신림8동',
 '서울특별시 관악구 신림9동',
 '서울특별시 관악구 신림10동',
 '서울특별시 관악구 신림11동',
 '서울특별시 서초구',
 '서울특별시 서초구 개포동',
 '서울특별시 서초구 방배동',
 '서울특별시 서초구 양재동',
 '서울특별시 서초구 우면동',
 '서울특별시 서초구 원지동',
 '서울특별시 서초구 도곡동',
 '서울특별시 서초구 잠원동',
 '서울특별시 서초구 반포동',
 '서울특별시 서초구 서초동',
 '서울특별시 서초구 내곡동',
 '서울특별시 서초구 염곡동',
 '서울특별시 서초구 신원동',
 '서울특별시 서초구 역삼동',
 '서울특별시 서초구 신사동',
 '서울특별시 서초구 서초1동',
 '서울특별시 서초구 서초2동',
 '서울특별시 서초구 서초3동',
 '서울특별시 서초구 반포본동',
 '서울특별시 서초구 반포1동',
 '서울특별시 서초구 반포2동',
 '서울특별시 서초구 반포3동',
 '서울특별시 서초구 방배본동',
 '서울특별시 서초구 방배1동',
 '서울특별시 서초구 방배2동',
 ...]

In [186]:
name_list[1][-1]

'구'

In [190]:
name_list[1].split()[1]

'종로구'

In [201]:
goo = []
for name in name_list:
    if name[-1] == '구':
        name_split = name.split(' ')
        goo.append(name_split[1])

In [203]:
goo

['종로구',
 '중구',
 '용산구',
 '성동구',
 '광진구',
 '동대문구',
 '중랑구',
 '성북구',
 '강북구',
 '도봉구',
 '노원구',
 '은평구',
 '서대문구',
 '마포구',
 '양천구',
 '강서구',
 '구로구',
 '금천구',
 '영등포구',
 '동작구',
 '관악구',
 '서초구',
 '강남구',
 '송파구',
 '강동구']

In [191]:
#2번째 방법
df = lawd_cd_seoule

In [195]:
df['name'].str.split().str[1].dropna().unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

In [197]:
seoul_go = df[df['name'].str.contains('서울특별시')]['name'].str.split().str[1].dropna().unique()

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구',
       '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구'], dtype=object)

- **(필수) 특정월에 서울시 전체 구의 데이터를 한번에 가져오기(입력값: 연월 202402)**

In [208]:
base = "202510"
year = int(base[:4])
month = int(base[4:])
result = []

for i in range(12):
    result.append(f"{year}{month:02d}")

340282366920938463463374607431768211456

In [209]:
import requests

url = 'http://apis.data.go.kr/1360000/MidFcstInfoService/getMidFcst'
params ={'serviceKey' : '서비스키', 'pageNo' : '1', 'numOfRows' : '10', 'dataType' : 'XML', 'stnId' : '108', 'tmFc' : '201310170600' }

response = requests.get(url, params=params)
print(response.content)

b'Unauthorized\n'