In [166]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [167]:
df = pd.DataFrame({
    '이름' : ['김', '이', '박'],
    '나이' : [28, 27, 30],
    '지역' : ['서울' , '부산', '대구']
})

In [168]:
df

  이름  나이  지역
0  김  28  서울
1  이  27  부산
2  박  30  대구

In [169]:
df.loc[df['나이'] >= 28, '상태'] = '일반인'

In [170]:
df.loc[df['나이'] <= 28, '상태'] = '학생'

In [171]:
import folium 
import json

In [172]:
people2026 = pd.read_excel('C:/Users/USER/Desktop/연습데이터/2024년_인구데이터.xlsx', skiprows=1)

C:\Users\USER\anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [173]:
people2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 741 entries, 0 to 740
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   행정구역(시군구)별(1)  18 non-null     object
 1   행정구역(시군구)별(2)  247 non-null    object
 2   성별(1)          741 non-null    object
 3   계              741 non-null    float64
 4   20 - 24세       741 non-null    float64
 5   25 - 29세       741 non-null    float64
 6   30 - 34세       741 non-null    float64
 7   35 - 39세       741 non-null    float64
 8   40 - 44세       741 non-null    float64
 9   45 - 49세       741 non-null    float64
 10  50 - 54세       741 non-null    float64
 11  55 - 59세       741 non-null    float64
 12  60 - 64세       741 non-null    float64
 13  65 - 69세       741 non-null    float64
 14  70 - 74세       741 non-null    float64
 15  75 - 79세       741 non-null    float64
 16  80세 이상         741 non-null    float64
 17  80 - 84세       741 non-null    float64
 18  85세 이상         741 non-null    float64
 19  85 - 89세       741 non-null    float64
 20  90 - 94세       741 non-null    float64
 21  95 - 99세       741 non-null    float64
 22  100세 이상        741 non-null    float64
dtypes: float64(20), object(3)
memory usage: 133.3+ KB

In [174]:
people2026_1 = people2026

In [175]:
people2026_1.head()

,행정구역(시군구)별(1),행정구역(시군구)별(2),성별(1),계,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,...,65 - 69세,70 - 74세,75 - 79세,80세 이상,80 - 84세,85세 이상,85 - 89세,90 - 94세,95 - 99세,100세 이상
0,전국,소계,계,51037252.5,2715177.5,3345302.5,3426128.0,3145432.0,3942230.0,3830094.0,...,3502182.0,2324531.5,1737959.0,2390803.5,1332256.5,1058547.0,737135.5,257365.5,55929.0,8117.0
1,NaN,NaN,남자,25400503.0,1410684.5,1749087.0,1802576.0,1620174.0,2005710.0,1942249.5,...,1703153.0,1092697.0,776189.5,834606.0,521935.0,312671.0,238765.5,62485.0,10087.0,1333.5
2,NaN,NaN,여자,25636749.5,1304493.0,1596215.5,1623552.0,1525258.0,1936520.0,1887844.5,...,1799029.0,1231834.5,961769.5,1556197.5,810321.5,745876.0,498370.0,194880.5,45842.0,6783.5
3,서울특별시,소계,계,9288119.0,540958.0,786238.0,783490.5,643327.5,716405.0,671810.5,...,615615.5,423867.0,327072.5,393408.0,230572.0,162836.0,114558.5,38085.5,8865.0,1327.0
4,NaN,NaN,남자,4486066.5,253312.5,373857.0,393071.0,320819.5,355381.0,330694.0,...,286904.5,194370.5,145187.0,152627.5,97849.0,54778.5,41851.5,10696.5,1948.0,282.5

In [176]:
people2026_1 = people2026_1.rename(columns={'행정구역(시군구)별(1)': '광역시도', '행정구역(시군구)별(2)': '시도',
                                   '성별(1)':'구분', '계':'인구수', '100세 이상':'100+'})

In [177]:
people2026_1.head()

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,...,65 - 69세,70 - 74세,75 - 79세,80세 이상,80 - 84세,85세 이상,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,계,51037252.5,2715177.5,3345302.5,3426128.0,3145432.0,3942230.0,3830094.0,...,3502182.0,2324531.5,1737959.0,2390803.5,1332256.5,1058547.0,737135.5,257365.5,55929.0,8117.0
1,NaN,NaN,남자,25400503.0,1410684.5,1749087.0,1802576.0,1620174.0,2005710.0,1942249.5,...,1703153.0,1092697.0,776189.5,834606.0,521935.0,312671.0,238765.5,62485.0,10087.0,1333.5
2,NaN,NaN,여자,25636749.5,1304493.0,1596215.5,1623552.0,1525258.0,1936520.0,1887844.5,...,1799029.0,1231834.5,961769.5,1556197.5,810321.5,745876.0,498370.0,194880.5,45842.0,6783.5
3,서울특별시,소계,계,9288119.0,540958.0,786238.0,783490.5,643327.5,716405.0,671810.5,...,615615.5,423867.0,327072.5,393408.0,230572.0,162836.0,114558.5,38085.5,8865.0,1327.0
4,NaN,NaN,남자,4486066.5,253312.5,373857.0,393071.0,320819.5,355381.0,330694.0,...,286904.5,194370.5,145187.0,152627.5,97849.0,54778.5,41851.5,10696.5,1948.0,282.5

In [178]:
people2026_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 741 entries, 0 to 740
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   광역시도      18 non-null     object
 1   시도        247 non-null    object
 2   구분        741 non-null    object
 3   인구수       741 non-null    float64
 4   20 - 24세  741 non-null    float64
 5   25 - 29세  741 non-null    float64
 6   30 - 34세  741 non-null    float64
 7   35 - 39세  741 non-null    float64
 8   40 - 44세  741 non-null    float64
 9   45 - 49세  741 non-null    float64
 10  50 - 54세  741 non-null    float64
 11  55 - 59세  741 non-null    float64
 12  60 - 64세  741 non-null    float64
 13  65 - 69세  741 non-null    float64
 14  70 - 74세  741 non-null    float64
 15  75 - 79세  741 non-null    float64
 16  80세 이상    741 non-null    float64
 17  80 - 84세  741 non-null    float64
 18  85세 이상    741 non-null    float64
 19  85 - 89세  741 non-null    float64
 20  90 - 94세  741 non-null    float64
 21  95 - 99세  741 non-null    float64
 22  100+      741 non-null    float64
dtypes: float64(20), object(3)
memory usage: 133.3+ KB

In [179]:
people2026_1.loc[people2026_1['구분'] == '계', '구분'] = '합계'

In [180]:
people2026_1.head()

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,...,65 - 69세,70 - 74세,75 - 79세,80세 이상,80 - 84세,85세 이상,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,합계,51037252.5,2715177.5,3345302.5,3426128.0,3145432.0,3942230.0,3830094.0,...,3502182.0,2324531.5,1737959.0,2390803.5,1332256.5,1058547.0,737135.5,257365.5,55929.0,8117.0
1,NaN,NaN,남자,25400503.0,1410684.5,1749087.0,1802576.0,1620174.0,2005710.0,1942249.5,...,1703153.0,1092697.0,776189.5,834606.0,521935.0,312671.0,238765.5,62485.0,10087.0,1333.5
2,NaN,NaN,여자,25636749.5,1304493.0,1596215.5,1623552.0,1525258.0,1936520.0,1887844.5,...,1799029.0,1231834.5,961769.5,1556197.5,810321.5,745876.0,498370.0,194880.5,45842.0,6783.5
3,서울특별시,소계,합계,9288119.0,540958.0,786238.0,783490.5,643327.5,716405.0,671810.5,...,615615.5,423867.0,327072.5,393408.0,230572.0,162836.0,114558.5,38085.5,8865.0,1327.0
4,NaN,NaN,남자,4486066.5,253312.5,373857.0,393071.0,320819.5,355381.0,330694.0,...,286904.5,194370.5,145187.0,152627.5,97849.0,54778.5,41851.5,10696.5,1948.0,282.5

In [181]:
people2026_1.fillna(method='ffill', inplace = True)

In [182]:
people2026_1.head(7)

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,...,65 - 69세,70 - 74세,75 - 79세,80세 이상,80 - 84세,85세 이상,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,합계,51037252.5,2715177.5,3345302.5,3426128.0,3145432.0,3942230.0,3830094.0,...,3502182.0,2324531.5,1737959.0,2390803.5,1332256.5,1058547.0,737135.5,257365.5,55929.0,8117.0
1,전국,소계,남자,25400503.0,1410684.5,1749087.0,1802576.0,1620174.0,2005710.0,1942249.5,...,1703153.0,1092697.0,776189.5,834606.0,521935.0,312671.0,238765.5,62485.0,10087.0,1333.5
2,전국,소계,여자,25636749.5,1304493.0,1596215.5,1623552.0,1525258.0,1936520.0,1887844.5,...,1799029.0,1231834.5,961769.5,1556197.5,810321.5,745876.0,498370.0,194880.5,45842.0,6783.5
3,서울특별시,소계,합계,9288119.0,540958.0,786238.0,783490.5,643327.5,716405.0,671810.5,...,615615.5,423867.0,327072.5,393408.0,230572.0,162836.0,114558.5,38085.5,8865.0,1327.0
4,서울특별시,소계,남자,4486066.5,253312.5,373857.0,393071.0,320819.5,355381.0,330694.0,...,286904.5,194370.5,145187.0,152627.5,97849.0,54778.5,41851.5,10696.5,1948.0,282.5
5,서울특별시,소계,여자,4802052.5,287645.5,412381.0,390419.5,322508.0,361024.0,341116.5,...,328711.0,229496.5,181885.5,240780.5,132723.0,108057.5,72707.0,27389.0,6917.0,1044.5
6,서울특별시,종로구,합계,137094.5,8827.0,12277.0,11024.0,8350.5,9439.0,9142.5,...,9371.0,6246.5,5272.5,7712.0,4291.0,3421.0,2377.5,803.5,205.0,35.0

In [183]:
people2026_1['20-39세'] = people2026_1['20 - 24세'] + people2026_1['25 - 29세'] + \
                          people2026_1['30 - 34세'] + people2026_1['35 - 39세']

In [184]:
people2026_1['65세이상'] = people2026_1['65 - 69세'] + people2026_1['70 - 74세'] + \
                          people2026_1['75 - 79세'] + people2026_1['80 - 84세'] + \
                          people2026_1['85 - 89세'] + people2026_1['90 - 94세'] + people2026_1['100+']

In [185]:
people2026_1.head()

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,40 - 44세,45 - 49세,...,75 - 79세,80세 이상,80 - 84세,85세 이상,85 - 89세,90 - 94세,95 - 99세,100+,20-39세,65세이상
0,전국,소계,합계,51037252.5,2715177.5,3345302.5,3426128.0,3145432.0,3942230.0,3830094.0,...,1737959.0,2390803.5,1332256.5,1058547.0,737135.5,257365.5,55929.0,8117.0,12632040.0,9899547.0
1,전국,소계,남자,25400503.0,1410684.5,1749087.0,1802576.0,1620174.0,2005710.0,1942249.5,...,776189.5,834606.0,521935.0,312671.0,238765.5,62485.0,10087.0,1333.5,6582521.5,4396558.5
2,전국,소계,여자,25636749.5,1304493.0,1596215.5,1623552.0,1525258.0,1936520.0,1887844.5,...,961769.5,1556197.5,810321.5,745876.0,498370.0,194880.5,45842.0,6783.5,6049518.5,5502988.5
3,서울특별시,소계,합계,9288119.0,540958.0,786238.0,783490.5,643327.5,716405.0,671810.5,...,327072.5,393408.0,230572.0,162836.0,114558.5,38085.5,8865.0,1327.0,2754014.0,1751098.0
4,서울특별시,소계,남자,4486066.5,253312.5,373857.0,393071.0,320819.5,355381.0,330694.0,...,145187.0,152627.5,97849.0,54778.5,41851.5,10696.5,1948.0,282.5,1341060.0,777141.5

In [186]:
people2026_1.columns

Index(['광역시도', '시도', '구분', '인구수', '20 - 24세', '25 - 29세', '30 - 34세',
       '35 - 39세', '40 - 44세', '45 - 49세', '50 - 54세', '55 - 59세', '60 - 64세',
       '65 - 69세', '70 - 74세', '75 - 79세', '80세 이상', '80 - 84세', '85세 이상',
       '85 - 89세', '90 - 94세', '95 - 99세', '100+', '20-39세', '65세이상'],
      dtype='object')

In [187]:
people2026_1.drop(['40 - 44세', '45 - 49세', '50 - 54세',
                   '55 - 59세', '60 - 64세', '80세 이상', '85세 이상'], axis=1, inplace=True)

In [188]:
people2026_1.head()

,광역시도,시도,구분,인구수,20 - 24세,25 - 29세,30 - 34세,35 - 39세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+,20-39세,65세이상
0,전국,소계,합계,51037252.5,2715177.5,3345302.5,3426128.0,3145432.0,3502182.0,2324531.5,1737959.0,1332256.5,737135.5,257365.5,55929.0,8117.0,12632040.0,9899547.0
1,전국,소계,남자,25400503.0,1410684.5,1749087.0,1802576.0,1620174.0,1703153.0,1092697.0,776189.5,521935.0,238765.5,62485.0,10087.0,1333.5,6582521.5,4396558.5
2,전국,소계,여자,25636749.5,1304493.0,1596215.5,1623552.0,1525258.0,1799029.0,1231834.5,961769.5,810321.5,498370.0,194880.5,45842.0,6783.5,6049518.5,5502988.5
3,서울특별시,소계,합계,9288119.0,540958.0,786238.0,783490.5,643327.5,615615.5,423867.0,327072.5,230572.0,114558.5,38085.5,8865.0,1327.0,2754014.0,1751098.0
4,서울특별시,소계,남자,4486066.5,253312.5,373857.0,393071.0,320819.5,286904.5,194370.5,145187.0,97849.0,41851.5,10696.5,1948.0,282.5,1341060.0,777141.5

In [189]:
people2026_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 741 entries, 0 to 740
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   광역시도      741 non-null    object
 1   시도        741 non-null    object
 2   구분        741 non-null    object
 3   인구수       741 non-null    float64
 4   20 - 24세  741 non-null    float64
 5   25 - 29세  741 non-null    float64
 6   30 - 34세  741 non-null    float64
 7   35 - 39세  741 non-null    float64
 8   65 - 69세  741 non-null    float64
 9   70 - 74세  741 non-null    float64
 10  75 - 79세  741 non-null    float64
 11  80 - 84세  741 non-null    float64
 12  85 - 89세  741 non-null    float64
 13  90 - 94세  741 non-null    float64
 14  95 - 99세  741 non-null    float64
 15  100+      741 non-null    float64
 16  20-39세    741 non-null    float64
 17  65세이상     741 non-null    float64
dtypes: float64(15), object(3)
memory usage: 104.3+ KB

In [190]:
popl = pd.pivot_table(people2026_1, index=['광역시도', '시도'], columns='구분',
                      values=['인구수', '20-39세', '65세이상'])

In [191]:
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', '{:,.0f}'.format)

In [192]:
popl

                   20-39세                          65세이상                      \
구분                     남자        여자         합계        남자        여자        합계
광역시도    시도
강원특별자치도 강릉시        22,929    19,342     42,271    22,833    29,660    52,494
        고성군         2,829     1,955      4,784     3,912     4,938     8,850
        동해시         9,370     7,067     16,438     9,356    11,854    21,210
        삼척시         6,306     5,004     11,310     7,976    10,248    18,224
        소계        173,762   143,714    317,476   166,736   205,557   372,294
        속초시         9,253     7,392     16,646     8,208    10,547    18,756
        양구군         2,773     1,816      4,588     2,462     2,878     5,341
        양양군         2,372     1,710      4,082     4,306     5,145     9,452
        영월군         2,790     2,216      5,006     5,971     6,843    12,814
        원주시        45,410    41,556     86,966    29,436    36,646    66,082
        인제군         4,861     2,767      7,628     3,730     4,004     7,734
        정선군         2,568     1,880      4,448     5,243     6,131    11,374
        철원군         5,140     3,384      8,524     4,916     6,257    11,173
        춘천시        37,462    33,480     70,942    25,904    33,468    59,372
        태백시         3,226     2,478      5,704     4,993     6,494    11,488
        평창군         3,277     2,343      5,620     6,520     7,214    13,734
        홍천군         6,378     4,658     11,037    10,286    11,385    21,672
        화천군         3,442     1,990      5,432     2,872     3,328     6,200
        횡성군         3,374     2,675      6,050     7,810     8,516    16,327
경기도     가평군         6,238     4,828     11,066     9,072    10,018    19,089
        고양시       137,950   136,549    274,500    78,028    98,388   176,416
        과천시        10,938    11,076     22,014     5,532     6,545    12,076
        광명시        35,494    33,682     69,176    20,994    26,780    47,774
        광주시        49,094    44,172     93,266    31,118    34,924    66,042
        구리시        23,859    23,034     46,893    14,448    17,356    31,805
        군포시        35,642    32,011     67,654    19,968    24,598    44,566
        김포시        57,186    56,922    114,108    33,364    40,032    73,396
        남양주시       83,898    81,175    165,074    55,790    68,714   124,504
        동두천시        9,627     8,254     17,880     9,330    12,306    21,636
        부천시       103,410    97,530    200,940    62,544    75,437   137,981
        성남시       127,006   120,576    247,583    70,120    84,999   155,119
        소계      1,850,787 1,685,019  3,535,806   983,155 1,190,222 2,173,377
        수원시       187,795   169,525    357,320    71,842    89,354   161,196
        시흥시        74,522    63,493    138,016    28,630    33,228    61,858
        안산시        93,336    79,502    172,838    41,133    48,714    89,848
        안성시        24,472    19,778     44,250    17,749    21,411    39,160
        안양시        76,379    71,380    147,758    41,967    50,832    92,799
        양주시        34,914    31,986     66,900    21,836    26,094    47,930
        양평군        10,827     9,356     20,182    17,849    19,847    37,696
        여주시        11,991    10,232     22,224    13,794    15,650    29,443
        연천군         5,054     3,190      8,244     5,950     7,062    13,012
        오산시        35,992    29,382     65,374    12,518    15,548    28,066
        용인시       136,404   129,015    265,420    75,418    93,382   168,800
        의왕시        21,566    20,042     41,609    12,454    14,474    26,928
        의정부시       59,806    58,008    117,814    36,686    47,106    83,791
        이천시        32,926    25,654     58,579    17,566    20,232    37,798
        파주시        66,701    59,350    126,050    35,520    44,534    80,054
        평택시        95,338    74,042    169,380    35,443    43,980    79,424
        포천시        16,522    12,606     29,128    17,060    18,683    35,743
        하남시        42,656    43,466     86,121    22,744    25,976    48,720
        화성시       143,243   125,205    268,448    46,689    54,016   100,706
경상남도    거제시        24,376    20,451     44,826    16,376    18,344    34,720
        거창군         5,244     4,110      9,354     7,732    10,910    18,642
        고성군         3,405     2,486      5,892     7,597     9,914    17,511
        김해시        65,372    56,232    121,604    34,544    42,568    77,112
        남해군         2,680     1,860      4,540     6,920     9,836    16,756
        밀양시         8,437     6,572     15,008    14,832    19,314    34,146
        사천시        11,526     8,231     19,757    11,514    15,874    27,388
        산청군         2,027     1,570      3,597     6,003     7,839    13,842
        소계        360,670   299,752    660,422   300,373   381,473   681,846
        양산시        41,378    37,314     78,692    27,424    34,109    61,532
        의령군         1,648     1,255      2,902     4,404     6,054    10,458
        진주시        42,619    36,513     79,132    29,146    39,102    68,248
        창녕군         4,144     2,942      7,086     8,959    11,898    20,858
        창원시       125,328   102,336    227,664    83,597   101,314   184,910
        통영시        10,200     8,641     18,842    12,982    16,366    29,348
        하동군         2,612     1,929      4,542     7,140     9,316    16,456
        함안군         4,792     3,574      8,366     8,056    10,052    18,108
        함양군         2,447     1,942      4,388     5,766     8,206    13,972
        합천군         2,434     1,794      4,228     7,380    10,458    17,839
경상북도    경산시        36,029    29,724     65,752    23,336    29,832    53,168
        경주시        24,844    20,106     44,950    28,348    36,964    65,312
        고령군         2,182     1,661      3,842     4,970     6,072    11,042
        구미시        59,394    46,905    106,298    22,632    27,546    50,178
        김천시        13,972    11,469     25,441    15,677    20,638    36,314
        문경시         5,476     4,503      9,979     9,933    13,572    23,506
        봉화군         1,732     1,196      2,928     5,544     6,718    12,263
        상주시         7,244     5,692     12,937    13,896    18,986    32,882
        성주군         3,144     2,203      5,346     7,222     8,354    15,576
        소계        278,172   219,806    497,978   281,030   358,758   639,789
        안동시        15,676    13,466     29,142    18,425    24,316    42,742
        영덕군         2,095     1,648      3,742     5,730     8,478    14,208
        영양군           950       744      1,694     2,746     3,736     6,481
        영주시         9,122     7,089     16,211    13,304    17,460    30,764
        영천시         9,320     6,944     16,264    14,292    17,898    32,189
        예천군         4,599     4,003      8,602     7,744    10,154    17,898
        울릉군         1,004       574      1,578     1,244     1,403     2,647
        울진군         4,433     3,158      7,591     6,109     8,492    14,601
        의성군         2,924     2,196      5,120     9,835    12,882    22,718
        청도군         2,432     1,896      4,328     7,780     9,718    17,498
        청송군         1,688     1,088      2,776     4,448     5,672    10,120
        칠곡군        11,958     9,008     20,966     9,452    11,692    21,145
        포항시        57,956    44,536    102,492    48,364    58,173   106,537
광주광역시   광산구        54,470    48,832    103,303    19,817    25,748    45,565
        남구         23,634    23,117     46,750    18,520    24,685    43,206
        동구         14,731    14,079     28,810    10,707    13,658    24,364
        북구         56,238    51,242    107,480    33,247    43,170    76,417
        서구         37,514    35,386     72,901    21,220    27,901    49,121
        소계        186,588   172,656    359,244   103,512   135,162   238,673
대구광역시   군위군         1,334       888      2,223     4,770     5,630    10,400
        남구         17,114    16,454     33,568    15,329    21,528    36,858
        달서구        66,066    58,546    124,612    42,394    54,175    96,570
        달성군        32,922    27,705     60,627    18,638    22,745    41,382
        동구         42,506    37,908     80,415    33,440    44,888    78,328
        북구         55,317    47,436    102,754    32,708    42,766    75,475
        서구         19,442    15,742     35,184    18,570    25,245    43,816
        소계        293,942   261,108    555,050   205,889   270,812   476,700
        수성구        45,138    41,776     86,914    32,879    43,616    76,496
        중구         14,104    14,650     28,754     7,160    10,218    17,378
대전광역시   대덕구        22,292    17,972     40,263    15,188    18,676    33,864
        동구         28,125    24,512     52,637    21,378    27,122    48,499
        서구         66,192    63,324    129,516    32,547    40,462    73,010
        소계        202,197   182,430    384,626   111,469   138,638   250,106
        유성구        59,375    51,622    110,997    19,908    23,460    43,367
        중구         26,214    25,000     51,213    22,450    28,918    51,368
부산광역시   강서구        17,574    16,058     33,632     9,856    10,790    20,646
        금정구        26,311    22,612     48,924    24,015    30,757    54,772
        기장군        19,328    17,976     37,304    14,444    18,942    33,385
        남구         30,533    28,116     58,648    25,946    33,904    59,849
        동구         10,042     9,865     19,906    10,666    14,501    25,166
        동래구        30,188    29,518     59,706    25,878    32,988    58,866
        부산진구       48,669    50,455     99,124    34,943    45,577    80,520
        북구         32,188    28,651     60,840    27,354    33,229    60,584
        사상구        25,499    22,212     47,712    21,282    25,606    46,888
        사하구        34,709    29,980     64,688    31,489    38,888    70,377
        서구         10,910    11,166     22,076    12,620    16,958    29,578
        소계        388,220   367,166    755,386   332,443   424,992   757,435
        수영구        21,802    22,981     44,783    18,298    24,574    42,872
        연제구        24,732    24,883     49,614    20,692    26,628    47,321
        영도구        10,196     8,558     18,754    14,649    19,270    33,920
        중구          4,728     4,678      9,407     5,093     6,778    11,870
        해운대구       40,810    39,456     80,266    35,217    45,604    80,820
서울특별시   강남구        68,355    77,186    145,542    39,038    47,853    86,890
        강동구        61,810    64,816    126,626    38,952    46,354    85,306
        강북구        35,722    35,928     71,650    29,851    39,365    69,216
        강서구        82,616    90,537    173,153    45,668    57,734   103,403
        관악구       100,644    93,592    194,236    38,050    47,608    85,658
        광진구        54,063    58,510    112,573    25,632    31,550    57,181
        구로구        54,823    55,476    110,299    35,824    43,632    79,456
        금천구        37,406    34,867     72,272    20,806    24,576    45,382
        노원구        63,430    62,315    125,746    41,516    55,935    97,452
        도봉구        37,196    36,508     73,704    31,961    39,532    71,493
        동대문구       51,878    53,678    105,556    30,059    37,289    67,348
        동작구        60,801    61,998    122,800    30,790    39,748    70,539
        마포구        55,360    66,168    121,527    24,272    33,360    57,632
        서대문구       43,824    48,139     91,964    24,794    33,064    57,858
        서초구        49,522    56,179    105,702    29,778    36,016    65,795
        성동구        41,665    43,984     85,649    21,880    27,602    49,482
        성북구        57,870    61,756    119,626    34,986    45,824    80,810
        소계      1,341,060 1,412,954  2,754,014   777,142   973,956 1,751,098
        송파구        88,916    98,442    187,358    50,552    59,209   109,762
        양천구        51,785    51,784    103,570    34,802    42,528    77,329
        영등포구       61,386    66,128    127,514    30,095    36,201    66,296
        용산구        31,283    34,187     65,470    16,673    21,350    38,022
        은평구        60,238    66,107    126,346    40,812    53,810    94,622
        종로구        19,606    20,873     40,478    12,827    15,570    28,397
        중구         18,226    19,942     38,169    11,262    14,145    25,406
        중랑구        52,635    53,852    106,487    36,262    44,103    80,365
세종특별자치시 세종특별자치시    48,086    48,284     96,370    19,675    23,830    43,506
        소계         48,086    48,284     96,370    19,675    23,830    43,506
울산광역시   남구         43,246    34,600     77,846    22,680    26,168    48,848
        동구         18,834    14,710     33,544    12,663    13,595    26,258
        북구         29,486    23,234     52,720    11,406    12,862    24,268
        소계        142,497   113,300    255,796    84,302    96,901   181,204
        울주군        25,740    20,269     46,008    19,236    22,070    41,306
        중구         25,190    20,488     45,678    18,318    22,206    40,525
인천광역시   강화군         5,076     4,192      9,269    12,092    14,010    26,102
        계양구        37,512    33,666     71,179    22,186    26,444    48,630
        남동구        62,032    56,987    119,018    38,680    48,979    87,660
        동구          6,570     5,734     12,304     6,643     8,741    15,384
        미추홀구       56,800    50,027    106,827    35,702    45,684    81,386
        부평구        67,972    64,198    132,170    39,238    50,064    89,302
        서구         86,169    82,802    168,971    36,836    43,448    80,284
        소계        400,948   370,962    771,910   228,801   281,180   509,980
        연수구        51,477    49,998    101,474    22,749    26,564    49,313
        옹진군         2,844     1,262      4,107     3,157     3,352     6,509
        중구         24,495    22,096     46,591    11,516    13,894    25,411
전국      소계      6,582,522 6,049,518 12,632,040 4,396,558 5,502,988 9,899,547
전라남도    강진군         2,424     2,004      4,428     5,210     7,266    12,476
        고흥군         3,650     2,832      6,482    11,244    15,746    26,990
        곡성군         1,893     1,588      3,481     4,470     6,052    10,521
        광양시        20,526    15,865     36,390    11,123    13,071    24,194
        구례군         1,550     1,326      2,876     3,845     5,430     9,274
        나주시        13,026    12,088     25,115    12,278    16,190    28,468
        담양군         3,792     3,136      6,929     6,782     8,706    15,488
        목포시        23,694    21,006     44,701    18,641    24,568    43,210
        무안군        10,194     9,424     19,618     8,253    10,891    19,144
        보성군         2,412     1,877      4,288     6,586     9,332    15,918
        소계        186,192   156,024    342,216   205,052   269,694   474,746
        순천시        34,508    30,192     64,700    22,820    28,735    51,554
        신안군         2,826     1,794      4,620     6,704     8,293    14,996
        여수시        31,596    25,235     56,832    27,722    34,360    62,082
        영광군         4,812     4,194      9,006     6,893     9,460    16,352
        영암군         4,825     3,648      8,474     6,522     8,821    15,344
        완도군         3,403     2,624      6,027     7,133     9,668    16,801
        장성군         3,766     2,853      6,618     6,190     7,993    14,183
        장흥군         2,580     2,101      4,682     5,420     7,818    13,239
        진도군         2,202     1,782      3,984     4,428     6,204    10,632
        함평군         2,163     1,658      3,822     5,142     7,094    12,236
        해남군         4,832     3,744      8,576     9,867    13,466    23,334
        화순군         5,519     5,050     10,568     7,778    10,530    18,307
전북특별자치도 고창군         3,651     2,930      6,580     8,350    11,473    19,824
        군산시        28,268    23,702     51,971    25,745    32,024    57,769
        김제시         7,092     5,897     12,990    11,874    16,084    27,958
        남원시         6,300     5,398     11,698    10,258    13,964    24,222
        무주군         1,640     1,319      2,959     3,690     4,881     8,572
        부안군         3,669     2,861      6,530     7,817    10,438    18,256
        소계        190,570   167,273    357,842   185,930   241,376   427,307
        순창군         1,920     1,682      3,602     4,110     5,747     9,858
        완주군        10,658     9,150     19,808    11,140    13,348    24,488
        익산시        30,630    26,374     57,004    27,540    35,258    62,798
        임실군         1,860     1,438      3,298     4,594     5,779    10,374
        장수군         1,382     1,122      2,504     3,486     4,590     8,076
        전주시        82,722    76,492    159,214    49,463    64,238   113,702
        정읍시         9,190     7,538     16,728    13,560    18,372    31,932
        진안군         1,588     1,369      2,956     4,302     5,178     9,480
제주특별자치도 서귀포시       17,982    16,348     34,331    17,821    22,590    40,410
        소계         77,607    71,756    149,364    53,840    68,537   122,376
        제주시        59,624    55,408    115,032    36,018    45,948    81,966
충청남도    계룡시         5,502     4,710     10,212     2,990     3,726     6,716
        공주시        10,120     8,902     19,022    13,828    17,014    30,842
        금산군         3,552     2,863      6,416     7,872     9,783    17,654
        논산시        10,152     8,338     18,490    14,774    18,938    33,712
        당진시        20,520    14,668     35,188    16,336    19,416    35,753
        보령시         8,756     6,776     15,532    12,628    16,119    28,747
        부여군         4,307     3,370      7,676    10,617    13,398    24,014
        서산시        21,946    15,274     37,219    16,846    20,522    37,368
        서천군         3,376     2,565      5,942     8,637    11,270    19,908
        소계        260,106   213,178    473,284   205,538   255,380   460,918
        아산시        48,872    40,804     89,675    22,653    28,220    50,872
        예산군         6,728     5,437     12,165    11,945    14,980    26,926
        천안시        99,260    85,915    185,175    39,896    48,500    88,396
        청양군         2,414     1,784      4,198     5,293     6,531    11,824
        태안군         4,755     3,432      8,187     9,758    12,128    21,886
        홍성군         9,846     8,342     18,188    11,464    14,834    26,298
충청북도    괴산군         2,395     1,716      4,112     6,878     7,768    14,646
        단양군         1,941     1,457      3,398     4,700     5,517    10,218
        보은군         2,097     1,578      3,676     5,444     6,793    12,238
        소계        201,118   164,137    365,256   151,672   186,521   338,192
        영동군         3,234     2,546      5,779     7,296     8,972    16,267
        옥천군         3,767     3,043      6,810     7,640     9,154    16,794
        음성군         9,750     7,160     16,910    10,800    12,374    23,174
        제천시        13,833    11,258     25,092    15,511    18,792    34,302
        증평군         4,911     3,690      8,600     3,484     4,328     7,813
        진천군        10,996     8,241     19,237     7,342     8,876    16,218
        청주시       123,468   104,501    227,970    60,832    76,794   137,626
        충주시        24,726    18,947     43,673    21,744    27,153    48,896

                       인구수
구분                      남자         여자         합계
광역시도    시도
강원특별자치도 강릉시        102,918    104,956    207,874
        고성군         13,890     13,190     27,080
        동해시         44,582     43,228     87,810
        삼척시         31,534     30,500     62,034
        소계         762,647    754,712  1,517,360
        속초시         40,077     41,058     81,134
        양구군         10,902      9,904     20,805
        양양군         14,092     13,433     27,526
        영월군         19,072     17,788     36,861
        원주시        178,287    182,094    360,382
        인제군         17,265     14,430     31,695
        정선군         17,580     16,152     33,732
        철원군         21,143     19,732     40,876
        춘천시        140,732    144,432    285,164

In [193]:
popl[('20-39세','여자')]

광역시도     시도
강원특별자치도  강릉시          19,342
         고성군           1,955
         동해시           7,067
         삼척시           5,004
         소계          143,714
         속초시           7,392
         양구군           1,816
         양양군           1,710
         영월군           2,216
         원주시          41,556
         인제군           2,767
         정선군           1,880
         철원군           3,384
         춘천시          33,480
         태백시           2,478
         평창군           2,343
         홍천군           4,658
         화천군           1,990
         횡성군           2,675
경기도      가평군           4,828
         고양시         136,549
         과천시          11,076
         광명시          33,682
         광주시          44,172
         구리시          23,034
         군포시          32,011
         김포시          56,922
         남양주시         81,175
         동두천시          8,254
         부천시          97,530
         성남시         120,576
         소계        1,685,019
         수원시         169,525
         시흥시          63,493
         안산시          79,502
         안성시          19,778
         안양시          71,380
         양주시          31,986
         양평군           9,356
         여주시          10,232
         연천군           3,190
         오산시          29,382
         용인시         129,015
         의왕시          20,042
         의정부시         58,008
         이천시          25,654
         파주시          59,350
         평택시          74,042
         포천시          12,606
         하남시          43,466
         화성시         125,205
경상남도     거제시          20,451
         거창군           4,110
         고성군           2,486
         김해시          56,232
         남해군           1,860
         밀양시           6,572
         사천시           8,231
         산청군           1,570
         소계          299,752
         양산시          37,314
         의령군           1,255
         진주시          36,513
         창녕군           2,942
         창원시         102,336
         통영시           8,641
         하동군           1,929
         함안군           3,574
         함양군           1,942
         합천군           1,794
경상북도     경산시          29,724
         경주시          20,106
         고령군           1,661
         구미시          46,905
         김천시          11,469
         문경시           4,503
         봉화군           1,196
         상주시           5,692
         성주군           2,203
         소계          219,806
         안동시          13,466
         영덕군           1,648
         영양군             744
         영주시           7,089
         영천시           6,944
         예천군           4,003
         울릉군             574
         울진군           3,158
         의성군           2,196
         청도군           1,896
         청송군           1,088
         칠곡군           9,008
         포항시          44,536
광주광역시    광산구          48,832
         남구           23,117
         동구           14,079
         북구           51,242
         서구           35,386
         소계          172,656
대구광역시    군위군             888
         남구           16,454
         달서구          58,546
         달성군          27,705
         동구           37,908
         북구           47,436
         서구           15,742
         소계          261,108
         수성구          41,776
         중구           14,650
대전광역시    대덕구          17,972
         동구           24,512
         서구           63,324
         소계          182,430
         유성구          51,622
         중구           25,000
부산광역시    강서구          16,058
         금정구          22,612
         기장군          17,976
         남구           28,116
         동구            9,865
         동래구          29,518
         부산진구         50,455
         북구           28,651
         사상구          22,212
         사하구          29,980
         서구           11,166
         소계          367,166
         수영구          22,981
         연제구          24,883
         영도구           8,558
         중구            4,678
         해운대구         39,456
서울특별시    강남구          77,186
         강동구          64,816
         강북구          35,928
         강서구          90,537
         관악구          93,592
         광진구          58,510
         구로구          55,476
         금천구          34,867
         노원구          62,315
         도봉구          36,508
         동대문구         53,678
         동작구          61,998
         마포구          66,168
         서대문구         48,139
         서초구          56,179
         성동구          43,984
         성북구          61,756
         소계        1,412,954
         송파구          98,442
         양천구          51,784
         영등포구         66,128
         용산구          34,187
         은평구          66,107
         종로구          20,873
         중구           19,942
         중랑구          53,852
세종특별자치시  세종특별자치시      48,284
         소계           48,284
울산광역시    남구           34,600
         동구           14,710
         북구           23,234
         소계          113,300
         울주군          20,269
         중구           20,488
인천광역시    강화군           4,192
         계양구          33,666
         남동구          56,987
         동구            5,734
         미추홀구         50,027
         부평구          64,198
         서구           82,802
         소계          370,962
         연수구          49,998
         옹진군           1,262
         중구           22,096
전국       소계        6,049,518
전라남도     강진군           2,004
         고흥군           2,832
         곡성군           1,588
         광양시          15,865
         구례군           1,326
         나주시          12,088
         담양군           3,136
         목포시          21,006
         무안군           9,424
         보성군           1,877
         소계          156,024
         순천시          30,192
         신안군           1,794
         여수시          25,235
         영광군           4,194
         영암군           3,648
         완도군           2,624
         장성군           2,853
         장흥군           2,101
         진도군           1,782
         함평군           1,658
         해남군           3,744
         화순군           5,050
전북특별자치도  고창군           2,930
         군산시          23,702
         김제시           5,897
         남원시           5,398
         무주군           1,319
         부안군           2,861
         소계          167,273
         순창군           1,682
         완주군           9,150
         익산시          26,374
         임실군           1,438
         장수군           1,122
         전주시          76,492
         정읍시           7,538
         진안군           1,369
제주특별자치도  서귀포시         16,348
         소계           71,756
         제주시          55,408
충청남도     계룡시           4,710
         공주시           8,902
         금산군           2,863
         논산시           8,338
         당진시          14,668
         보령시           6,776
         부여군           3,370
         서산시          15,274
         서천군           2,565
         소계          213,178
         아산시          40,804
         예산군           5,437
         천안시          85,915
         청양군           1,784
         태안군           3,432
         홍성군           8,342
충청북도     괴산군           1,716
         단양군           1,457
         보은군           1,578
         소계          164,137
         영동군           2,546
         옥천군           3,043
         음성군           7,160
         제천시          11,258
         증평군           3,690
         진천군           8,241
         청주시         104,501
         충주시          18,947
Name: (20-39세, 여자), dtype: float64

In [194]:
popl['소멸비율'] = popl[('20-39세','여자')] / popl[('65세이상', '합계')]

In [195]:
pd.reset_option('display.float_format')

In [196]:
popl

                    20-39세                             65세이상             \
구분                      남자         여자          합계         남자         여자
광역시도    시도
강원특별자치도 강릉시        22929.0    19342.0     42271.0    22833.0    29660.5
        고성군         2829.0     1955.0      4784.0     3912.5     4938.0
        동해시         9370.5     7067.0     16437.5     9356.0    11853.5
        삼척시         6306.0     5004.5     11310.5     7975.5    10248.5
        소계        173762.0   143713.5    317475.5   166736.5   205557.0
        속초시         9253.0     7392.5     16645.5     8208.5    10547.0
        양구군         2773.0     1815.5      4588.5     2462.5     2878.5
        양양군         2372.5     1709.5      4082.0     4306.5     5145.0
        영월군         2790.0     2215.5      5005.5     5971.0     6843.0
        원주시        45409.5    41556.5     86966.0    29435.5    36646.0
        인제군         4861.0     2767.0      7628.0     3730.0     4004.0
        정선군         2568.5     1879.5      4448.0     5243.0     6131.0
        철원군         5140.0     3384.5      8524.5     4916.0     6257.0
        춘천시        37462.0    33480.5     70942.5    25904.5    33467.5
        태백시         3226.5     2477.5      5704.0     4993.0     6494.5
        평창군         3277.0     2343.0      5620.0     6520.0     7213.5
        홍천군         6378.5     4658.5     11037.0    10286.5    11385.0
        화천군         3441.5     1990.0      5431.5     2872.0     3328.0
        횡성군         3374.5     2675.0      6049.5     7810.5     8516.5
경기도     가평군         6238.5     4827.5     11066.0     9071.5    10017.5
        고양시       137950.5   136549.0    274499.5    78028.5    98388.0
        과천시        10938.0    11075.5     22013.5     5531.5     6545.0
        광명시        35493.5    33682.5     69176.0    20994.5    26780.0
        광주시        49094.0    44172.5     93266.5    31118.0    34924.0
        구리시        23859.0    23034.0     46893.0    14448.5    17356.5
        군포시        35642.5    32011.0     67653.5    19968.0    24598.0
        김포시        57185.5    56922.0    114107.5    33364.5    40032.0
        남양주시       83898.5    81175.0    165073.5    55790.5    68713.5
        동두천시        9627.0     8253.5     17880.5     9330.0    12305.5
        부천시       103409.5    97530.5    200940.0    62544.0    75437.0
        성남시       127006.5   120576.5    247583.0    70120.0    84999.0
        소계       1850787.0  1685019.0   3535806.0   983155.0  1190222.0
        수원시       187795.0   169525.0    357320.0    71842.5    89354.0
        시흥시        74522.5    63493.0    138015.5    28629.5    33228.5
        안산시        93336.0    79502.5    172838.5    41133.0    48714.5
        안성시        24472.5    19777.5     44250.0    17749.0    21411.0
        안양시        76379.0    71379.5    147758.5    41967.0    50832.0
        양주시        34914.0    31985.5     66899.5    21835.5    26094.5
        양평군        10827.0     9355.5     20182.5    17849.0    19847.0
        여주시        11991.0    10232.5     22223.5    13793.5    15649.5
        연천군         5053.5     3190.5      8244.0     5950.5     7061.5
        오산시        35992.0    29382.0     65374.0    12517.5    15548.0
        용인시       136404.5   129015.0    265419.5    75417.5    93382.5
        의왕시        21566.5    20042.5     41609.0    12454.0    14474.5
        의정부시       59805.5    58008.0    117813.5    36685.5    47105.5
        이천시        32925.5    25653.5     58579.0    17566.0    20232.5
        파주시        66701.0    59349.5    126050.5    35519.5    44534.5
        평택시        95338.0    74041.5    169379.5    35443.0    43980.5
        포천시        16522.0    12605.5     29127.5    17060.0    18683.0
        하남시        42655.5    43465.5     86121.0    22744.0    25976.0
        화성시       143243.0   125205.0    268448.0    46689.0    54016.5
경상남도    거제시        24375.5    20451.0     44826.5    16375.5    18344.0
        거창군         5244.5     4109.5      9354.0     7732.5    10910.0
        고성군         3405.0     2486.5      5891.5     7597.0     9914.0
        김해시        65371.5    56232.5    121604.0    34543.5    42568.5
        남해군         2679.5     1860.0      4539.5     6920.5     9836.0
        밀양시         8437.0     6571.5     15008.5    14832.5    19313.5
        사천시        11526.0     8231.0     19757.0    11514.0    15874.0
        산청군         2027.0     1570.0      3597.0     6003.0     7839.0
        소계        360670.0   299751.5    660421.5   300373.0   381473.0
        양산시        41378.5    37314.0     78692.5    27423.5    34109.0
        의령군         1647.5     1255.0      2902.5     4403.5     6054.5
        진주시        42619.0    36513.0     79132.0    29146.5    39101.5
        창녕군         4144.5     2942.0      7086.5     8959.0    11898.5
        창원시       125328.5   102335.5    227664.0    83597.0   101313.5
        통영시        10200.5     8641.0     18841.5    12982.0    16365.5
        하동군         2612.5     1929.0      4541.5     7140.5     9315.5
        함안군         4792.5     3574.0      8366.5     8056.5    10051.5
        함양군         2447.0     1941.5      4388.5     5765.5     8206.0
        합천군         2433.5     1794.5      4228.0     7380.5    10458.5
경상북도    경산시        36029.0    29723.5     65752.5    23335.5    29832.0
        경주시        24843.5    20106.0     44949.5    28348.0    36964.5
        고령군         2181.5     1661.0      3842.5     4970.5     6072.0
        구미시        59393.5    46905.0    106298.5    22631.5    27546.5
        김천시        13972.0    11469.0     25441.0    15677.0    20637.5
        문경시         5476.0     4503.0      9979.0     9933.0    13572.5
        봉화군         1732.5     1195.5      2928.0     5544.5     6718.5
        상주시         7244.5     5692.5     12937.0    13896.0    18985.5
        성주군         3143.5     2203.0      5346.5     7222.0     8353.5
        소계        278172.5   219806.0    497978.5   281030.5   358758.5
        안동시        15675.5    13466.0     29141.5    18425.0    24316.5
        영덕군         2095.0     1647.5      3742.5     5729.5     8478.5
        영양군          950.0      743.5      1693.5     2745.5     3735.5
        영주시         9122.0     7089.0     16211.0    13304.0    17460.5
        영천시         9319.5     6944.0     16263.5    14291.5    17897.5
        예천군         4599.0     4003.0      8602.0     7744.0    10154.5
        울릉군         1004.0      573.5      1577.5     1244.0     1403.0
        울진군         4433.0     3158.0      7591.0     6109.0     8492.0
        의성군         2924.5     2195.5      5120.0     9835.0    12882.5
        청도군         2431.5     1896.0      4327.5     7780.5     9718.0
        청송군         1688.0     1087.5      2775.5     4448.0     5672.0
        칠곡군        11958.5     9008.0     20966.5     9452.5    11692.5
        포항시        57956.0    44536.0    102492.0    48364.0    58173.0
광주광역시   광산구        54470.5    48832.5    103303.0    19817.0    25748.0
        남구         23633.5    23117.0     46750.5    18520.5    24685.0
        동구         14731.0    14079.0     28810.0    10707.0    13657.5
        북구         56238.0    51241.5    107479.5    33247.0    43170.0
        서구         37514.5    35386.5     72901.0    21220.0    27901.0
        소계        186587.5   172656.5    359244.0   103511.5   135161.5
대구광역시   군위군         1334.5      888.5      2223.0     4770.0     5630.0
        남구         17114.0    16454.5     33568.5    15329.0    21528.5
        달서구        66065.5    58546.0    124611.5    42394.5    54175.0
        달성군        32922.0    27705.0     60627.0    18637.5    22745.0
        동구         42506.5    37908.5     80415.0    33440.0    44887.5
        북구         55317.0    47436.5    102753.5    32708.5    42766.5
        서구         19441.5    15742.5     35184.0    18570.5    25245.0
        소계        293942.5   261108.0    555050.5   205889.0   270811.5
        수성구        45137.5    41776.0     86913.5    32879.0    43616.5
        중구         14104.0    14650.5     28754.5     7160.0    10217.5
대전광역시   대덕구        22291.5    17971.5     40263.0    15187.5    18676.0
        동구         28125.0    24512.0     52637.0    21377.5    27121.5
        서구         66192.0    63324.5    129516.5    32547.0    40462.5
        소계        202197.0   182429.5    384626.5   111469.0   138637.5
        유성구        59375.0    51622.0    110997.0    19907.5    23459.5
        중구         26213.5    24999.5     51213.0    22449.5    28918.0
부산광역시   강서구        17574.0    16057.5     33631.5     9855.5    10790.0
        금정구        26311.0    22612.5     48923.5    24015.0    30757.0
        기장군        19328.5    17976.0     37304.5    14443.5    18941.5
        남구         30533.0    28115.5     58648.5    25945.5    33903.5
        동구         10041.5     9865.0     19906.5    10665.5    14501.0
        동래구        30188.5    29518.0     59706.5    25878.5    32988.0
        부산진구       48669.0    50455.0     99124.0    34943.0    45577.0
        북구         32188.5    28651.0     60839.5    27354.5    33229.0
        사상구        25499.0    22212.5     47711.5    21282.5    25606.0
        사하구        34709.0    29979.5     64688.5    31489.0    38888.0
        서구         10910.0    11166.5     22076.5    12620.5    16957.5
        소계        388220.0   367166.0    755386.0   332443.0   424992.0
        수영구        21802.0    22981.0     44783.0    18298.5    24573.5
        연제구        24731.5    24883.0     49614.5    20692.5    26628.5
        영도구        10196.0     8558.0     18754.0    14649.0    19270.5
        중구          4728.5     4678.5      9407.0     5093.0     6777.5
        해운대구       40810.0    39456.5     80266.5    35217.0    45603.5
서울특별시   강남구        68355.0    77186.5    145541.5    39037.5    47853.0
        강동구        61809.5    64816.5    126626.0    38952.0    46353.5
        강북구        35722.0    35927.5     71649.5    29851.0    39365.0
        강서구        82616.0    90537.0    173153.0    45668.5    57734.5
        관악구       100644.0    93592.0    194236.0    38049.5    47608.0
        광진구        54063.0    58510.0    112573.0    25631.5    31549.5
        구로구        54823.0    55476.0    110299.0    35824.0    43632.0
        금천구        37405.5    34867.0     72272.5    20806.0    24575.5
        노원구        63430.5    62315.0    125745.5    41516.5    55935.0
        도봉구        37196.5    36507.5     73704.0    31961.0    39532.0
        동대문구       51877.5    53678.5    105556.0    30059.0    37289.0
        동작구        60801.0    61998.5    122799.5    30790.5    39748.5
        마포구        55359.5    66167.5    121527.0    24272.5    33359.5
        서대문구       43824.5    48139.0     91963.5    24794.5    33063.5
        서초구        49522.5    56179.0    105701.5    29778.5    36016.5
        성동구        41665.0    43984.0     85649.0    21879.5    27602.0
        성북구        57870.5    61755.5    119626.0    34985.5    45824.0
        소계       1341060.0  1412954.0   2754014.0   777141.5   973956.5
        송파구        88915.5    98442.5    187358.0    50552.5    59209.0
        양천구        51785.0    51784.5    103569.5    34801.5    42527.5
        영등포구       61385.5    66128.5    127514.0    30095.0    36201.0
        용산구        31283.0    34187.0     65470.0    16673.0    21349.5
        은평구        60238.5    66107.0    126345.5    40811.5    53810.5
        종로구        19605.5    20873.0     40478.5    12827.0    15570.0
        중구         18226.5    19942.5     38169.0    11261.5    14145.0
        중랑구        52635.0    53852.0    106487.0    36262.0    44103.0
세종특별자치시 세종특별자치시    48086.5    48283.5     96370.0    19675.0    23830.5
        소계         48086.5    48283.5     96370.0    19675.0    23830.5
울산광역시   남구         43246.5    34599.5     77846.0    22679.5    26168.0
        동구         18834.5    14709.5     33544.0    12663.0    13595.0
        북구         29486.0    23234.0     52720.0    11406.0    12861.5
        소계        142497.0   113299.5    255796.5    84302.5    96901.0
        울주군        25739.5    20269.0     46008.5    19235.5    22070.0
        중구         25190.5    20487.5     45678.0    18318.5    22206.5
인천광역시   강화군         5076.5     4192.5      9269.0    12092.0    14009.5
        계양구        37512.5    33666.5     71179.0    22186.5    26443.5
        남동구        62031.5    56987.0    119018.5    38680.5    48979.0
        동구          6570.0     5733.5     12303.5     6643.0     8741.0
        미추홀구       56800.0    50027.0    106827.0    35702.0    45683.5
        부평구        67971.5    64198.0    132169.5    39238.0    50064.5
        서구         86169.0    82802.0    168971.0    36836.5    43448.0
        소계        400947.5   370962.5    771910.0   228801.0   281179.5
        연수구        51477.0    49997.5    101474.5    22749.0    26564.0
        옹진군         2844.5     1262.5      4107.0     3157.0     3352.0
        중구         24495.0    22096.0     46591.0    11516.5    13894.5
전국      소계       6582521.5  6049518.5  12632040.0  4396558.5  5502988.5
전라남도    강진군         2424.0     2003.5      4427.5     5210.5     7265.5
        고흥군         3649.5     2832.0      6481.5    11244.5    15746.0
        곡성군         1893.0     1588.0      3481.0     4469.5     6051.5
        광양시        20525.5    15865.0     36390.5    11123.0    13071.0
        구례군         1549.5     1326.0      2875.5     3845.0     5429.5
        나주시        13026.5    12088.5     25115.0    12278.0    16190.5
        담양군         3792.5     3136.5      6929.0     6782.0     8706.5
        목포시        23694.5    21006.5     44701.0    18641.0    24568.5
        무안군        10193.5     9424.0     19617.5     8253.0    10891.0
        보성군         2411.5     1877.0      4288.5     6586.5     9332.0
        소계        186191.5   156024.5    342216.0   205052.0   269693.5
        순천시        34507.5    30192.5     64700.0    22819.5    28735.0
        신안군         2826.5     1794.0      4620.5     6703.5     8293.0
        여수시        31596.5    25235.0     56831.5    27722.0    34360.0
        영광군         4811.5     4194.5      9006.0     6893.0     9459.5
        영암군         4825.0     3648.5      8473.5     6522.5     8821.0
        완도군         3403.0     2624.0      6027.0     7133.0     9668.0
        장성군         3765.5     2853.0      6618.5     6190.0     7993.0
        장흥군         2580.5     2101.0      4681.5     5420.5     7818.5
        진도군         2202.0     1782.5      3984.5     4428.5     6204.0
        함평군         2163.0     1658.5      3821.5     5142.0     7093.5
        해남군         4831.5     3744.5      8576.0     9867.0    13466.5
        화순군         5519.0     5049.5     10568.5     7777.5    10529.5
전북특별자치도 고창군         3651.0     2929.5      6580.5     8350.5    11473.0
        군산시        28268.5    23702.5     51971.0    25745.0    32024.0
        김제시         7092.5     5897.0     12989.5    11874.5    16083.5
        남원시         6300.0     5398.5     11698.5    10258.5    13964.0
        무주군         1640.0     1319.0      2959.0     3690.5     4881.0
        부안군         3669.0     2861.0      6530.0     7817.0    10438.5
        소계        190569.5   167273.0    357842.5   185930.5   241376.5
        순창군         1919.5     1682.0      3601.5     4110.5     5747.0
        완주군        10658.5     9150.0     19808.5    11140.0    13348.5
        익산시        30629.5    26374.0     57003.5    27539.5    35258.5
        임실군         1860.5     1437.5      3298.0     4594.5     5779.0
        장수군         1382.0     1122.0      2504.0     3485.5     4590.5
        전주시        82721.5    76492.5    159214.0    49463.0    64238.5
        정읍시         9189.5     7538.5     16728.0    13560.0    18372.5
        진안군         1587.5     1369.0      2956.5     4301.5     5178.0
제주특별자치도 서귀포시       17982.5    16348.5     34331.0    17821.0    22589.5
        소계         77607.0    71756.5    149363.5    53839.5    68537.0
        제주시        59624.5    55408.0    115032.5    36018.5    45947.5
충청남도    계룡시         5502.5     4710.0     10212.5     2990.0     3726.0
        공주시        10120.5     8901.5     19022.0    13828.0    17014.5
        금산군         3552.5     2863.0      6415.5     7871.5     9783.0
        논산시        10151.5     8338.5     18490.0    14774.0    18938.5
        당진시        20520.0    14667.5     35187.5    16336.5    19416.5
        보령시         8756.0     6776.0     15532.0    12628.0    16119.0
        부여군         4307.0     3369.5      7676.5    10617.0    13397.5
        서산시        21945.5    15273.5     37219.0    16846.0    20522.0
        서천군         3376.5     2565.0      5941.5     8637.0    11270.5
        소계        260105.5   213178.0    473283.5   205537.5   255380.0
        아산시        48871.5    40803.5     89675.0    22653.0    28219.5
        예산군         6728.0     5437.0     12165.0    11945.0    14980.5
        천안시        99260.0    85915.0    185175.0    39895.5    48500.0
        청양군         2413.5     1784.0      4197.5     5293.0     6531.0
        태안군         4755.0     3432.0      8187.0     9758.5    12128.0
        홍성군         9845.5     8342.0     18187.5    11464.5    14833.5
충청북도    괴산군         2395.0     1716.5      4111.5     6877.5     7768.0
        단양군         1941.0     1457.0      3398.0     4700.5     5517.0
        보은군         2097.0     1578.5      3675.5     5444.5     6793.0
        소계        201118.5   164137.0    365255.5   151671.5   186521.0
        영동군         3233.5     2545.5      5779.0     7295.5     8971.5
        옥천군         3767.0     3043.0      6810.0     7640.5     9154.0
        음성군         9750.5     7159.5     16910.0    10800.5    12374.0
        제천시        13833.0    11258.5     25091.5    15511.0    18791.5
        증평군         4911.0     3689.5      8600.5     3484.5     4328.5
        진천군        10996.0     8241.0     19237.0     7341.5     8876.0
        청주시       123468.5   104501.0    227969.5    60832.0    76794.5
        충주시        24726.0    18947.0     43673.0    21743.5    27153.0

                                   인구수                              소멸비율
구분                      합계          남자          여자          합계
광역시도    시도
강원특별자치도 강릉시        52493.5    102917.5    104956.5    207874.0  0.368465
        고성군         8850.5     13890.0     13189.5     27079.5  0.220891
        동해시        21209.5     44582.5     43227.5     87810.0  0.333200
        삼척시        18224.0     31534.0     30499.5     62033.5  0.274610
        소계        372293.5    762647.0    754712.5   1517359.5  0.386022
        속초시        18755.5     40077.0     41057.5     81134.5  0.394151
        양구군         5341.0     10901.5      9903.5     20805.0  0.339918
        양양군         9451.5     14092.5     13433.0     27525.5  0.180871
        영월군        12814.0     19072.5     17788.5     36861.0  0.172897
        원주시        66081.5    178287.0    182094.5    360381.5  0.628867
        인제군         7734.0     17265.0     14430.0     31695.0  0.357771
        정선군        11374.0     17579.5     16152.0     33731.5  0.165245
        철원군        11173.0     21143.0     19732.5     40875.5  0.302918
        춘천시        59372.0    140731.5    144432.0    285163.5  0.563911
        태백시        11487.5     19266.0     18935.0     38201.0  0.215669
        평창군        13733.5     20933.5     19454.0     40387.5  0.170605
        홍천군        21671.5     34416.0     32393.5     66809.5  0.214960
        화천군         6200.0     12270.5     10633.0     22903.5  0.320968
        횡성군        16327.0     23687.5     22400.5     46088.0  0.163839
경기도     가평군        19089.0     32013.0     30133.0     62146.0  0.252894
        고양시       176416.5    519637.0    546537.5   1066174.5  0.774015
        과천시        12076.5     40487.0     42278.5     82765.5  0.917112
        광명시        47774.5    136179.5    141739.5    277919.0  0.705031
        광주시        66042.0    200190.5    192654.5    392845.0  0.668855
        구리시        31805.0     91969.0     94077.5    186046.5  0.724226
        군포시        44566.0    127632.5    129821.5    257454.0  0.718283

In [197]:
popl['소멸위기지역'] = popl['소멸비율'] < 0.5 
popl.head(10)

               20-39세                         65세이상                      \
구분                 남자        여자        합계        남자        여자        합계
광역시도    시도
강원특별자치도 강릉시   22929.0   19342.0   42271.0   22833.0   29660.5   52493.5
        고성군    2829.0    1955.0    4784.0    3912.5    4938.0    8850.5
        동해시    9370.5    7067.0   16437.5    9356.0   11853.5   21209.5
        삼척시    6306.0    5004.5   11310.5    7975.5   10248.5   18224.0
        소계   173762.0  143713.5  317475.5  166736.5  205557.0  372293.5
        속초시    9253.0    7392.5   16645.5    8208.5   10547.0   18755.5
        양구군    2773.0    1815.5    4588.5    2462.5    2878.5    5341.0
        양양군    2372.5    1709.5    4082.0    4306.5    5145.0    9451.5
        영월군    2790.0    2215.5    5005.5    5971.0    6843.0   12814.0
        원주시   45409.5   41556.5   86966.0   29435.5   36646.0   66081.5

                  인구수                           소멸비율 소멸위기지역
구분                 남자        여자         합계
광역시도    시도
강원특별자치도 강릉시  102917.5  104956.5   207874.0  0.368465   True
        고성군   13890.0   13189.5    27079.5  0.220891   True
        동해시   44582.5   43227.5    87810.0  0.333200   True
        삼척시   31534.0   30499.5    62033.5  0.274610   True
        소계   762647.0  754712.5  1517359.5  0.386022   True
        속초시   40077.0   41057.5    81134.5  0.394151   True
        양구군   10901.5    9903.5    20805.0  0.339918   True
        양양군   14092.5   13433.0    27525.5  0.180871   True
        영월군   19072.5   17788.5    36861.0  0.172897   True
        원주시  178287.0  182094.5   360381.5  0.628867  False

In [198]:
popl.reset_index()

        광역시도       시도     20-39세                             65세이상             \
구분                            남자         여자          합계         남자         여자
0    강원특별자치도      강릉시    22929.0    19342.0     42271.0    22833.0    29660.5
1    강원특별자치도      고성군     2829.0     1955.0      4784.0     3912.5     4938.0
2    강원특별자치도      동해시     9370.5     7067.0     16437.5     9356.0    11853.5
3    강원특별자치도      삼척시     6306.0     5004.5     11310.5     7975.5    10248.5
4    강원특별자치도       소계   173762.0   143713.5    317475.5   166736.5   205557.0
5    강원특별자치도      속초시     9253.0     7392.5     16645.5     8208.5    10547.0
6    강원특별자치도      양구군     2773.0     1815.5      4588.5     2462.5     2878.5
7    강원특별자치도      양양군     2372.5     1709.5      4082.0     4306.5     5145.0
8    강원특별자치도      영월군     2790.0     2215.5      5005.5     5971.0     6843.0
9    강원특별자치도      원주시    45409.5    41556.5     86966.0    29435.5    36646.0
10   강원특별자치도      인제군     4861.0     2767.0      7628.0     3730.0     4004.0
11   강원특별자치도      정선군     2568.5     1879.5      4448.0     5243.0     6131.0
12   강원특별자치도      철원군     5140.0     3384.5      8524.5     4916.0     6257.0
13   강원특별자치도      춘천시    37462.0    33480.5     70942.5    25904.5    33467.5
14   강원특별자치도      태백시     3226.5     2477.5      5704.0     4993.0     6494.5
15   강원특별자치도      평창군     3277.0     2343.0      5620.0     6520.0     7213.5
16   강원특별자치도      홍천군     6378.5     4658.5     11037.0    10286.5    11385.0
17   강원특별자치도      화천군     3441.5     1990.0      5431.5     2872.0     3328.0
18   강원특별자치도      횡성군     3374.5     2675.0      6049.5     7810.5     8516.5
19       경기도      가평군     6238.5     4827.5     11066.0     9071.5    10017.5
20       경기도      고양시   137950.5   136549.0    274499.5    78028.5    98388.0
21       경기도      과천시    10938.0    11075.5     22013.5     5531.5     6545.0
22       경기도      광명시    35493.5    33682.5     69176.0    20994.5    26780.0
23       경기도      광주시    49094.0    44172.5     93266.5    31118.0    34924.0
24       경기도      구리시    23859.0    23034.0     46893.0    14448.5    17356.5
25       경기도      군포시    35642.5    32011.0     67653.5    19968.0    24598.0
26       경기도      김포시    57185.5    56922.0    114107.5    33364.5    40032.0
27       경기도     남양주시    83898.5    81175.0    165073.5    55790.5    68713.5
28       경기도     동두천시     9627.0     8253.5     17880.5     9330.0    12305.5
29       경기도      부천시   103409.5    97530.5    200940.0    62544.0    75437.0
30       경기도      성남시   127006.5   120576.5    247583.0    70120.0    84999.0
31       경기도       소계  1850787.0  1685019.0   3535806.0   983155.0  1190222.0
32       경기도      수원시   187795.0   169525.0    357320.0    71842.5    89354.0
33       경기도      시흥시    74522.5    63493.0    138015.5    28629.5    33228.5
34       경기도      안산시    93336.0    79502.5    172838.5    41133.0    48714.5
35       경기도      안성시    24472.5    19777.5     44250.0    17749.0    21411.0
36       경기도      안양시    76379.0    71379.5    147758.5    41967.0    50832.0
37       경기도      양주시    34914.0    31985.5     66899.5    21835.5    26094.5
38       경기도      양평군    10827.0     9355.5     20182.5    17849.0    19847.0
39       경기도      여주시    11991.0    10232.5     22223.5    13793.5    15649.5
40       경기도      연천군     5053.5     3190.5      8244.0     5950.5     7061.5
41       경기도      오산시    35992.0    29382.0     65374.0    12517.5    15548.0
42       경기도      용인시   136404.5   129015.0    265419.5    75417.5    93382.5
43       경기도      의왕시    21566.5    20042.5     41609.0    12454.0    14474.5
44       경기도     의정부시    59805.5    58008.0    117813.5    36685.5    47105.5
45       경기도      이천시    32925.5    25653.5     58579.0    17566.0    20232.5
46       경기도      파주시    66701.0    59349.5    126050.5    35519.5    44534.5
47       경기도      평택시    95338.0    74041.5    169379.5    35443.0    43980.5
48       경기도      포천시    16522.0    12605.5     29127.5    17060.0    18683.0
49       경기도      하남시    42655.5    43465.5     86121.0    22744.0    25976.0
50       경기도      화성시   143243.0   125205.0    268448.0    46689.0    54016.5
51      경상남도      거제시    24375.5    20451.0     44826.5    16375.5    18344.0
52      경상남도      거창군     5244.5     4109.5      9354.0     7732.5    10910.0
53      경상남도      고성군     3405.0     2486.5      5891.5     7597.0     9914.0
54      경상남도      김해시    65371.5    56232.5    121604.0    34543.5    42568.5
55      경상남도      남해군     2679.5     1860.0      4539.5     6920.5     9836.0
56      경상남도      밀양시     8437.0     6571.5     15008.5    14832.5    19313.5
57      경상남도      사천시    11526.0     8231.0     19757.0    11514.0    15874.0
58      경상남도      산청군     2027.0     1570.0      3597.0     6003.0     7839.0
59      경상남도       소계   360670.0   299751.5    660421.5   300373.0   381473.0
60      경상남도      양산시    41378.5    37314.0     78692.5    27423.5    34109.0
61      경상남도      의령군     1647.5     1255.0      2902.5     4403.5     6054.5
62      경상남도      진주시    42619.0    36513.0     79132.0    29146.5    39101.5
63      경상남도      창녕군     4144.5     2942.0      7086.5     8959.0    11898.5
64      경상남도      창원시   125328.5   102335.5    227664.0    83597.0   101313.5
65      경상남도      통영시    10200.5     8641.0     18841.5    12982.0    16365.5
66      경상남도      하동군     2612.5     1929.0      4541.5     7140.5     9315.5
67      경상남도      함안군     4792.5     3574.0      8366.5     8056.5    10051.5
68      경상남도      함양군     2447.0     1941.5      4388.5     5765.5     8206.0
69      경상남도      합천군     2433.5     1794.5      4228.0     7380.5    10458.5
70      경상북도      경산시    36029.0    29723.5     65752.5    23335.5    29832.0
71      경상북도      경주시    24843.5    20106.0     44949.5    28348.0    36964.5
72      경상북도      고령군     2181.5     1661.0      3842.5     4970.5     6072.0
73      경상북도      구미시    59393.5    46905.0    106298.5    22631.5    27546.5
74      경상북도      김천시    13972.0    11469.0     25441.0    15677.0    20637.5
75      경상북도      문경시     5476.0     4503.0      9979.0     9933.0    13572.5
76      경상북도      봉화군     1732.5     1195.5      2928.0     5544.5     6718.5
77      경상북도      상주시     7244.5     5692.5     12937.0    13896.0    18985.5
78      경상북도      성주군     3143.5     2203.0      5346.5     7222.0     8353.5
79      경상북도       소계   278172.5   219806.0    497978.5   281030.5   358758.5
80      경상북도      안동시    15675.5    13466.0     29141.5    18425.0    24316.5
81      경상북도      영덕군     2095.0     1647.5      3742.5     5729.5     8478.5
82      경상북도      영양군      950.0      743.5      1693.5     2745.5     3735.5
83      경상북도      영주시     9122.0     7089.0     16211.0    13304.0    17460.5
84      경상북도      영천시     9319.5     6944.0     16263.5    14291.5    17897.5
85      경상북도      예천군     4599.0     4003.0      8602.0     7744.0    10154.5
86      경상북도      울릉군     1004.0      573.5      1577.5     1244.0     1403.0
87      경상북도      울진군     4433.0     3158.0      7591.0     6109.0     8492.0
88      경상북도      의성군     2924.5     2195.5      5120.0     9835.0    12882.5
89      경상북도      청도군     2431.5     1896.0      4327.5     7780.5     9718.0
90      경상북도      청송군     1688.0     1087.5      2775.5     4448.0     5672.0
91      경상북도      칠곡군    11958.5     9008.0     20966.5     9452.5    11692.5
92      경상북도      포항시    57956.0    44536.0    102492.0    48364.0    58173.0
93     광주광역시      광산구    54470.5    48832.5    103303.0    19817.0    25748.0
94     광주광역시       남구    23633.5    23117.0     46750.5    18520.5    24685.0
95     광주광역시       동구    14731.0    14079.0     28810.0    10707.0    13657.5
96     광주광역시       북구    56238.0    51241.5    107479.5    33247.0    43170.0
97     광주광역시       서구    37514.5    35386.5     72901.0    21220.0    27901.0
98     광주광역시       소계   186587.5   172656.5    359244.0   103511.5   135161.5
99     대구광역시      군위군     1334.5      888.5      2223.0     4770.0     5630.0
100    대구광역시       남구    17114.0    16454.5     33568.5    15329.0    21528.5
101    대구광역시      달서구    66065.5    58546.0    124611.5    42394.5    54175.0
102    대구광역시      달성군    32922.0    27705.0     60627.0    18637.5    22745.0
103    대구광역시       동구    42506.5    37908.5     80415.0    33440.0    44887.5
104    대구광역시       북구    55317.0    47436.5    102753.5    32708.5    42766.5
105    대구광역시       서구    19441.5    15742.5     35184.0    18570.5    25245.0
106    대구광역시       소계   293942.5   261108.0    555050.5   205889.0   270811.5
107    대구광역시      수성구    45137.5    41776.0     86913.5    32879.0    43616.5
108    대구광역시       중구    14104.0    14650.5     28754.5     7160.0    10217.5
109    대전광역시      대덕구    22291.5    17971.5     40263.0    15187.5    18676.0
110    대전광역시       동구    28125.0    24512.0     52637.0    21377.5    27121.5
111    대전광역시       서구    66192.0    63324.5    129516.5    32547.0    40462.5
112    대전광역시       소계   202197.0   182429.5    384626.5   111469.0   138637.5
113    대전광역시      유성구    59375.0    51622.0    110997.0    19907.5    23459.5
114    대전광역시       중구    26213.5    24999.5     51213.0    22449.5    28918.0
115    부산광역시      강서구    17574.0    16057.5     33631.5     9855.5    10790.0
116    부산광역시      금정구    26311.0    22612.5     48923.5    24015.0    30757.0
117    부산광역시      기장군    19328.5    17976.0     37304.5    14443.5    18941.5
118    부산광역시       남구    30533.0    28115.5     58648.5    25945.5    33903.5
119    부산광역시       동구    10041.5     9865.0     19906.5    10665.5    14501.0
120    부산광역시      동래구    30188.5    29518.0     59706.5    25878.5    32988.0
121    부산광역시     부산진구    48669.0    50455.0     99124.0    34943.0    45577.0
122    부산광역시       북구    32188.5    28651.0     60839.5    27354.5    33229.0
123    부산광역시      사상구    25499.0    22212.5     47711.5    21282.5    25606.0
124    부산광역시      사하구    34709.0    29979.5     64688.5    31489.0    38888.0
125    부산광역시       서구    10910.0    11166.5     22076.5    12620.5    16957.5
126    부산광역시       소계   388220.0   367166.0    755386.0   332443.0   424992.0
127    부산광역시      수영구    21802.0    22981.0     44783.0    18298.5    24573.5
128    부산광역시      연제구    24731.5    24883.0     49614.5    20692.5    26628.5
129    부산광역시      영도구    10196.0     8558.0     18754.0    14649.0    19270.5
130    부산광역시       중구     4728.5     4678.5      9407.0     5093.0     6777.5
131    부산광역시     해운대구    40810.0    39456.5     80266.5    35217.0    45603.5
132    서울특별시      강남구    68355.0    77186.5    145541.5    39037.5    47853.0
133    서울특별시      강동구    61809.5    64816.5    126626.0    38952.0    46353.5
134    서울특별시      강북구    35722.0    35927.5     71649.5    29851.0    39365.0
135    서울특별시      강서구    82616.0    90537.0    173153.0    45668.5    57734.5
136    서울특별시      관악구   100644.0    93592.0    194236.0    38049.5    47608.0
137    서울특별시      광진구    54063.0    58510.0    112573.0    25631.5    31549.5
138    서울특별시      구로구    54823.0    55476.0    110299.0    35824.0    43632.0
139    서울특별시      금천구    37405.5    34867.0     72272.5    20806.0    24575.5
140    서울특별시      노원구    63430.5    62315.0    125745.5    41516.5    55935.0
141    서울특별시      도봉구    37196.5    36507.5     73704.0    31961.0    39532.0
142    서울특별시     동대문구    51877.5    53678.5    105556.0    30059.0    37289.0
143    서울특별시      동작구    60801.0    61998.5    122799.5    30790.5    39748.5
144    서울특별시      마포구    55359.5    66167.5    121527.0    24272.5    33359.5
145    서울특별시     서대문구    43824.5    48139.0     91963.5    24794.5    33063.5
146    서울특별시      서초구    49522.5    56179.0    105701.5    29778.5    36016.5
147    서울특별시      성동구    41665.0    43984.0     85649.0    21879.5    27602.0
148    서울특별시      성북구    57870.5    61755.5    119626.0    34985.5    45824.0
149    서울특별시       소계  1341060.0  1412954.0   2754014.0   777141.5   973956.5
150    서울특별시      송파구    88915.5    98442.5    187358.0    50552.5    59209.0
151    서울특별시      양천구    51785.0    51784.5    103569.5    34801.5    42527.5
152    서울특별시     영등포구    61385.5    66128.5    127514.0    30095.0    36201.0
153    서울특별시      용산구    31283.0    34187.0     65470.0    16673.0    21349.5
154    서울특별시      은평구    60238.5    66107.0    126345.5    40811.5    53810.5
155    서울특별시      종로구    19605.5    20873.0     40478.5    12827.0    15570.0
156    서울특별시       중구    18226.5    19942.5     38169.0    11261.5    14145.0
157    서울특별시      중랑구    52635.0    53852.0    106487.0    36262.0    44103.0
158  세종특별자치시  세종특별자치시    48086.5    48283.5     96370.0    19675.0    23830.5
159  세종특별자치시       소계    48086.5    48283.5     96370.0    19675.0    23830.5
160    울산광역시       남구    43246.5    34599.5     77846.0    22679.5    26168.0
161    울산광역시       동구    18834.5    14709.5     33544.0    12663.0    13595.0
162    울산광역시       북구    29486.0    23234.0     52720.0    11406.0    12861.5
163    울산광역시       소계   142497.0   113299.5    255796.5    84302.5    96901.0
164    울산광역시      울주군    25739.5    20269.0     46008.5    19235.5    22070.0
165    울산광역시       중구    25190.5    20487.5     45678.0    18318.5    22206.5
166    인천광역시      강화군     5076.5     4192.5      9269.0    12092.0    14009.5
167    인천광역시      계양구    37512.5    33666.5     71179.0    22186.5    26443.5
168    인천광역시      남동구    62031.5    56987.0    119018.5    38680.5    48979.0
169    인천광역시       동구     6570.0     5733.5     12303.5     6643.0     8741.0
170    인천광역시     미추홀구    56800.0    50027.0    106827.0    35702.0    45683.5
171    인천광역시      부평구    67971.5    64198.0    132169.5    39238.0    50064.5
172    인천광역시       서구    86169.0    82802.0    168971.0    36836.5    43448.0
173    인천광역시       소계   400947.5   370962.5    771910.0   228801.0   281179.5
174    인천광역시      연수구    51477.0    49997.5    101474.5    22749.0    26564.0
175    인천광역시      옹진군     2844.5     1262.5      4107.0     3157.0     3352.0
176    인천광역시       중구    24495.0    22096.0     46591.0    11516.5    13894.5
177       전국       소계  6582521.5  6049518.5  12632040.0  4396558.5  5502988.5
178     전라남도      강진군     2424.0     2003.5      4427.5     5210.5     7265.5
179     전라남도      고흥군     3649.5     2832.0      6481.5    11244.5    15746.0
180     전라남도      곡성군     1893.0     1588.0      3481.0     4469.5     6051.5
181     전라남도      광양시    20525.5    15865.0     36390.5    11123.0    13071.0
182     전라남도      구례군     1549.5     1326.0      2875.5     3845.0     5429.5
183     전라남도      나주시    13026.5    12088.5     25115.0    12278.0    16190.5
184     전라남도      담양군     3792.5     3136.5      6929.0     6782.0     8706.5
185     전라남도      목포시    23694.5    21006.5     44701.0    18641.0    24568.5
186     전라남도      무안군    10193.5     9424.0     19617.5     8253.0    10891.0
187     전라남도      보성군     2411.5     1877.0      4288.5     6586.5     9332.0
188     전라남도       소계   186191.5   156024.5    342216.0   205052.0   269693.5
189     전라남도      순천시    34507.5    30192.5     64700.0    22819.5    28735.0
190     전라남도      신안군     2826.5     1794.0      4620.5     6703.5     8293.0
191     전라남도      여수시    31596.5    25235.0     56831.5    27722.0    34360.0
192     전라남도      영광군     4811.5     4194.5      9006.0     6893.0     9459.5
193     전라남도      영암군     4825.0     3648.5      8473.5     6522.5     8821.0
194     전라남도      완도군     3403.0     2624.0      6027.0     7133.0     9668.0
195     전라남도      장성군     3765.5     2853.0      6618.5     6190.0     7993.0
196     전라남도      장흥군     2580.5     2101.0      4681.5     5420.5     7818.5
197     전라남도      진도군     2202.0     1782.5      3984.5     4428.5     6204.0
198     전라남도      함평군     2163.0     1658.5      3821.5     5142.0     7093.5
199     전라남도      해남군     4831.5     3744.5      8576.0     9867.0    13466.5
200     전라남도      화순군     5519.0     5049.5     10568.5     7777.5    10529.5
201  전북특별자치도      고창군     3651.0     2929.5      6580.5     8350.5    11473.0
202  전북특별자치도      군산시    28268.5    23702.5     51971.0    25745.0    32024.0
203  전북특별자치도      김제시     7092.5     5897.0     12989.5    11874.5    16083.5
204  전북특별자치도      남원시     6300.0     5398.5     11698.5    10258.5    13964.0
205  전북특별자치도      무주군     1640.0     1319.0      2959.0     3690.5     4881.0
206  전북특별자치도      부안군     3669.0     2861.0      6530.0     7817.0    10438.5
207  전북특별자치도       소계   190569.5   167273.0    357842.5   185930.5   241376.5
208  전북특별자치도      순창군     1919.5     1682.0      3601.5     4110.5     5747.0
209  전북특별자치도      완주군    10658.5     9150.0     19808.5    11140.0    13348.5
210  전북특별자치도      익산시    30629.5    26374.0     57003.5    27539.5    35258.5
211  전북특별자치도      임실군     1860.5     1437.5      3298.0     4594.5     5779.0
212  전북특별자치도      장수군     1382.0     1122.0      2504.0     3485.5     4590.5
213  전북특별자치도      전주시    82721.5    76492.5    159214.0    49463.0    64238.5
214  전북특별자치도      정읍시     9189.5     7538.5     16728.0    13560.0    18372.5
215  전북특별자치도      진안군     1587.5     1369.0      2956.5     4301.5     5178.0
216  제주특별자치도     서귀포시    17982.5    16348.5     34331.0    17821.0    22589.5
217  제주특별자치도       소계    77607.0    71756.5    149363.5    53839.5    68537.0
218  제주특별자치도      제주시    59624.5    55408.0    115032.5    36018.5    45947.5
219     충청남도      계룡시     5502.5     4710.0     10212.5     2990.0     3726.0
220     충청남도      공주시    10120.5     8901.5     19022.0    13828.0    17014.5
221     충청남도      금산군     3552.5     2863.0      6415.5     7871.5     9783.0
222     충청남도      논산시    10151.5     8338.5     18490.0    14774.0    18938.5
223     충청남도      당진시    20520.0    14667.5     35187.5    16336.5    19416.5
224     충청남도      보령시     8756.0     6776.0     15532.0    12628.0    16119.0
225     충청남도      부여군     4307.0     3369.5      7676.5    10617.0    13397.5
226     충청남도      서산시    21945.5    15273.5     37219.0    16846.0    20522.0
227     충청남도      서천군     3376.5     2565.0      5941.5     8637.0    11270.5
228     충청남도       소계   260105.5   213178.0    473283.5   205537.5   255380.0
229     충청남도      아산시    48871.5    40803.5     89675.0    22653.0    28219.5
230     충청남도      예산군     6728.0     5437.0     12165.0    11945.0    14980.5
231     충청남도      천안시    99260.0    85915.0    185175.0    39895.5    48500.0
232     충청남도      청양군     2413.5     1784.0      4197.5     5293.0     6531.0
233     충청남도      태안군     4755.0     3432.0      8187.0     9758.5    12128.0
234     충청남도      홍성군     9845.5     8342.0     18187.5    11464.5    14833.5
235     충청북도      괴산군     2395.0     1716.5      4111.5     6877.5     7768.0
236     충청북도      단양군     1941.0     1457.0      3398.0     4700.5     5517.0
237     충청북도      보은군     2097.0     1578.5      3675.5     5444.5     6793.0
238     충청북도       소계   201118.5   164137.0    365255.5   151671.5   186521.0
239     충청북도      영동군     3233.5     2545.5      5779.0     7295.5     8971.5
240     충청북도      옥천군     3767.0     3043.0      6810.0     7640.5     9154.0
241     충청북도      음성군     9750.5     7159.5     16910.0    10800.5    12374.0
242     충청북도      제천시    13833.0    11258.5     25091.5    15511.0    18791.5
243     충청북도      증평군     4911.0     3689.5      8600.5     3484.5     4328.5
244     충청북도      진천군    10996.0     8241.0     19237.0     7341.5     8876.0
245     충청북도      청주시   123468.5   104501.0    227969.5    60832.0    76794.5
246     충청북도      충주시    24726.0    18947.0     43673.0    21743.5    27153.0

                       인구수                              소멸비율 소멸위기지역
구분          합계          남자          여자          합계
0      52493.5    102917.5    104956.5    207874.0  0.368465   True
1       8850.5     13890.0     13189.5     27079.5  0.220891   True
2      21209.5     44582.5     43227.5     87810.0  0.333200   True
3      18224.0     31534.0     30499.5     62033.5  0.274610   True
4     372293.5    762647.0    754712.5   1517359.5  0.386022   True
5      18755.5     40077.0     41057.5     81134.5  0.394151   True

In [199]:
popl.reset_index(inplace=True)
popl.head()

       광역시도   시도    20-39세                         65세이상                      \
구분                      남자        여자        합계        남자        여자        합계
0   강원특별자치도  강릉시   22929.0   19342.0   42271.0   22833.0   29660.5   52493.5
1   강원특별자치도  고성군    2829.0    1955.0    4784.0    3912.5    4938.0    8850.5
2   강원특별자치도  동해시    9370.5    7067.0   16437.5    9356.0   11853.5   21209.5
3   강원특별자치도  삼척시    6306.0    5004.5   11310.5    7975.5   10248.5   18224.0
4   강원특별자치도   소계  173762.0  143713.5  317475.5  166736.5  205557.0  372293.5

         인구수                           소멸비율 소멸위기지역
구분        남자        여자         합계
0   102917.5  104956.5   207874.0  0.368465   True
1    13890.0   13189.5    27079.5  0.220891   True
2    44582.5   43227.5    87810.0  0.333200   True
3    31534.0   30499.5    62033.5  0.274610   True
4   762647.0  754712.5  1517359.5  0.386022   True

In [200]:
popl['시도'].unique()

array(['강릉시', '고성군', '동해시', '삼척시', '소계', '속초시', '양구군', '양양군', '영월군',
       '원주시', '인제군', '정선군', '철원군', '춘천시', '태백시', '평창군', '홍천군', '화천군',
       '횡성군', '가평군', '고양시', '과천시', '광명시', '광주시', '구리시', '군포시', '김포시',
       '남양주시', '동두천시', '부천시', '성남시', '수원시', '시흥시', '안산시', '안성시', '안양시',
       '양주시', '양평군', '여주시', '연천군', '오산시', '용인시', '의왕시', '의정부시', '이천시',
       '파주시', '평택시', '포천시', '하남시', '화성시', '거제시', '거창군', '김해시', '남해군',
       '밀양시', '사천시', '산청군', '양산시', '의령군', '진주시', '창녕군', '창원시', '통영시',
       '하동군', '함안군', '함양군', '합천군', '경산시', '경주시', '고령군', '구미시', '김천시',
       '문경시', '봉화군', '상주시', '성주군', '안동시', '영덕군', '영양군', '영주시', '영천시',
       '예천군', '울릉군', '울진군', '의성군', '청도군', '청송군', '칠곡군', '포항시', '광산구',
       '남구', '동구', '북구', '서구', '군위군', '달서구', '달성군', '수성구', '중구', '대덕구',
       '유성구', '강서구', '금정구', '기장군', '동래구', '부산진구', '사상구', '사하구', '수영구',
       '연제구', '영도구', '해운대구', '강남구', '강동구', '강북구', '관악구', '광진구', '구로구',
       '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구',
       '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중랑구', '세종특별자치시',
       '울주군', '강화군', '계양구', '남동구', '미추홀구', '부평구', '연수구', '옹진군', '강진군',
       '고흥군', '곡성군', '광양시', '구례군', '나주시', '담양군', '목포시', '무안군', '보성군',
       '순천시', '신안군', '여수시', '영광군', '영암군', '완도군', '장성군', '장흥군', '진도군',
       '함평군', '해남군', '화순군', '고창군', '군산시', '김제시', '남원시', '무주군', '부안군',
       '순창군', '완주군', '익산시', '임실군', '장수군', '전주시', '정읍시', '진안군', '서귀포시',
       '제주시', '계룡시', '공주시', '금산군', '논산시', '당진시', '보령시', '부여군', '서산시',
       '서천군', '아산시', '예산군', '천안시', '청양군', '태안군', '홍성군', '괴산군', '단양군',
       '보은군', '영동군', '옥천군', '음성군', '제천시', '증평군', '진천군', '청주시', '충주시'],
      dtype=object)

In [201]:
popl['시도'].str[0:2]

0      강릉
1      고성
2      동해
3      삼척
4      소계
5      속초
6      양구
7      양양
8      영월
9      원주
10     인제
11     정선
12     철원
13     춘천
14     태백
15     평창
16     홍천
17     화천
18     횡성
19     가평
20     고양
21     과천
22     광명
23     광주
24     구리
25     군포
26     김포
27     남양
28     동두
29     부천
30     성남
31     소계
32     수원
33     시흥
34     안산
35     안성
36     안양
37     양주
38     양평
39     여주
40     연천
41     오산
42     용인
43     의왕
44     의정
45     이천
46     파주
47     평택
48     포천
49     하남
50     화성
51     거제
52     거창
53     고성
54     김해
55     남해
56     밀양
57     사천
58     산청
59     소계
60     양산
61     의령
62     진주
63     창녕
64     창원
65     통영
66     하동
67     함안
68     함양
69     합천
70     경산
71     경주
72     고령
73     구미
74     김천
75     문경
76     봉화
77     상주
78     성주
79     소계
80     안동
81     영덕
82     영양
83     영주
84     영천
85     예천
86     울릉
87     울진
88     의성
89     청도
90     청송
91     칠곡
92     포항
93     광산
94     남구
95     동구
96     북구
97     서구
98     소계
99     군위
100    남구
101    달서
102    달성
103    동구
104    북구
105    서구
106    소계
107    수성
108    중구
109    대덕
110    동구
111    서구
112    소계
113    유성
114    중구
115    강서
116    금정
117    기장
118    남구
119    동구
120    동래
121    부산
122    북구
123    사상
124    사하
125    서구
126    소계
127    수영
128    연제
129    영도
130    중구
131    해운
132    강남
133    강동
134    강북
135    강서
136    관악
137    광진
138    구로
139    금천
140    노원
141    도봉
142    동대
143    동작
144    마포
145    서대
146    서초
147    성동
148    성북
149    소계
150    송파
151    양천
152    영등
153    용산
154    은평
155    종로
156    중구
157    중랑
158    세종
159    소계
160    남구
161    동구
162    북구
163    소계
164    울주
165    중구
166    강화
167    계양
168    남동
169    동구
170    미추
171    부평
172    서구
173    소계
174    연수
175    옹진
176    중구
177    소계
178    강진
179    고흥
180    곡성
181    광양
182    구례
183    나주
184    담양
185    목포
186    무안
187    보성
188    소계
189    순천
190    신안
191    여수
192    영광
193    영암
194    완도
195    장성
196    장흥
197    진도
198    함평
199    해남
200    화순
201    고창
202    군산
203    김제
204    남원
205    무주
206    부안
207    소계
208    순창
209    완주
210    익산
211    임실
212    장수
213    전주
214    정읍
215    진안
216    서귀
217    소계
218    제주
219    계룡
220    공주
221    금산
222    논산
223    당진
224    보령
225    부여
226    서산
227    서천
228    소계
229    아산
230    예산
231    천안
232    청양
233    태안
234    홍성
235    괴산
236    단양
237    보은
238    소계
239    영동
240    옥천
241    음성
242    제천
243    증평
244    진천
245    청주
246    충주
Name: 시도, dtype: object

In [202]:
popl['id'] = popl['시도'].str[0:2]

In [203]:
popl.head()

       광역시도   시도    20-39세                         65세이상                      \
구분                      남자        여자        합계        남자        여자        합계
0   강원특별자치도  강릉시   22929.0   19342.0   42271.0   22833.0   29660.5   52493.5
1   강원특별자치도  고성군    2829.0    1955.0    4784.0    3912.5    4938.0    8850.5
2   강원특별자치도  동해시    9370.5    7067.0   16437.5    9356.0   11853.5   21209.5
3   강원특별자치도  삼척시    6306.0    5004.5   11310.5    7975.5   10248.5   18224.0
4   강원특별자치도   소계  173762.0  143713.5  317475.5  166736.5  205557.0  372293.5

         인구수                           소멸비율 소멸위기지역  id
구분        남자        여자         합계
0   102917.5  104956.5   207874.0  0.368465   True  강릉
1    13890.0   13189.5    27079.5  0.220891   True  고성
2    44582.5   43227.5    87810.0  0.333200   True  동해
3    31534.0   30499.5    62033.5  0.274610   True  삼척
4   762647.0  754712.5  1517359.5  0.386022   True  소계

In [204]:
popl_map = popl.set_index('id', inplace=True)

In [213]:
popl

       광역시도       시도     20-39세                             65세이상             \
구분                           남자         여자          합계         남자         여자
id
강릉  강원특별자치도      강릉시    22929.0    19342.0     42271.0    22833.0    29660.5
고성  강원특별자치도      고성군     2829.0     1955.0      4784.0     3912.5     4938.0
동해  강원특별자치도      동해시     9370.5     7067.0     16437.5     9356.0    11853.5
삼척  강원특별자치도      삼척시     6306.0     5004.5     11310.5     7975.5    10248.5
소계  강원특별자치도       소계   173762.0   143713.5    317475.5   166736.5   205557.0
속초  강원특별자치도      속초시     9253.0     7392.5     16645.5     8208.5    10547.0
양구  강원특별자치도      양구군     2773.0     1815.5      4588.5     2462.5     2878.5
양양  강원특별자치도      양양군     2372.5     1709.5      4082.0     4306.5     5145.0
영월  강원특별자치도      영월군     2790.0     2215.5      5005.5     5971.0     6843.0
원주  강원특별자치도      원주시    45409.5    41556.5     86966.0    29435.5    36646.0
인제  강원특별자치도      인제군     4861.0     2767.0      7628.0     3730.0     4004.0
정선  강원특별자치도      정선군     2568.5     1879.5      4448.0     5243.0     6131.0
철원  강원특별자치도      철원군     5140.0     3384.5      8524.5     4916.0     6257.0
춘천  강원특별자치도      춘천시    37462.0    33480.5     70942.5    25904.5    33467.5
태백  강원특별자치도      태백시     3226.5     2477.5      5704.0     4993.0     6494.5
평창  강원특별자치도      평창군     3277.0     2343.0      5620.0     6520.0     7213.5
홍천  강원특별자치도      홍천군     6378.5     4658.5     11037.0    10286.5    11385.0
화천  강원특별자치도      화천군     3441.5     1990.0      5431.5     2872.0     3328.0
횡성  강원특별자치도      횡성군     3374.5     2675.0      6049.5     7810.5     8516.5
가평      경기도      가평군     6238.5     4827.5     11066.0     9071.5    10017.5
고양      경기도      고양시   137950.5   136549.0    274499.5    78028.5    98388.0
과천      경기도      과천시    10938.0    11075.5     22013.5     5531.5     6545.0
광명      경기도      광명시    35493.5    33682.5     69176.0    20994.5    26780.0
광주      경기도      광주시    49094.0    44172.5     93266.5    31118.0    34924.0
구리      경기도      구리시    23859.0    23034.0     46893.0    14448.5    17356.5
군포      경기도      군포시    35642.5    32011.0     67653.5    19968.0    24598.0
김포      경기도      김포시    57185.5    56922.0    114107.5    33364.5    40032.0
남양      경기도     남양주시    83898.5    81175.0    165073.5    55790.5    68713.5
동두      경기도     동두천시     9627.0     8253.5     17880.5     9330.0    12305.5
부천      경기도      부천시   103409.5    97530.5    200940.0    62544.0    75437.0
성남      경기도      성남시   127006.5   120576.5    247583.0    70120.0    84999.0
소계      경기도       소계  1850787.0  1685019.0   3535806.0   983155.0  1190222.0
수원      경기도      수원시   187795.0   169525.0    357320.0    71842.5    89354.0
시흥      경기도      시흥시    74522.5    63493.0    138015.5    28629.5    33228.5
안산      경기도      안산시    93336.0    79502.5    172838.5    41133.0    48714.5
안성      경기도      안성시    24472.5    19777.5     44250.0    17749.0    21411.0
안양      경기도      안양시    76379.0    71379.5    147758.5    41967.0    50832.0
양주      경기도      양주시    34914.0    31985.5     66899.5    21835.5    26094.5
양평      경기도      양평군    10827.0     9355.5     20182.5    17849.0    19847.0
여주      경기도      여주시    11991.0    10232.5     22223.5    13793.5    15649.5
연천      경기도      연천군     5053.5     3190.5      8244.0     5950.5     7061.5
오산      경기도      오산시    35992.0    29382.0     65374.0    12517.5    15548.0
용인      경기도      용인시   136404.5   129015.0    265419.5    75417.5    93382.5
의왕      경기도      의왕시    21566.5    20042.5     41609.0    12454.0    14474.5
의정      경기도     의정부시    59805.5    58008.0    117813.5    36685.5    47105.5
이천      경기도      이천시    32925.5    25653.5     58579.0    17566.0    20232.5
파주      경기도      파주시    66701.0    59349.5    126050.5    35519.5    44534.5
평택      경기도      평택시    95338.0    74041.5    169379.5    35443.0    43980.5
포천      경기도      포천시    16522.0    12605.5     29127.5    17060.0    18683.0
하남      경기도      하남시    42655.5    43465.5     86121.0    22744.0    25976.0
화성      경기도      화성시   143243.0   125205.0    268448.0    46689.0    54016.5
거제     경상남도      거제시    24375.5    20451.0     44826.5    16375.5    18344.0
거창     경상남도      거창군     5244.5     4109.5      9354.0     7732.5    10910.0
고성     경상남도      고성군     3405.0     2486.5      5891.5     7597.0     9914.0
김해     경상남도      김해시    65371.5    56232.5    121604.0    34543.5    42568.5
남해     경상남도      남해군     2679.5     1860.0      4539.5     6920.5     9836.0
밀양     경상남도      밀양시     8437.0     6571.5     15008.5    14832.5    19313.5
사천     경상남도      사천시    11526.0     8231.0     19757.0    11514.0    15874.0
산청     경상남도      산청군     2027.0     1570.0      3597.0     6003.0     7839.0
소계     경상남도       소계   360670.0   299751.5    660421.5   300373.0   381473.0
양산     경상남도      양산시    41378.5    37314.0     78692.5    27423.5    34109.0
의령     경상남도      의령군     1647.5     1255.0      2902.5     4403.5     6054.5
진주     경상남도      진주시    42619.0    36513.0     79132.0    29146.5    39101.5
창녕     경상남도      창녕군     4144.5     2942.0      7086.5     8959.0    11898.5
창원     경상남도      창원시   125328.5   102335.5    227664.0    83597.0   101313.5
통영     경상남도      통영시    10200.5     8641.0     18841.5    12982.0    16365.5
하동     경상남도      하동군     2612.5     1929.0      4541.5     7140.5     9315.5
함안     경상남도      함안군     4792.5     3574.0      8366.5     8056.5    10051.5
함양     경상남도      함양군     2447.0     1941.5      4388.5     5765.5     8206.0
합천     경상남도      합천군     2433.5     1794.5      4228.0     7380.5    10458.5
경산     경상북도      경산시    36029.0    29723.5     65752.5    23335.5    29832.0
경주     경상북도      경주시    24843.5    20106.0     44949.5    28348.0    36964.5
고령     경상북도      고령군     2181.5     1661.0      3842.5     4970.5     6072.0
구미     경상북도      구미시    59393.5    46905.0    106298.5    22631.5    27546.5
김천     경상북도      김천시    13972.0    11469.0     25441.0    15677.0    20637.5
문경     경상북도      문경시     5476.0     4503.0      9979.0     9933.0    13572.5
봉화     경상북도      봉화군     1732.5     1195.5      2928.0     5544.5     6718.5
상주     경상북도      상주시     7244.5     5692.5     12937.0    13896.0    18985.5
성주     경상북도      성주군     3143.5     2203.0      5346.5     7222.0     8353.5
소계     경상북도       소계   278172.5   219806.0    497978.5   281030.5   358758.5
안동     경상북도      안동시    15675.5    13466.0     29141.5    18425.0    24316.5
영덕     경상북도      영덕군     2095.0     1647.5      3742.5     5729.5     8478.5
영양     경상북도      영양군      950.0      743.5      1693.5     2745.5     3735.5
영주     경상북도      영주시     9122.0     7089.0     16211.0    13304.0    17460.5
영천     경상북도      영천시     9319.5     6944.0     16263.5    14291.5    17897.5
예천     경상북도      예천군     4599.0     4003.0      8602.0     7744.0    10154.5
울릉     경상북도      울릉군     1004.0      573.5      1577.5     1244.0     1403.0
울진     경상북도      울진군     4433.0     3158.0      7591.0     6109.0     8492.0
의성     경상북도      의성군     2924.5     2195.5      5120.0     9835.0    12882.5
청도     경상북도      청도군     2431.5     1896.0      4327.5     7780.5     9718.0
청송     경상북도      청송군     1688.0     1087.5      2775.5     4448.0     5672.0
칠곡     경상북도      칠곡군    11958.5     9008.0     20966.5     9452.5    11692.5
포항     경상북도      포항시    57956.0    44536.0    102492.0    48364.0    58173.0
광산    광주광역시      광산구    54470.5    48832.5    103303.0    19817.0    25748.0
남구    광주광역시       남구    23633.5    23117.0     46750.5    18520.5    24685.0
동구    광주광역시       동구    14731.0    14079.0     28810.0    10707.0    13657.5
북구    광주광역시       북구    56238.0    51241.5    107479.5    33247.0    43170.0
서구    광주광역시       서구    37514.5    35386.5     72901.0    21220.0    27901.0
소계    광주광역시       소계   186587.5   172656.5    359244.0   103511.5   135161.5
군위    대구광역시      군위군     1334.5      888.5      2223.0     4770.0     5630.0
남구    대구광역시       남구    17114.0    16454.5     33568.5    15329.0    21528.5
달서    대구광역시      달서구    66065.5    58546.0    124611.5    42394.5    54175.0
달성    대구광역시      달성군    32922.0    27705.0     60627.0    18637.5    22745.0
동구    대구광역시       동구    42506.5    37908.5     80415.0    33440.0    44887.5
북구    대구광역시       북구    55317.0    47436.5    102753.5    32708.5    42766.5
서구    대구광역시       서구    19441.5    15742.5     35184.0    18570.5    25245.0
소계    대구광역시       소계   293942.5   261108.0    555050.5   205889.0   270811.5
수성    대구광역시      수성구    45137.5    41776.0     86913.5    32879.0    43616.5
중구    대구광역시       중구    14104.0    14650.5     28754.5     7160.0    10217.5
대덕    대전광역시      대덕구    22291.5    17971.5     40263.0    15187.5    18676.0
동구    대전광역시       동구    28125.0    24512.0     52637.0    21377.5    27121.5
서구    대전광역시       서구    66192.0    63324.5    129516.5    32547.0    40462.5
소계    대전광역시       소계   202197.0   182429.5    384626.5   111469.0   138637.5
유성    대전광역시      유성구    59375.0    51622.0    110997.0    19907.5    23459.5
중구    대전광역시       중구    26213.5    24999.5     51213.0    22449.5    28918.0
강서    부산광역시      강서구    17574.0    16057.5     33631.5     9855.5    10790.0
금정    부산광역시      금정구    26311.0    22612.5     48923.5    24015.0    30757.0
기장    부산광역시      기장군    19328.5    17976.0     37304.5    14443.5    18941.5
남구    부산광역시       남구    30533.0    28115.5     58648.5    25945.5    33903.5
동구    부산광역시       동구    10041.5     9865.0     19906.5    10665.5    14501.0
동래    부산광역시      동래구    30188.5    29518.0     59706.5    25878.5    32988.0
부산    부산광역시     부산진구    48669.0    50455.0     99124.0    34943.0    45577.0
북구    부산광역시       북구    32188.5    28651.0     60839.5    27354.5    33229.0
사상    부산광역시      사상구    25499.0    22212.5     47711.5    21282.5    25606.0
사하    부산광역시      사하구    34709.0    29979.5     64688.5    31489.0    38888.0
서구    부산광역시       서구    10910.0    11166.5     22076.5    12620.5    16957.5
소계    부산광역시       소계   388220.0   367166.0    755386.0   332443.0   424992.0
수영    부산광역시      수영구    21802.0    22981.0     44783.0    18298.5    24573.5
연제    부산광역시      연제구    24731.5    24883.0     49614.5    20692.5    26628.5
영도    부산광역시      영도구    10196.0     8558.0     18754.0    14649.0    19270.5
중구    부산광역시       중구     4728.5     4678.5      9407.0     5093.0     6777.5
해운    부산광역시     해운대구    40810.0    39456.5     80266.5    35217.0    45603.5
강남    서울특별시      강남구    68355.0    77186.5    145541.5    39037.5    47853.0
강동    서울특별시      강동구    61809.5    64816.5    126626.0    38952.0    46353.5
강북    서울특별시      강북구    35722.0    35927.5     71649.5    29851.0    39365.0
강서    서울특별시      강서구    82616.0    90537.0    173153.0    45668.5    57734.5
관악    서울특별시      관악구   100644.0    93592.0    194236.0    38049.5    47608.0
광진    서울특별시      광진구    54063.0    58510.0    112573.0    25631.5    31549.5
구로    서울특별시      구로구    54823.0    55476.0    110299.0    35824.0    43632.0
금천    서울특별시      금천구    37405.5    34867.0     72272.5    20806.0    24575.5
노원    서울특별시      노원구    63430.5    62315.0    125745.5    41516.5    55935.0
도봉    서울특별시      도봉구    37196.5    36507.5     73704.0    31961.0    39532.0
동대    서울특별시     동대문구    51877.5    53678.5    105556.0    30059.0    37289.0
동작    서울특별시      동작구    60801.0    61998.5    122799.5    30790.5    39748.5
마포    서울특별시      마포구    55359.5    66167.5    121527.0    24272.5    33359.5
서대    서울특별시     서대문구    43824.5    48139.0     91963.5    24794.5    33063.5
서초    서울특별시      서초구    49522.5    56179.0    105701.5    29778.5    36016.5
성동    서울특별시      성동구    41665.0    43984.0     85649.0    21879.5    27602.0
성북    서울특별시      성북구    57870.5    61755.5    119626.0    34985.5    45824.0
소계    서울특별시       소계  1341060.0  1412954.0   2754014.0   777141.5   973956.5
송파    서울특별시      송파구    88915.5    98442.5    187358.0    50552.5    59209.0
양천    서울특별시      양천구    51785.0    51784.5    103569.5    34801.5    42527.5
영등    서울특별시     영등포구    61385.5    66128.5    127514.0    30095.0    36201.0
용산    서울특별시      용산구    31283.0    34187.0     65470.0    16673.0    21349.5
은평    서울특별시      은평구    60238.5    66107.0    126345.5    40811.5    53810.5
종로    서울특별시      종로구    19605.5    20873.0     40478.5    12827.0    15570.0
중구    서울특별시       중구    18226.5    19942.5     38169.0    11261.5    14145.0
중랑    서울특별시      중랑구    52635.0    53852.0    106487.0    36262.0    44103.0
세종  세종특별자치시  세종특별자치시    48086.5    48283.5     96370.0    19675.0    23830.5
소계  세종특별자치시       소계    48086.5    48283.5     96370.0    19675.0    23830.5
남구    울산광역시       남구    43246.5    34599.5     77846.0    22679.5    26168.0
동구    울산광역시       동구    18834.5    14709.5     33544.0    12663.0    13595.0
북구    울산광역시       북구    29486.0    23234.0     52720.0    11406.0    12861.5
소계    울산광역시       소계   142497.0   113299.5    255796.5    84302.5    96901.0
울주    울산광역시      울주군    25739.5    20269.0     46008.5    19235.5    22070.0
중구    울산광역시       중구    25190.5    20487.5     45678.0    18318.5    22206.5
강화    인천광역시      강화군     5076.5     4192.5      9269.0    12092.0    14009.5
계양    인천광역시      계양구    37512.5    33666.5     71179.0    22186.5    26443.5
남동    인천광역시      남동구    62031.5    56987.0    119018.5    38680.5    48979.0
동구    인천광역시       동구     6570.0     5733.5     12303.5     6643.0     8741.0
미추    인천광역시     미추홀구    56800.0    50027.0    106827.0    35702.0    45683.5
부평    인천광역시      부평구    67971.5    64198.0    132169.5    39238.0    50064.5
서구    인천광역시       서구    86169.0    82802.0    168971.0    36836.5    43448.0
소계    인천광역시       소계   400947.5   370962.5    771910.0   228801.0   281179.5
연수    인천광역시      연수구    51477.0    49997.5    101474.5    22749.0    26564.0
옹진    인천광역시      옹진군     2844.5     1262.5      4107.0     3157.0     3352.0
중구    인천광역시       중구    24495.0    22096.0     46591.0    11516.5    13894.5
소계       전국       소계  6582521.5  6049518.5  12632040.0  4396558.5  5502988.5
강진     전라남도      강진군     2424.0     2003.5      4427.5     5210.5     7265.5
고흥     전라남도      고흥군     3649.5     2832.0      6481.5    11244.5    15746.0
곡성     전라남도      곡성군     1893.0     1588.0      3481.0     4469.5     6051.5
광양     전라남도      광양시    20525.5    15865.0     36390.5    11123.0    13071.0
구례     전라남도      구례군     1549.5     1326.0      2875.5     3845.0     5429.5
나주     전라남도      나주시    13026.5    12088.5     25115.0    12278.0    16190.5
담양     전라남도      담양군     3792.5     3136.5      6929.0     6782.0     8706.5
목포     전라남도      목포시    23694.5    21006.5     44701.0    18641.0    24568.5
무안     전라남도      무안군    10193.5     9424.0     19617.5     8253.0    10891.0
보성     전라남도      보성군     2411.5     1877.0      4288.5     6586.5     9332.0
소계     전라남도       소계   186191.5   156024.5    342216.0   205052.0   269693.5
순천     전라남도      순천시    34507.5    30192.5     64700.0    22819.5    28735.0
신안     전라남도      신안군     2826.5     1794.0      4620.5     6703.5     8293.0
여수     전라남도      여수시    31596.5    25235.0     56831.5    27722.0    34360.0
영광     전라남도      영광군     4811.5     4194.5      9006.0     6893.0     9459.5
영암     전라남도      영암군     4825.0     3648.5      8473.5     6522.5     8821.0
완도     전라남도      완도군     3403.0     2624.0      6027.0     7133.0     9668.0
장성     전라남도      장성군     3765.5     2853.0      6618.5     6190.0     7993.0
장흥     전라남도      장흥군     2580.5     2101.0      4681.5     5420.5     7818.5
진도     전라남도      진도군     2202.0     1782.5      3984.5     4428.5     6204.0
함평     전라남도      함평군     2163.0     1658.5      3821.5     5142.0     7093.5
해남     전라남도      해남군     4831.5     3744.5      8576.0     9867.0    13466.5
화순     전라남도      화순군     5519.0     5049.5     10568.5     7777.5    10529.5
고창  전북특별자치도      고창군     3651.0     2929.5      6580.5     8350.5    11473.0
군산  전북특별자치도      군산시    28268.5    23702.5     51971.0    25745.0    32024.0
김제  전북특별자치도      김제시     7092.5     5897.0     12989.5    11874.5    16083.5
남원  전북특별자치도      남원시     6300.0     5398.5     11698.5    10258.5    13964.0
무주  전북특별자치도      무주군     1640.0     1319.0      2959.0     3690.5     4881.0
부안  전북특별자치도      부안군     3669.0     2861.0      6530.0     7817.0    10438.5
소계  전북특별자치도       소계   190569.5   167273.0    357842.5   185930.5   241376.5
순창  전북특별자치도      순창군     1919.5     1682.0      3601.5     4110.5     5747.0
완주  전북특별자치도      완주군    10658.5     9150.0     19808.5    11140.0    13348.5
익산  전북특별자치도      익산시    30629.5    26374.0     57003.5    27539.5    35258.5
임실  전북특별자치도      임실군     1860.5     1437.5      3298.0     4594.5     5779.0
장수  전북특별자치도      장수군     1382.0     1122.0      2504.0     3485.5     4590.5
전주  전북특별자치도      전주시    82721.5    76492.5    159214.0    49463.0    64238.5
정읍  전북특별자치도      정읍시     9189.5     7538.5     16728.0    13560.0    18372.5
진안  전북특별자치도      진안군     1587.5     1369.0      2956.5     4301.5     5178.0
서귀  제주특별자치도     서귀포시    17982.5    16348.5     34331.0    17821.0    22589.5
소계  제주특별자치도       소계    77607.0    71756.5    149363.5    53839.5    68537.0
제주  제주특별자치도      제주시    59624.5    55408.0    115032.5    36018.5    45947.5
계룡     충청남도      계룡시     5502.5     4710.0     10212.5     2990.0     3726.0
공주     충청남도      공주시    10120.5     8901.5     19022.0    13828.0    17014.5
금산     충청남도      금산군     3552.5     2863.0      6415.5     7871.5     9783.0
논산     충청남도      논산시    10151.5     8338.5     18490.0    14774.0    18938.5
당진     충청남도      당진시    20520.0    14667.5     35187.5    16336.5    19416.5
보령     충청남도      보령시     8756.0     6776.0     15532.0    12628.0    16119.0
부여     충청남도      부여군     4307.0     3369.5      7676.5    10617.0    13397.5
서산     충청남도      서산시    21945.5    15273.5     37219.0    16846.0    20522.0
서천     충청남도      서천군     3376.5     2565.0      5941.5     8637.0    11270.5
소계     충청남도       소계   260105.5   213178.0    473283.5   205537.5   255380.0
아산     충청남도      아산시    48871.5    40803.5     89675.0    22653.0    28219.5
예산     충청남도      예산군     6728.0     5437.0     12165.0    11945.0    14980.5
천안     충청남도      천안시    99260.0    85915.0    185175.0    39895.5    48500.0
청양     충청남도      청양군     2413.5     1784.0      4197.5     5293.0     6531.0
태안     충청남도      태안군     4755.0     3432.0      8187.0     9758.5    12128.0
홍성     충청남도      홍성군     9845.5     8342.0     18187.5    11464.5    14833.5
괴산     충청북도      괴산군     2395.0     1716.5      4111.5     6877.5     7768.0
단양     충청북도      단양군     1941.0     1457.0      3398.0     4700.5     5517.0
보은     충청북도      보은군     2097.0     1578.5      3675.5     5444.5     6793.0
소계     충청북도       소계   201118.5   164137.0    365255.5   151671.5   186521.0
영동     충청북도      영동군     3233.5     2545.5      5779.0     7295.5     8971.5
옥천     충청북도      옥천군     3767.0     3043.0      6810.0     7640.5     9154.0
음성     충청북도      음성군     9750.5     7159.5     16910.0    10800.5    12374.0
제천     충청북도      제천시    13833.0    11258.5     25091.5    15511.0    18791.5
증평     충청북도      증평군     4911.0     3689.5      8600.5     3484.5     4328.5
진천     충청북도      진천군    10996.0     8241.0     19237.0     7341.5     8876.0
청주     충청북도      청주시   123468.5   104501.0    227969.5    60832.0    76794.5
충주     충청북도      충주시    24726.0    18947.0     43673.0    21743.5    27153.0

                      인구수                              소멸비율 소멸위기지역
구분         합계          남자          여자          합계
id
강릉    52493.5    102917.5    104956.5    207874.0  0.368465   True
고성     8850.5     13890.0     13189.5     27079.5  0.220891   True
동해    21209.5     44582.5     43227.5     87810.0  0.333200   True
삼척    18224.0     31534.0     30499.5     62033.5  0.274610   True
소계   372293.5    762647.0    754712.5   1517359.5  0.386022   True
속초    18755.5     40077.0     41057.5     81134.5  0.394151   True
양구     5341.0     10901.5      9903.5     20805.0  0.339918   True
양양     9451.5     14092.5     13433.0     27525.5  0.180871   True
영월    12814.0     19072.5     17788.5     36861.0  0.172897   True
원주    66081.5    178287.0    182094.5    360381.5  0.628867  False

In [205]:
popl['소멸위기지역'].value_counts()

True     137
False    110
Name: 소멸위기지역, dtype: int64

In [206]:
popl['시도'].value_counts()

소계         18
동구          6
중구          6
서구          5
북구          4
남구          4
고성군         2
강서구         2
남동구         1
연수구         1
부평구         1
미추홀구        1
강릉시         1
계양구         1
울주군         1
세종특별자치시     1
중랑구         1
종로구         1
강화군         1
옹진군         1
용산구         1
강진군         1
고흥군         1
곡성군         1
광양시         1
구례군         1
나주시         1
담양군         1
목포시         1
무안군         1
은평구         1
성북구         1
영등포구        1
양천구         1
영도구         1
해운대구        1
강남구         1
강동구         1
강북구         1
관악구         1
광진구         1
구로구         1
금천구         1
노원구         1
도봉구         1
동대문구        1
동작구         1
마포구         1
서대문구        1
서초구         1
성동구         1
순천시         1
송파구         1
보성군         1
신안군         1
수영구         1
계룡시         1
금산군         1
논산시         1
당진시         1
보령시         1
부여군         1
서산시         1
서천군         1
아산시         1
예산군         1
천안시         1
청양군         1
태안군         1
홍성군         1
괴산군         1
단양군         1
보은군         1
영동군         1
옥천군         1
음성군         1
제천시         1
증평군         1
진천군         1
청주시         1
공주시         1
제주시         1
여수시         1
서귀포시        1
영광군         1
영암군         1
완도군         1
장성군         1
장흥군         1
진도군         1
함평군         1
해남군         1
화순군         1
고창군         1
군산시         1
김제시         1
남원시         1
무주군         1
부안군         1
순창군         1
완주군         1
익산시         1
임실군         1
장수군         1
전주시         1
정읍시         1
진안군         1
연제구         1
동래구         1
사하구         1
김포시         1
동두천시        1
부천시         1
성남시         1
수원시         1
시흥시         1
안산시         1
안성시         1
안양시         1
양주시         1
양평군         1
여주시         1
연천군         1
오산시         1
용인시         1
의왕시         1
의정부시        1
이천시         1
파주시         1
평택시         1
포천시         1
하남시         1
남양주시        1
군포시         1
거제시         1
구리시         1
동해시         1
삼척시         1
속초시         1
양구군         1
양양군         1
영월군         1
원주시         1
인제군         1
정선군         1
철원군         1
춘천시         1
태백시         1
평창군         1
홍천군         1
화천군         1
횡성군         1
가평군         1
고양시         1
과천시         1
광명시         1
광주시         1
화성시         1
거창군         1
사상구         1
안동시         1
영양군         1
영주시         1
영천시         1
예천군         1
울릉군         1
울진군         1
의성군         1
청도군         1
청송군         1
칠곡군         1
포항시         1
광산구         1
군위군         1
달서구         1
달성군         1
수성구         1
대덕구         1
유성구         1
금정구         1
기장군         1
부산진구        1
영덕군         1
성주군         1
김해시         1
상주시         1
남해군         1
밀양시         1
사천시         1
산청군         1
양산시         1
의령군         1
진주시         1
창녕군         1
창원시         1
통영시         1
하동군         1
함안군         1
함양군         1
합천군         1
경산시         1
경주시         1
고령군         1
구미시         1
김천시         1
문경시         1
봉화군         1
충주시         1
Name: 시도, dtype: int64

In [207]:
popl1 = popl[popl['시도'] != '소계']

In [208]:
popl1['시도'].value_counts()

동구         6
중구         6
서구         5
남구         4
북구         4
강서구        2
고성군        2
세종특별자치시    1
울주군        1
계양구        1
중랑구        1
남동구        1
미추홀구       1
부평구        1
연수구        1
종로구        1
강화군        1
강릉시        1
용산구        1
옹진군        1
강진군        1
고흥군        1
곡성군        1
광양시        1
구례군        1
나주시        1
담양군        1
목포시        1
무안군        1
은평구        1
성북구        1
영등포구       1
양천구        1
영도구        1
해운대구       1
강남구        1
강동구        1
강북구        1
관악구        1
광진구        1
구로구        1
금천구        1
노원구        1
도봉구        1
동대문구       1
동작구        1
마포구        1
서대문구       1
서초구        1
성동구        1
순천시        1
송파구        1
보성군        1
신안군        1
수영구        1
계룡시        1
금산군        1
논산시        1
당진시        1
보령시        1
부여군        1
서산시        1
서천군        1
아산시        1
예산군        1
천안시        1
청양군        1
태안군        1
홍성군        1
괴산군        1
단양군        1
보은군        1
영동군        1
옥천군        1
음성군        1
제천시        1
증평군        1
진천군        1
청주시        1
공주시        1
제주시        1
여수시        1
서귀포시       1
영광군        1
영암군        1
완도군        1
장성군        1
장흥군        1
진도군        1
함평군        1
해남군        1
화순군        1
고창군        1
군산시        1
김제시        1
남원시        1
무주군        1
부안군        1
순창군        1
완주군        1
익산시        1
임실군        1
장수군        1
전주시        1
정읍시        1
진안군        1
연제구        1
동래구        1
사하구        1
김포시        1
동두천시       1
부천시        1
성남시        1
수원시        1
시흥시        1
안산시        1
안성시        1
안양시        1
양주시        1
양평군        1
여주시        1
연천군        1
오산시        1
용인시        1
의왕시        1
의정부시       1
이천시        1
파주시        1
평택시        1
포천시        1
하남시        1
남양주시       1
군포시        1
거제시        1
구리시        1
동해시        1
삼척시        1
속초시        1
양구군        1
양양군        1
영월군        1
원주시        1
인제군        1
정선군        1
철원군        1
춘천시        1
태백시        1
평창군        1
홍천군        1
화천군        1
횡성군        1
가평군        1
고양시        1
과천시        1
광명시        1
광주시        1
화성시        1
거창군        1
사상구        1
안동시        1
영양군        1
영주시        1
영천시        1
예천군        1
울릉군        1
울진군        1
의성군        1
청도군        1
청송군        1
칠곡군        1
포항시        1
광산구        1
군위군        1
달서구        1
달성군        1
수성구        1
대덕구        1
유성구        1
금정구        1
기장군        1
부산진구       1
영덕군        1
성주군        1
김해시        1
상주시        1
남해군        1
밀양시        1
사천시        1
산청군        1
양산시        1
의령군        1
진주시        1
창녕군        1
창원시        1
통영시        1
하동군        1
함안군        1
함양군        1
합천군        1
경산시        1
경주시        1
고령군        1
구미시        1
김천시        1
문경시        1
봉화군        1
충주시        1
Name: 시도, dtype: int64

In [209]:
len(popl1[popl1['소멸위기지역']==True]) / len(popl1)

0.5633187772925764

In [210]:
popl

       광역시도       시도     20-39세                             65세이상             \
구분                           남자         여자          합계         남자         여자
id
강릉  강원특별자치도      강릉시    22929.0    19342.0     42271.0    22833.0    29660.5
고성  강원특별자치도      고성군     2829.0     1955.0      4784.0     3912.5     4938.0
동해  강원특별자치도      동해시     9370.5     7067.0     16437.5     9356.0    11853.5
삼척  강원특별자치도      삼척시     6306.0     5004.5     11310.5     7975.5    10248.5
소계  강원특별자치도       소계   173762.0   143713.5    317475.5   166736.5   205557.0
속초  강원특별자치도      속초시     9253.0     7392.5     16645.5     8208.5    10547.0
양구  강원특별자치도      양구군     2773.0     1815.5      4588.5     2462.5     2878.5
양양  강원특별자치도      양양군     2372.5     1709.5      4082.0     4306.5     5145.0
영월  강원특별자치도      영월군     2790.0     2215.5      5005.5     5971.0     6843.0
원주  강원특별자치도      원주시    45409.5    41556.5     86966.0    29435.5    36646.0
인제  강원특별자치도      인제군     4861.0     2767.0      7628.0     3730.0     4004.0
정선  강원특별자치도      정선군     2568.5     1879.5      4448.0     5243.0     6131.0
철원  강원특별자치도      철원군     5140.0     3384.5      8524.5     4916.0     6257.0
춘천  강원특별자치도      춘천시    37462.0    33480.5     70942.5    25904.5    33467.5
태백  강원특별자치도      태백시     3226.5     2477.5      5704.0     4993.0     6494.5
평창  강원특별자치도      평창군     3277.0     2343.0      5620.0     6520.0     7213.5
홍천  강원특별자치도      홍천군     6378.5     4658.5     11037.0    10286.5    11385.0
화천  강원특별자치도      화천군     3441.5     1990.0      5431.5     2872.0     3328.0
횡성  강원특별자치도      횡성군     3374.5     2675.0      6049.5     7810.5     8516.5
가평      경기도      가평군     6238.5     4827.5     11066.0     9071.5    10017.5
고양      경기도      고양시   137950.5   136549.0    274499.5    78028.5    98388.0
과천      경기도      과천시    10938.0    11075.5     22013.5     5531.5     6545.0
광명      경기도      광명시    35493.5    33682.5     69176.0    20994.5    26780.0
광주      경기도      광주시    49094.0    44172.5     93266.5    31118.0    34924.0
구리      경기도      구리시    23859.0    23034.0     46893.0    14448.5    17356.5
군포      경기도      군포시    35642.5    32011.0     67653.5    19968.0    24598.0
김포      경기도      김포시    57185.5    56922.0    114107.5    33364.5    40032.0
남양      경기도     남양주시    83898.5    81175.0    165073.5    55790.5    68713.5
동두      경기도     동두천시     9627.0     8253.5     17880.5     9330.0    12305.5
부천      경기도      부천시   103409.5    97530.5    200940.0    62544.0    75437.0
성남      경기도      성남시   127006.5   120576.5    247583.0    70120.0    84999.0
소계      경기도       소계  1850787.0  1685019.0   3535806.0   983155.0  1190222.0
수원      경기도      수원시   187795.0   169525.0    357320.0    71842.5    89354.0
시흥      경기도      시흥시    74522.5    63493.0    138015.5    28629.5    33228.5
안산      경기도      안산시    93336.0    79502.5    172838.5    41133.0    48714.5
안성      경기도      안성시    24472.5    19777.5     44250.0    17749.0    21411.0
안양      경기도      안양시    76379.0    71379.5    147758.5    41967.0    50832.0
양주      경기도      양주시    34914.0    31985.5     66899.5    21835.5    26094.5
양평      경기도      양평군    10827.0     9355.5     20182.5    17849.0    19847.0
여주      경기도      여주시    11991.0    10232.5     22223.5    13793.5    15649.5
연천      경기도      연천군     5053.5     3190.5      8244.0     5950.5     7061.5
오산      경기도      오산시    35992.0    29382.0     65374.0    12517.5    15548.0
용인      경기도      용인시   136404.5   129015.0    265419.5    75417.5    93382.5
의왕      경기도      의왕시    21566.5    20042.5     41609.0    12454.0    14474.5
의정      경기도     의정부시    59805.5    58008.0    117813.5    36685.5    47105.5
이천      경기도      이천시    32925.5    25653.5     58579.0    17566.0    20232.5
파주      경기도      파주시    66701.0    59349.5    126050.5    35519.5    44534.5
평택      경기도      평택시    95338.0    74041.5    169379.5    35443.0    43980.5
포천      경기도      포천시    16522.0    12605.5     29127.5    17060.0    18683.0
하남      경기도      하남시    42655.5    43465.5     86121.0    22744.0    25976.0
화성      경기도      화성시   143243.0   125205.0    268448.0    46689.0    54016.5
거제     경상남도      거제시    24375.5    20451.0     44826.5    16375.5    18344.0
거창     경상남도      거창군     5244.5     4109.5      9354.0     7732.5    10910.0
고성     경상남도      고성군     3405.0     2486.5      5891.5     7597.0     9914.0
김해     경상남도      김해시    65371.5    56232.5    121604.0    34543.5    42568.5
남해     경상남도      남해군     2679.5     1860.0      4539.5     6920.5     9836.0
밀양     경상남도      밀양시     8437.0     6571.5     15008.5    14832.5    19313.5
사천     경상남도      사천시    11526.0     8231.0     19757.0    11514.0    15874.0
산청     경상남도      산청군     2027.0     1570.0      3597.0     6003.0     7839.0
소계     경상남도       소계   360670.0   299751.5    660421.5   300373.0   381473.0
양산     경상남도      양산시    41378.5    37314.0     78692.5    27423.5    34109.0
의령     경상남도      의령군     1647.5     1255.0      2902.5     4403.5     6054.5
진주     경상남도      진주시    42619.0    36513.0     79132.0    29146.5    39101.5
창녕     경상남도      창녕군     4144.5     2942.0      7086.5     8959.0    11898.5
창원     경상남도      창원시   125328.5   102335.5    227664.0    83597.0   101313.5
통영     경상남도      통영시    10200.5     8641.0     18841.5    12982.0    16365.5
하동     경상남도      하동군     2612.5     1929.0      4541.5     7140.5     9315.5
함안     경상남도      함안군     4792.5     3574.0      8366.5     8056.5    10051.5
함양     경상남도      함양군     2447.0     1941.5      4388.5     5765.5     8206.0
합천     경상남도      합천군     2433.5     1794.5      4228.0     7380.5    10458.5
경산     경상북도      경산시    36029.0    29723.5     65752.5    23335.5    29832.0
경주     경상북도      경주시    24843.5    20106.0     44949.5    28348.0    36964.5
고령     경상북도      고령군     2181.5     1661.0      3842.5     4970.5     6072.0
구미     경상북도      구미시    59393.5    46905.0    106298.5    22631.5    27546.5
김천     경상북도      김천시    13972.0    11469.0     25441.0    15677.0    20637.5
문경     경상북도      문경시     5476.0     4503.0      9979.0     9933.0    13572.5
봉화     경상북도      봉화군     1732.5     1195.5      2928.0     5544.5     6718.5
상주     경상북도      상주시     7244.5     5692.5     12937.0    13896.0    18985.5
성주     경상북도      성주군     3143.5     2203.0      5346.5     7222.0     8353.5
소계     경상북도       소계   278172.5   219806.0    497978.5   281030.5   358758.5
안동     경상북도      안동시    15675.5    13466.0     29141.5    18425.0    24316.5
영덕     경상북도      영덕군     2095.0     1647.5      3742.5     5729.5     8478.5
영양     경상북도      영양군      950.0      743.5      1693.5     2745.5     3735.5
영주     경상북도      영주시     9122.0     7089.0     16211.0    13304.0    17460.5
영천     경상북도      영천시     9319.5     6944.0     16263.5    14291.5    17897.5
예천     경상북도      예천군     4599.0     4003.0      8602.0     7744.0    10154.5
울릉     경상북도      울릉군     1004.0      573.5      1577.5     1244.0     1403.0
울진     경상북도      울진군     4433.0     3158.0      7591.0     6109.0     8492.0
의성     경상북도      의성군     2924.5     2195.5      5120.0     9835.0    12882.5
청도     경상북도      청도군     2431.5     1896.0      4327.5     7780.5     9718.0
청송     경상북도      청송군     1688.0     1087.5      2775.5     4448.0     5672.0
칠곡     경상북도      칠곡군    11958.5     9008.0     20966.5     9452.5    11692.5
포항     경상북도      포항시    57956.0    44536.0    102492.0    48364.0    58173.0
광산    광주광역시      광산구    54470.5    48832.5    103303.0    19817.0    25748.0
남구    광주광역시       남구    23633.5    23117.0     46750.5    18520.5    24685.0
동구    광주광역시       동구    14731.0    14079.0     28810.0    10707.0    13657.5
북구    광주광역시       북구    56238.0    51241.5    107479.5    33247.0    43170.0
서구    광주광역시       서구    37514.5    35386.5     72901.0    21220.0    27901.0
소계    광주광역시       소계   186587.5   172656.5    359244.0   103511.5   135161.5
군위    대구광역시      군위군     1334.5      888.5      2223.0     4770.0     5630.0
남구    대구광역시       남구    17114.0    16454.5     33568.5    15329.0    21528.5
달서    대구광역시      달서구    66065.5    58546.0    124611.5    42394.5    54175.0
달성    대구광역시      달성군    32922.0    27705.0     60627.0    18637.5    22745.0
동구    대구광역시       동구    42506.5    37908.5     80415.0    33440.0    44887.5
북구    대구광역시       북구    55317.0    47436.5    102753.5    32708.5    42766.5
서구    대구광역시       서구    19441.5    15742.5     35184.0    18570.5    25245.0
소계    대구광역시       소계   293942.5   261108.0    555050.5   205889.0   270811.5
수성    대구광역시      수성구    45137.5    41776.0     86913.5    32879.0    43616.5
중구    대구광역시       중구    14104.0    14650.5     28754.5     7160.0    10217.5
대덕    대전광역시      대덕구    22291.5    17971.5     40263.0    15187.5    18676.0
동구    대전광역시       동구    28125.0    24512.0     52637.0    21377.5    27121.5
서구    대전광역시       서구    66192.0    63324.5    129516.5    32547.0    40462.5
소계    대전광역시       소계   202197.0   182429.5    384626.5   111469.0   138637.5
유성    대전광역시      유성구    59375.0    51622.0    110997.0    19907.5    23459.5
중구    대전광역시       중구    26213.5    24999.5     51213.0    22449.5    28918.0
강서    부산광역시      강서구    17574.0    16057.5     33631.5     9855.5    10790.0
금정    부산광역시      금정구    26311.0    22612.5     48923.5    24015.0    30757.0
기장    부산광역시      기장군    19328.5    17976.0     37304.5    14443.5    18941.5
남구    부산광역시       남구    30533.0    28115.5     58648.5    25945.5    33903.5
동구    부산광역시       동구    10041.5     9865.0     19906.5    10665.5    14501.0
동래    부산광역시      동래구    30188.5    29518.0     59706.5    25878.5    32988.0
부산    부산광역시     부산진구    48669.0    50455.0     99124.0    34943.0    45577.0
북구    부산광역시       북구    32188.5    28651.0     60839.5    27354.5    33229.0
사상    부산광역시      사상구    25499.0    22212.5     47711.5    21282.5    25606.0
사하    부산광역시      사하구    34709.0    29979.5     64688.5    31489.0    38888.0
서구    부산광역시       서구    10910.0    11166.5     22076.5    12620.5    16957.5
소계    부산광역시       소계   388220.0   367166.0    755386.0   332443.0   424992.0
수영    부산광역시      수영구    21802.0    22981.0     44783.0    18298.5    24573.5
연제    부산광역시      연제구    24731.5    24883.0     49614.5    20692.5    26628.5
영도    부산광역시      영도구    10196.0     8558.0     18754.0    14649.0    19270.5
중구    부산광역시       중구     4728.5     4678.5      9407.0     5093.0     6777.5
해운    부산광역시     해운대구    40810.0    39456.5     80266.5    35217.0    45603.5
강남    서울특별시      강남구    68355.0    77186.5    145541.5    39037.5    47853.0
강동    서울특별시      강동구    61809.5    64816.5    126626.0    38952.0    46353.5
강북    서울특별시      강북구    35722.0    35927.5     71649.5    29851.0    39365.0
강서    서울특별시      강서구    82616.0    90537.0    173153.0    45668.5    57734.5
관악    서울특별시      관악구   100644.0    93592.0    194236.0    38049.5    47608.0
광진    서울특별시      광진구    54063.0    58510.0    112573.0    25631.5    31549.5
구로    서울특별시      구로구    54823.0    55476.0    110299.0    35824.0    43632.0
금천    서울특별시      금천구    37405.5    34867.0     72272.5    20806.0    24575.5
노원    서울특별시      노원구    63430.5    62315.0    125745.5    41516.5    55935.0
도봉    서울특별시      도봉구    37196.5    36507.5     73704.0    31961.0    39532.0
동대    서울특별시     동대문구    51877.5    53678.5    105556.0    30059.0    37289.0
동작    서울특별시      동작구    60801.0    61998.5    122799.5    30790.5    39748.5
마포    서울특별시      마포구    55359.5    66167.5    121527.0    24272.5    33359.5
서대    서울특별시     서대문구    43824.5    48139.0     91963.5    24794.5    33063.5
서초    서울특별시      서초구    49522.5    56179.0    105701.5    29778.5    36016.5
성동    서울특별시      성동구    41665.0    43984.0     85649.0    21879.5    27602.0
성북    서울특별시      성북구    57870.5    61755.5    119626.0    34985.5    45824.0
소계    서울특별시       소계  1341060.0  1412954.0   2754014.0   777141.5   973956.5
송파    서울특별시      송파구    88915.5    98442.5    187358.0    50552.5    59209.0
양천    서울특별시      양천구    51785.0    51784.5    103569.5    34801.5    42527.5
영등    서울특별시     영등포구    61385.5    66128.5    127514.0    30095.0    36201.0
용산    서울특별시      용산구    31283.0    34187.0     65470.0    16673.0    21349.5
은평    서울특별시      은평구    60238.5    66107.0    126345.5    40811.5    53810.5
종로    서울특별시      종로구    19605.5    20873.0     40478.5    12827.0    15570.0
중구    서울특별시       중구    18226.5    19942.5     38169.0    11261.5    14145.0
중랑    서울특별시      중랑구    52635.0    53852.0    106487.0    36262.0    44103.0
세종  세종특별자치시  세종특별자치시    48086.5    48283.5     96370.0    19675.0    23830.5
소계  세종특별자치시       소계    48086.5    48283.5     96370.0    19675.0    23830.5
남구    울산광역시       남구    43246.5    34599.5     77846.0    22679.5    26168.0
동구    울산광역시       동구    18834.5    14709.5     33544.0    12663.0    13595.0
북구    울산광역시       북구    29486.0    23234.0     52720.0    11406.0    12861.5
소계    울산광역시       소계   142497.0   113299.5    255796.5    84302.5    96901.0
울주    울산광역시      울주군    25739.5    20269.0     46008.5    19235.5    22070.0
중구    울산광역시       중구    25190.5    20487.5     45678.0    18318.5    22206.5
강화    인천광역시      강화군     5076.5     4192.5      9269.0    12092.0    14009.5
계양    인천광역시      계양구    37512.5    33666.5     71179.0    22186.5    26443.5
남동    인천광역시      남동구    62031.5    56987.0    119018.5    38680.5    48979.0
동구    인천광역시       동구     6570.0     5733.5     12303.5     6643.0     8741.0
미추    인천광역시     미추홀구    56800.0    50027.0    106827.0    35702.0    45683.5
부평    인천광역시      부평구    67971.5    64198.0    132169.5    39238.0    50064.5
서구    인천광역시       서구    86169.0    82802.0    168971.0    36836.5    43448.0
소계    인천광역시       소계   400947.5   370962.5    771910.0   228801.0   281179.5
연수    인천광역시      연수구    51477.0    49997.5    101474.5    22749.0    26564.0
옹진    인천광역시      옹진군     2844.5     1262.5      4107.0     3157.0     3352.0
중구    인천광역시       중구    24495.0    22096.0     46591.0    11516.5    13894.5
소계       전국       소계  6582521.5  6049518.5  12632040.0  4396558.5  5502988.5
강진     전라남도      강진군     2424.0     2003.5      4427.5     5210.5     7265.5
고흥     전라남도      고흥군     3649.5     2832.0      6481.5    11244.5    15746.0
곡성     전라남도      곡성군     1893.0     1588.0      3481.0     4469.5     6051.5
광양     전라남도      광양시    20525.5    15865.0     36390.5    11123.0    13071.0
구례     전라남도      구례군     1549.5     1326.0      2875.5     3845.0     5429.5
나주     전라남도      나주시    13026.5    12088.5     25115.0    12278.0    16190.5
담양     전라남도      담양군     3792.5     3136.5      6929.0     6782.0     8706.5
목포     전라남도      목포시    23694.5    21006.5     44701.0    18641.0    24568.5
무안     전라남도      무안군    10193.5     9424.0     19617.5     8253.0    10891.0
보성     전라남도      보성군     2411.5     1877.0      4288.5     6586.5     9332.0
소계     전라남도       소계   186191.5   156024.5    342216.0   205052.0   269693.5
순천     전라남도      순천시    34507.5    30192.5     64700.0    22819.5    28735.0
신안     전라남도      신안군     2826.5     1794.0      4620.5     6703.5     8293.0
여수     전라남도      여수시    31596.5    25235.0     56831.5    27722.0    34360.0
영광     전라남도      영광군     4811.5     4194.5      9006.0     6893.0     9459.5
영암     전라남도      영암군     4825.0     3648.5      8473.5     6522.5     8821.0
완도     전라남도      완도군     3403.0     2624.0      6027.0     7133.0     9668.0
장성     전라남도      장성군     3765.5     2853.0      6618.5     6190.0     7993.0
장흥     전라남도      장흥군     2580.5     2101.0      4681.5     5420.5     7818.5
진도     전라남도      진도군     2202.0     1782.5      3984.5     4428.5     6204.0
함평     전라남도      함평군     2163.0     1658.5      3821.5     5142.0     7093.5
해남     전라남도      해남군     4831.5     3744.5      8576.0     9867.0    13466.5
화순     전라남도      화순군     5519.0     5049.5     10568.5     7777.5    10529.5
고창  전북특별자치도      고창군     3651.0     2929.5      6580.5     8350.5    11473.0
군산  전북특별자치도      군산시    28268.5    23702.5     51971.0    25745.0    32024.0
김제  전북특별자치도      김제시     7092.5     5897.0     12989.5    11874.5    16083.5
남원  전북특별자치도      남원시     6300.0     5398.5     11698.5    10258.5    13964.0
무주  전북특별자치도      무주군     1640.0     1319.0      2959.0     3690.5     4881.0
부안  전북특별자치도      부안군     3669.0     2861.0      6530.0     7817.0    10438.5
소계  전북특별자치도       소계   190569.5   167273.0    357842.5   185930.5   241376.5
순창  전북특별자치도      순창군     1919.5     1682.0      3601.5     4110.5     5747.0
완주  전북특별자치도      완주군    10658.5     9150.0     19808.5    11140.0    13348.5
익산  전북특별자치도      익산시    30629.5    26374.0     57003.5    27539.5    35258.5
임실  전북특별자치도      임실군     1860.5     1437.5      3298.0     4594.5     5779.0
장수  전북특별자치도      장수군     1382.0     1122.0      2504.0     3485.5     4590.5
전주  전북특별자치도      전주시    82721.5    76492.5    159214.0    49463.0    64238.5
정읍  전북특별자치도      정읍시     9189.5     7538.5     16728.0    13560.0    18372.5
진안  전북특별자치도      진안군     1587.5     1369.0      2956.5     4301.5     5178.0
서귀  제주특별자치도     서귀포시    17982.5    16348.5     34331.0    17821.0    22589.5
소계  제주특별자치도       소계    77607.0    71756.5    149363.5    53839.5    68537.0
제주  제주특별자치도      제주시    59624.5    55408.0    115032.5    36018.5    45947.5
계룡     충청남도      계룡시     5502.5     4710.0     10212.5     2990.0     3726.0
공주     충청남도      공주시    10120.5     8901.5     19022.0    13828.0    17014.5
금산     충청남도      금산군     3552.5     2863.0      6415.5     7871.5     9783.0
논산     충청남도      논산시    10151.5     8338.5     18490.0    14774.0    18938.5
당진     충청남도      당진시    20520.0    14667.5     35187.5    16336.5    19416.5
보령     충청남도      보령시     8756.0     6776.0     15532.0    12628.0    16119.0
부여     충청남도      부여군     4307.0     3369.5      7676.5    10617.0    13397.5
서산     충청남도      서산시    21945.5    15273.5     37219.0    16846.0    20522.0
서천     충청남도      서천군     3376.5     2565.0      5941.5     8637.0    11270.5
소계     충청남도       소계   260105.5   213178.0    473283.5   205537.5   255380.0
아산     충청남도      아산시    48871.5    40803.5     89675.0    22653.0    28219.5
예산     충청남도      예산군     6728.0     5437.0     12165.0    11945.0    14980.5
천안     충청남도      천안시    99260.0    85915.0    185175.0    39895.5    48500.0
청양     충청남도      청양군     2413.5     1784.0      4197.5     5293.0     6531.0
태안     충청남도      태안군     4755.0     3432.0      8187.0     9758.5    12128.0
홍성     충청남도      홍성군     9845.5     8342.0     18187.5    11464.5    14833.5
괴산     충청북도      괴산군     2395.0     1716.5      4111.5     6877.5     7768.0
단양     충청북도      단양군     1941.0     1457.0      3398.0     4700.5     5517.0
보은     충청북도      보은군     2097.0     1578.5      3675.5     5444.5     6793.0
소계     충청북도       소계   201118.5   164137.0    365255.5   151671.5   186521.0
영동     충청북도      영동군     3233.5     2545.5      5779.0     7295.5     8971.5
옥천     충청북도      옥천군     3767.0     3043.0      6810.0     7640.5     9154.0
음성     충청북도      음성군     9750.5     7159.5     16910.0    10800.5    12374.0
제천     충청북도      제천시    13833.0    11258.5     25091.5    15511.0    18791.5
증평     충청북도      증평군     4911.0     3689.5      8600.5     3484.5     4328.5
진천     충청북도      진천군    10996.0     8241.0     19237.0     7341.5     8876.0
청주     충청북도      청주시   123468.5   104501.0    227969.5    60832.0    76794.5
충주     충청북도      충주시    24726.0    18947.0     43673.0    21743.5    27153.0

                      인구수                              소멸비율 소멸위기지역
구분         합계          남자          여자          합계
id
강릉    52493.5    102917.5    104956.5    207874.0  0.368465   True
고성     8850.5     13890.0     13189.5     27079.5  0.220891   True
동해    21209.5     44582.5     43227.5     87810.0  0.333200   True
삼척    18224.0     31534.0     30499.5     62033.5  0.274610   True
소계   372293.5    762647.0    754712.5   1517359.5  0.386022   True
속초    18755.5     40077.0     41057.5     81134.5  0.394151   True
양구     5341.0     10901.5      9903.5     20805.0  0.339918   True
양양     9451.5     14092.5     13433.0     27525.5  0.180871   True
영월    12814.0     19072.5     17788.5     36861.0  0.172897   True
원주    66081.5    178287.0    182094.5    360381.5  0.628867  False

In [211]:
geo_path = 'C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/05. skorea_municipalities_geo_simple.json'
geo_data = json.load(open('C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/05. skorea_municipalities_geo_simple.json',encoding='utf-8'))

map2 = folium.Map(location=[36,127], zoom_start=7)

In [212]:
folium.Choropleth(geo_data=geo_data, 
               data=popl_map['인구수합계'],
               columns=[popl_map.index, popl_map['인구수합계']],
               key_on='feature.id',
               fill_color='YlGnBu').add_to(map2)

TypeError: 'NoneType' object is not subscriptable

In [ ]:
geo_data

In [ ]:
map2

In [ ]:
map2 = folium.Map(location=[36.2002, 127.054], zoom_start=7)
folium.Choropleth(geo_data=geo_data, 
               data=popl_map['소멸위기지역'],
               columns=[popl_map.index, popl_map['소멸위기지역']],
               key_on='feature.id',
               fill_color='PuRd').add_to(map2)
map2

In [ ]:
popl.columns = popl.columns.get_level_values(0)