In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [9]:
my_key = pd.read_csv("C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/api_key.txt",
                     header=None).iloc[0,0]

In [10]:
my_key

'accc226aba90e01bb632eb0bc06e1fe71b711c4f1144a8512c3a589482c0c514'

In [11]:
baseurl ="https://apis.data.go.kr/1613000/RTMSDataSvcAptTrade/getRTMSDataSvcAptTrade"

In [12]:
area_cd = 'LAWD_CD=' + '11110'
datetime = 'DEAL_YMD=' + '202511'
survice_key = 'serviceKey=' + my_key

In [13]:
url = baseurl + "?" + area_cd + '&' + datetime + '&' + survice_key

In [14]:
response = requests.get(url)
response

In [15]:
response.text

'<?xml version="1.0" encoding="utf-8" standalone="yes"?><response><header><resultCode>000</resultCode><resultMsg>OK</resultMsg></header><body><items><item><aptDong> </aptDong><aptNm>광화문스페이스본(101동~105동)</aptNm><buildYear>2008</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>151,000</dealAmount><dealDay>21</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>직거래</dealingGbn><estateAgentSggNm> </estateAgentSggNm><excluUseAr>158.99</excluUseAr><floor>3</floor><jibun>9</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>사직동</umdNm></item><item><aptDong> </aptDong><aptNm>종로중흥S클래스</aptNm><buildYear>2013</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>12,600</dealAmount><dealDay>13</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>19.466</excluUseAr><floor>8</floor><jibun>202-3</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>숭인동</umdNm></item><item><aptDong> </aptDong><aptNm>인왕산2차아이파크</aptNm><buildYear>2015</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>130,000</dealAmount><dealDay>18</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 강서구, 서울 서대문구</estateAgentSggNm><excluUseAr>84.068</excluUseAr><floor>12</floor><jibun>88</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>무악동</umdNm></item><item><aptDong> </aptDong><aptNm>종로중흥S클래스</aptNm><buildYear>2013</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>12,250</dealAmount><dealDay>13</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>17.811</excluUseAr><floor>9</floor><jibun>202-3</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>숭인동</umdNm></item><item><aptDong> </aptDong><aptNm>롯데미도파광화문빌딩</aptNm><buildYear>1981</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>57,000</dealAmount><dealDay>13</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>65.82</excluUseAr><floor>9</floor><jibun>145</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>당주동</umdNm></item><item><aptDong> </aptDong><aptNm>경희궁자이(4단지)</aptNm><buildYear>2017</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>87,000</dealAmount><dealDay>11</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>37.2635</excluUseAr><floor>7</floor><jibun>126</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>교북동</umdNm></item><item><aptDong> </aptDong><aptNm>창신쌍용1</aptNm><buildYear>1992</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>64,000</dealAmount><dealDay>7</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>54.7</excluUseAr><floor>3</floor><jibun>702</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>창신동</umdNm></item><item><aptDong> </aptDong><aptNm>이화에수풀</aptNm><buildYear>2014</buildYear><buyerGbn>개인</buyerGbn><cdealDay> </cdealDay><cdealType> </cdealType><dealAmount>23,500</dealAmount><dealDay>2</dealDay><dealMonth>11</dealMonth><dealYear>2025</dealYear><dealingGbn>중개거래</dealingGbn><estateAgentSggNm>서울 종로구</estateAgentSggNm><excluUseAr>19.86</excluUseAr><floor>7</floor><jibun>195-10</jibun><landLeaseholdGbn>N</landLeaseholdGbn><rgstDate> </rgstDate><sggCd>11110</sggCd><slerGbn>개인</slerGbn><umdNm>연건동</umdNm></item></items><numOfRows>10</numOfRows><pageNo>1</pageNo><totalCount>8</totalCount></body></response>'

In [16]:
lawd = pd.read_csv("C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/법정동코드 전체자료.txt",
                  sep='\t', encoding='cp949')
lawd

            법정동코드                  법정동명 폐지여부
0      1100000000                 서울특별시   존재
1      1111000000             서울특별시 종로구   존재
2      1111010100         서울특별시 종로구 청운동   존재
3      1111010200         서울특별시 종로구 신교동   존재
4      1111010300         서울특별시 종로구 궁정동   존재
...           ...                   ...  ...
49856  5280042024    전북특별자치도 부안군 위도면 대리   존재
49857  5280042025   전북특별자치도 부안군 위도면 거륜리   존재
49858  5280042026   전북특별자치도 부안군 위도면 식도리   존재
49859  5280042027  전북특별자치도 부안군 위도면 상왕등리   존재
49860  5280042028  전북특별자치도 부안군 위도면 하왕등리   존재

[49861 rows x 3 columns]

In [17]:
lawd.columns = ['code', 'area', 'cheek']
lawd

             code                  area cheek
0      1100000000                 서울특별시    존재
1      1111000000             서울특별시 종로구    존재
2      1111010100         서울특별시 종로구 청운동    존재
3      1111010200         서울특별시 종로구 신교동    존재
4      1111010300         서울특별시 종로구 궁정동    존재
...           ...                   ...   ...
49856  5280042024    전북특별자치도 부안군 위도면 대리    존재
49857  5280042025   전북특별자치도 부안군 위도면 거륜리    존재
49858  5280042026   전북특별자치도 부안군 위도면 식도리    존재
49859  5280042027  전북특별자치도 부안군 위도면 상왕등리    존재
49860  5280042028  전북특별자치도 부안군 위도면 하왕등리    존재

[49861 rows x 3 columns]

In [18]:
def find_lawd_cd(in_text):
    result = lawd[(lawd['area'].str.contains(in_text)) & (lawd['cheek'] == "존재")].head(1).iloc[0,0].astype(str)[0:5]    
    return result

In [19]:
in_name = "서울특별시"
find_lawd_cd(in_name)

'11000'

In [20]:
find_lawd_cd('중구')

'11140'

In [21]:
in_lawd = input("검색지 입력 : ")

검색지 입력 :

In [22]:
in_deal_ymd = input("계약월 입력(예: 201912) : ")

계약월 입력(예: 201912) :

In [23]:
soup = BeautifulSoup(response.text, 'lxml')
soup

C:\Users\USER\anaconda3\lib\site-packages\bs4\builder\__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

<?xml version="1.0" encoding="utf-8" standalone="yes"?><html><body><response><header><resultcode>000</resultcode><resultmsg>OK</resultmsg></header><items><item><aptdong> </aptdong><aptnm>광화문스페이스본(101동~105동)</aptnm><buildyear>2008</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>151,000</dealamount><dealday>21</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>직거래</dealinggbn><estateagentsggnm> </estateagentsggnm><excluusear>158.99</excluusear><floor>3</floor><jibun>9</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>사직동</umdnm></item><item><aptdong> </aptdong><aptnm>종로중흥S클래스</aptnm><buildyear>2013</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>12,600</dealamount><dealday>13</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>19.466</excluusear><floor>8</floor><jibun>202-3</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>숭인동</umdnm></item><item><aptdong> </aptdong><aptnm>인왕산2차아이파크</aptnm><buildyear>2015</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>130,000</dealamount><dealday>18</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강서구, 서울 서대문구</estateagentsggnm><excluusear>84.068</excluusear><floor>12</floor><jibun>88</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>무악동</umdnm></item><item><aptdong> </aptdong><aptnm>종로중흥S클래스</aptnm><buildyear>2013</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>12,250</dealamount><dealday>13</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>17.811</excluusear><floor>9</floor><jibun>202-3</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>숭인동</umdnm></item><item><aptdong> </aptdong><aptnm>롯데미도파광화문빌딩</aptnm><buildyear>1981</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>57,000</dealamount><dealday>13</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>65.82</excluusear><floor>9</floor><jibun>145</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>당주동</umdnm></item><item><aptdong> </aptdong><aptnm>경희궁자이(4단지)</aptnm><buildyear>2017</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>87,000</dealamount><dealday>11</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>37.2635</excluusear><floor>7</floor><jibun>126</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>교북동</umdnm></item><item><aptdong> </aptdong><aptnm>창신쌍용1</aptnm><buildyear>1992</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>64,000</dealamount><dealday>7</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>54.7</excluusear><floor>3</floor><jibun>702</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>창신동</umdnm></item><item><aptdong> </aptdong><aptnm>이화에수풀</aptnm><buildyear>2014</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>23,500</dealamount><dealday>2</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>19.86</excluusear><floor>7</floor><jibun>195-10</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>연건동</umdnm></item></items><numofrows>10</numofrows><pageno>1</pageno><totalcount>8</totalcount></response></body></html>

In [24]:
soup.find_all('item')

[<item><aptdong> </aptdong><aptnm>광화문스페이스본(101동~105동)</aptnm><buildyear>2008</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>151,000</dealamount><dealday>21</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>직거래</dealinggbn><estateagentsggnm> </estateagentsggnm><excluusear>158.99</excluusear><floor>3</floor><jibun>9</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>사직동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>종로중흥S클래스</aptnm><buildyear>2013</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>12,600</dealamount><dealday>13</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>19.466</excluusear><floor>8</floor><jibun>202-3</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>숭인동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>인왕산2차아이파크</aptnm><buildyear>2015</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>130,000</dealamount><dealday>18</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 강서구, 서울 서대문구</estateagentsggnm><excluusear>84.068</excluusear><floor>12</floor><jibun>88</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>무악동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>종로중흥S클래스</aptnm><buildyear>2013</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>12,250</dealamount><dealday>13</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>17.811</excluusear><floor>9</floor><jibun>202-3</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>숭인동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>롯데미도파광화문빌딩</aptnm><buildyear>1981</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>57,000</dealamount><dealday>13</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>65.82</excluusear><floor>9</floor><jibun>145</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>당주동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>경희궁자이(4단지)</aptnm><buildyear>2017</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>87,000</dealamount><dealday>11</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>37.2635</excluusear><floor>7</floor><jibun>126</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>교북동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>창신쌍용1</aptnm><buildyear>1992</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>64,000</dealamount><dealday>7</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>54.7</excluusear><floor>3</floor><jibun>702</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>창신동</umdnm></item>,
 <item><aptdong> </aptdong><aptnm>이화에수풀</aptnm><buildyear>2014</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>23,500</dealamount><dealday>2</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>중개거래</dealinggbn><estateagentsggnm>서울 종로구</estateagentsggnm><excluusear>19.86</excluusear><floor>7</floor><jibun>195-10</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>연건동</umdnm></item>]

In [25]:
item = soup.find('item')
print(item)

<item><aptdong> </aptdong><aptnm>광화문스페이스본(101동~105동)</aptnm><buildyear>2008</buildyear><buyergbn>개인</buyergbn><cdealday> </cdealday><cdealtype> </cdealtype><dealamount>151,000</dealamount><dealday>21</dealday><dealmonth>11</dealmonth><dealyear>2025</dealyear><dealinggbn>직거래</dealinggbn><estateagentsggnm> </estateagentsggnm><excluusear>158.99</excluusear><floor>3</floor><jibun>9</jibun><landleaseholdgbn>N</landleaseholdgbn><rgstdate> </rgstdate><sggcd>11110</sggcd><slergbn>개인</slergbn><umdnm>사직동</umdnm></item>

In [26]:
import xml.etree.ElementTree as ET

In [27]:
root = ET.fromstring(response.content)
root

In [28]:
item_list = []

In [29]:
root.find('body').find('items')[0]

In [30]:
type(root.find('body').find('items'))

xml.etree.ElementTree.Element

In [31]:
child = root.find('body').find('items')[0]
child

In [32]:
child.findall('*')#[0]

[<Element 'aptDong' at 0x000002B8526F04A0>,
 <Element 'aptNm' at 0x000002B8526F04F0>,
 <Element 'buildYear' at 0x000002B8526F0540>,
 <Element 'buyerGbn' at 0x000002B8526F0590>,
 <Element 'cdealDay' at 0x000002B8526F05E0>,
 <Element 'cdealType' at 0x000002B8526F0630>,
 <Element 'dealAmount' at 0x000002B8526F0680>,
 <Element 'dealDay' at 0x000002B8526F06D0>,
 <Element 'dealMonth' at 0x000002B8526F0720>,
 <Element 'dealYear' at 0x000002B8526F0770>,
 <Element 'dealingGbn' at 0x000002B8526F07C0>,
 <Element 'estateAgentSggNm' at 0x000002B8526F0860>,
 <Element 'excluUseAr' at 0x000002B8526F08B0>,
 <Element 'floor' at 0x000002B8526F0900>,
 <Element 'jibun' at 0x000002B8526F0950>,
 <Element 'landLeaseholdGbn' at 0x000002B8526F09F0>,
 <Element 'rgstDate' at 0x000002B8526F0A40>,
 <Element 'sggCd' at 0x000002B8526F0A90>,
 <Element 'slerGbn' at 0x000002B8526F0AE0>,
 <Element 'umdNm' at 0x000002B8526F0B30>]

In [33]:
element = child.findall('*')[0]
element

In [34]:
element.tag.strip()

'aptDong'

In [35]:
data = {}

In [36]:
tag = element.tag.strip()
text = element.text.strip()
data[tag] = text

In [37]:
data

{'aptDong': ''}

In [38]:
def find_xml_items(response):
    root = ET.fromstring(response.content)
    item_list = []
    for child in root.find('body').find('items'):
        elements = child.findall('*')
        data = {}
        for element in elements:
            tag = element.tag.strip()
            text = element.text.strip()
            data[tag] = text
        item_list.append(data)  
    return item_list

In [39]:
items_list = find_xml_items(response)
items_list

[{'aptDong': '',
  'aptNm': '광화문스페이스본(101동~105동)',
  'buildYear': '2008',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '151,000',
  'dealDay': '21',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '직거래',
  'estateAgentSggNm': '',
  'excluUseAr': '158.99',
  'floor': '3',
  'jibun': '9',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '사직동'},
 {'aptDong': '',
  'aptNm': '종로중흥S클래스',
  'buildYear': '2013',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '12,600',
  'dealDay': '13',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '19.466',
  'floor': '8',
  'jibun': '202-3',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '숭인동'},
 {'aptDong': '',
  'aptNm': '인왕산2차아이파크',
  'buildYear': '2015',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '130,000',
  'dealDay': '18',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강서구, 서울 서대문구',
  'excluUseAr': '84.068',
  'floor': '12',
  'jibun': '88',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '무악동'},
 {'aptDong': '',
  'aptNm': '종로중흥S클래스',
  'buildYear': '2013',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '12,250',
  'dealDay': '13',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '17.811',
  'floor': '9',
  'jibun': '202-3',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '숭인동'},
 {'aptDong': '',
  'aptNm': '롯데미도파광화문빌딩',
  'buildYear': '1981',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '57,000',
  'dealDay': '13',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '65.82',
  'floor': '9',
  'jibun': '145',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '당주동'},
 {'aptDong': '',
  'aptNm': '경희궁자이(4단지)',
  'buildYear': '2017',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '87,000',
  'dealDay': '11',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '37.2635',
  'floor': '7',
  'jibun': '126',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '교북동'},
 {'aptDong': '',
  'aptNm': '창신쌍용1',
  'buildYear': '1992',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '64,000',
  'dealDay': '7',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '54.7',
  'floor': '3',
  'jibun': '702',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '창신동'},
 {'aptDong': '',
  'aptNm': '이화에수풀',
  'buildYear': '2014',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '23,500',
  'dealDay': '2',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '19.86',
  'floor': '7',
  'jibun': '195-10',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '연건동'}]

In [40]:
result = pd.DataFrame(items_list)

In [41]:
result

,aptDong,aptNm,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,dealDay,dealMonth,dealYear,dealingGbn,estateAgentSggNm,excluUseAr,floor,jibun,landLeaseholdGbn,rgstDate,sggCd,slerGbn,umdNm
0,,광화문스페이스본(101동~105동),2008,개인,,,"151,000",21,11,2025,직거래,,158.99,3,9,N,,11110,개인,사직동
1,,종로중흥S클래스,2013,개인,,,"12,600",13,11,2025,중개거래,서울 종로구,19.466,8,202-3,N,,11110,개인,숭인동
2,,인왕산2차아이파크,2015,개인,,,"130,000",18,11,2025,중개거래,"서울 강서구, 서울 서대문구",84.068,12,88,N,,11110,개인,무악동
3,,종로중흥S클래스,2013,개인,,,"12,250",13,11,2025,중개거래,서울 종로구,17.811,9,202-3,N,,11110,개인,숭인동
4,,롯데미도파광화문빌딩,1981,개인,,,"57,000",13,11,2025,중개거래,서울 종로구,65.82,9,145,N,,11110,개인,당주동
5,,경희궁자이(4단지),2017,개인,,,"87,000",11,11,2025,중개거래,서울 종로구,37.2635,7,126,N,,11110,개인,교북동
6,,창신쌍용1,1992,개인,,,"64,000",7,11,2025,중개거래,서울 종로구,54.7,3,702,N,,11110,개인,창신동
7,,이화에수풀,2014,개인,,,"23,500",2,11,2025,중개거래,서울 종로구,19.86,7,195-10,N,,11110,개인,연건동

In [42]:
result.shape

(8, 20)

In [43]:
find_xml_items(response)

[{'aptDong': '',
  'aptNm': '광화문스페이스본(101동~105동)',
  'buildYear': '2008',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '151,000',
  'dealDay': '21',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '직거래',
  'estateAgentSggNm': '',
  'excluUseAr': '158.99',
  'floor': '3',
  'jibun': '9',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '사직동'},
 {'aptDong': '',
  'aptNm': '종로중흥S클래스',
  'buildYear': '2013',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '12,600',
  'dealDay': '13',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '19.466',
  'floor': '8',
  'jibun': '202-3',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '숭인동'},
 {'aptDong': '',
  'aptNm': '인왕산2차아이파크',
  'buildYear': '2015',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '130,000',
  'dealDay': '18',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강서구, 서울 서대문구',
  'excluUseAr': '84.068',
  'floor': '12',
  'jibun': '88',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '무악동'},
 {'aptDong': '',
  'aptNm': '종로중흥S클래스',
  'buildYear': '2013',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '12,250',
  'dealDay': '13',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '17.811',
  'floor': '9',
  'jibun': '202-3',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '숭인동'},
 {'aptDong': '',
  'aptNm': '롯데미도파광화문빌딩',
  'buildYear': '1981',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '57,000',
  'dealDay': '13',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '65.82',
  'floor': '9',
  'jibun': '145',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '당주동'},
 {'aptDong': '',
  'aptNm': '경희궁자이(4단지)',
  'buildYear': '2017',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '87,000',
  'dealDay': '11',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '37.2635',
  'floor': '7',
  'jibun': '126',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '교북동'},
 {'aptDong': '',
  'aptNm': '창신쌍용1',
  'buildYear': '1992',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '64,000',
  'dealDay': '7',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '54.7',
  'floor': '3',
  'jibun': '702',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '창신동'},
 {'aptDong': '',
  'aptNm': '이화에수풀',
  'buildYear': '2014',
  'buyerGbn': '개인',
  'cdealDay': '',
  'cdealType': '',
  'dealAmount': '23,500',
  'dealDay': '2',
  'dealMonth': '11',
  'dealYear': '2025',
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 종로구',
  'excluUseAr': '19.86',
  'floor': '7',
  'jibun': '195-10',
  'landLeaseholdGbn': 'N',
  'rgstDate': '',
  'sggCd': '11110',
  'slerGbn': '개인',
  'umdNm': '연건동'}]

In [44]:
def deal_by_lawd(cd_name, ymd):
    
    func_cd = find_lawd_cd(cd_name)
    
    svckey = my_key
    
    area_cd = "LAWD_CD=" + func_cd
    deal_dt = "DEAL_YMD=" + ymd
    svc_key = "serviceKey=" + svckey
    url = baseurl + "?" + area_cd + "&" + deal_dt + "&" + svc_key

    response = requests.get(url)
    items_list = find_xml_items(response)
    result = pd.DataFrame(items_list)
    
    name_info = cd_name + "_" + ymd
    file_name = f"C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/result_{name_info}.csv"

    result.to_csv(file_name, index=False, encoding='cp949')
    
    return file_name

In [100]:
func_gu = input("검색지역 입력 : ")
print(func_gu)

func_ymd = input("계약월 입력(예: 201911) : ")
print(func_ymd)

검색지역 입력 : 강동구
강동구
계약월 입력(예: 201911) : 202511
202511

In [101]:
deal_by_lawd(func_gu, func_ymd)

'C:/Users/USER/Desktop/연습데이터/WEEK03_01_공공데이터수집/data/result_강동구_202511.csv'